### ISSUE TITLE
Expire CredentialsRef in a proper time to reduce memory usage

### ISSUE THREAD

**Issue by zhouyifan279** [apache/incubator-kyuubi#1021]
### 1. Describe the feature
This is the a sub-task under umbrella issue #913. 

In sub-task #1007,  <user, CredentialsRef> pairs are cached in a Map. Credentials are periodically renewed  and will never be removed.
If a lot of inactive users' credentials are cached, both memory usage and credentials renewal load may become unacceptable.
So we should implement a logic to expire cached <user, CredentialsRef> pairs to erase this risk.

**Comment by lightning-L** [comment]
Hi, I'd like to try to implement this.

**Comment by ulysses-you** [comment]
@lightning-L assigned, thank you
