### ISSUE TITLE
Add Kyuubi server event

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1050]
### 1. Describe the feature
Add Kyuubi server event in `KyuubiServer` so we can get the server level info:

* server config
* server verion
* server environment

**Comment by zhenjiaguo** [comment]
Are you working on this? If not, maybe I can help.

**Comment by ulysses-you** [comment]
thank you @zhenjiaguo , it's helpful if you are interesting in this.
