### ISSUE TITLE
[Bug] Output error log when currentEngine is None

### ISSUE THREAD

**Issue by hddong** [apache/incubator-kyuubi#1056]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When createSpark in `SparkSqlEngine` get sparksession or execute initialize.sql failed, we cannot get any error info in logs. At this time, `currentEngine` is `None`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
the issue title is missing
