### ISSUE TITLE
Fix Kyuubi download page issue  and website releases page issue

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#1110]
### Describe the bug

As mentioned in mail list,
https://lists.apache.org/thread.html/r4dbc84ae39b51d46680bd827442bc81b993d4c28e7f1282e35529b63%40%3Cdev.kyuubi.apache.org%3E

There is some issue for the release page and website
-  A download page must use the ASF mirror system (closer.lua) and havelinks to KEYS, sigs and hashes.
- The website releases page is not valid: https://kyuubi.apache.org/releases.html
- The website is missing the Incubator disclaimer

**Comment by turboFei** [comment]
For the download page:
1. the tarball should not link to downloads link directly

For the website release page:
1. we should place latest release versions on the release page, and link to release archive for the others
2. do not link to github releases page

**Comment by pan3793** [comment]
Updated:

- [x] Add Incubator disclaimer for website, please check https://kyuubi.apache.org/
- [x] Auto deploy ASF site from `master` branch of apache/incubator-kyuubi-website
- [x] Update releases page to match project dist areas, and remove GitHub releases page links, please check https://kyuubi.apache.org/releases.html
- [x] Update links, use https://www.apache.org/dyn/closer.lua for release, use https://downloads.apache.org/ for hashes and signatures, please check https://kyuubi.apache.org/release/1.3.0-incubating.html

**Comment by pan3793** [comment]
cc @Apache9 @WillemJiang, would you please take a look? Thanks.

**Comment by Apache9** [comment]
+1

**Comment by yaooqinn** [comment]
Thank you @turboFei @pan3793 for fixing this and @Apache9 for the confirmation

**Comment by sebbASF** [comment]
Getting there, but:

There is no link to the KEYS file from the download page [1].

There is no mention of the need to verify downloads, nor how to do so.


[1] https://kyuubi.apache.org/release/1.3.0-incubating.html

**Comment by pan3793** [comment]
Thanks @sebbASF, will update soon.

**Comment by turboFei** [comment]
Thanks @sebbASF, I have updated the download page,

https://kyuubi.apache.org/releases.html

**Comment by sebbASF** [comment]
Thanks, but there are still some issues.

- The KEYS file must be linked from: https://downloads.apache.org/incubator/kyuubi/KEYS

- gpg requires -- (hyphen hyphen) before qualifiers, not '\&dash;'

- gpg --verify should have a second parameter, e.g
gpg –verify apache-kyuubi-X.Y.Z-incubating-source.tgz.asc apache-kyuubi-X.Y.Z-incubating-source.tgz
See: https://www.apache.org/info/verification.html#specify_both

- Also the 1.3.0 release page has not been fixed.

**Comment by pan3793** [comment]
> The KEYS file must be linked from: https://downloads.apache.org/incubator/kyuubi/KEYS

Fixed.

> gpg requires -- (hyphen hyphen) before qualifiers, not '&dash;'
> gpg --verify should have a second parameter, e.g
> gpg –verify apache-kyuubi-X.Y.Z-incubating-source.tgz.asc apache-kyuubi-X.Y.Z-incubating-source.tgz
> See: https://www.apache.org/info/verification.html#specify_both

Replaced by [Verify Instructions](https://www.apache.org/dyn/closer.cgi#verify) page's hyperlink

> Also the 1.3.0 release page has not been fixed.

Removed download information from release note page

@sebbASF thanks for pointing issues, would you please take a look again?

**Comment by sebbASF** [comment]
Looks OK now, thanks.

It's good that the download and release notes pages link to each other, and no longer duplicate information.

**Comment by pan3793** [comment]
Thanks @sebbASF for confirmation!
