### ISSUE TITLE
[FEATURE] Add `Affects Version/s`  area in bug report isusse template

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1115]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

`Affects Version/s`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @byyue

**Comment by timothy65535** [comment]
Error msg still need to enhance, also can label `beginner`.

https://github.com/apache/incubator-kyuubi/blob/master/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/SparkSQLEngine.scala#L154-L165

```
```
