### ISSUE TITLE
[Bug] KyuubiFrontendServices 's oom hook should call the stop on serverable level

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1137]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

we shall stop the entire server instead of the FrontendServices only

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @yanghua

**Comment by yanghua** [comment]
> cc @yanghua

Take this ticket.
