### ISSUE TITLE
[FEATURE] Enhance zookeeper authentication and acls of Kyuubi HA module

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1204]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support zookeeper sasl kerberos authentication of engine and more zookeeper ACL Schemes.

### Describe the solution

Zookeeper 支持多种类型的 ACL Schemes，下面列出两种典型进行说明 

1. 支持 SASL Kerberos 类型的 ACL

    节点 ACLs 示例：

    ```
    'world,'anyone
    : r
    'sasl,'test
    : cdrwa
    ```

    配置规划：

    ```
    kyuubi.ha.zookeeper.acl.enabled=true
    kyuubi.ha.zookeeper.auth.sasl.kerberos=true   # 使用 sasl kerberos 类型认证
    
    # 还需要 kerberos 相关配置
    ```

    其它修改：
    + Yarn Cluster 模式运行 Engine 时，通过 --file 上传 keytab 文件，并指定相对路径访问 keytab 文件

2. 支持 Digest 类型的 ACL

    节点 ACLs 示例：

    ```
    'world,'anyone
    : r
    'digest,'test:V28q/NynI4JI3Rk54h0r8O5kMug=
    : cdrwa
    ```

    配置规划：

    ```
    kyuubi.ha.zookeeper.acl.enabled=true
    kyuubi.ha.zookeeper.auth=digest:test:test   # 使用 auth string 进行认证，格式：scheme:expression:perms
    ```

    其它修改：
    + 将 kyuubi.ha.zookeeper.auth 配置解析为 AuthInfo 对象，通过 CuratorFrameworkFactory.Builder#authorization 方法添加认证

参考：
+ [ZooKeeper access control using ACLs](http://zookeeper.apache.org/doc/r3.7.0/zookeeperProgrammers.html#sc_ZooKeeperAccessControl)
+ [ZooKeeper and SASL](https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+and+SASL)
+ [zookeeper（client-server身份认证-SASL配置）](https://www.liangzl.com/get-article-detail-167111.html)

### Additional context

I don’t have a deep understanding of the Zookeeper authentication mechanism. If you have any questions, please point them out. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
That's true. But it will be difficult and hacky to let the Kyuubi server know whether the engine is in client mode or not.

**Comment by wForget** [comment]
> That's true. But it will be difficult and hacky to let the Kyuubi server know whether the engine is in client mode or not.

After adding the --file configuration, the keytab path needs to be changed to a relative path. Is there a problem changing to a relative path in the yarn client mode?

**Comment by yaooqinn** [comment]
> Is there a problem changing to a relative path in the yarn client mode?

I guess it is not a problem and as same as in the yarn cluster mode, maybe also other cluster managers

**Comment by wForget** [comment]
> Looks like we have to detect the value of `--conf spark.kyuubi.kinit.keytab=kyuubi.keytab \` at engine side after spark gets instantiated not pass it from server to engine

Sorry, @yaooqinn , I don't quite understand this reply. The current detection is on the Engine side.
This problem may be due to the fact that spark.files are not placed in the user.home directory in yarn-client mode, resulting in inaccessible relative paths. Should we distinguish between client and cluster modes?

**Comment by yaooqinn** [comment]
It looks fine to me. However, can we merge some of these configurations, it is now very hard to explain and use.
```
kyuubi.ha.zookeeper.acl.enabled=true
kyuubi.ha.zookeeper.auth.sasl.kerberos=false
kyuubi.ha.zookeeper.auth=digest:hue:***
kyuubi.ha.zookeeper.acl.engine.enabled=true
```

cc @zhouyifan279, do you have any idea, if we can add some unit tests to test with a kerberied zookeeper and acls

**Comment by wForget** [comment]
@yaooqinn Looks good, Can we add the following fallback configuration? 

```
kyuubi.ha.zookeeper.engine.auth.type     fallback to kyuubi.ha.zookeeper.auth.type
kyuubi.ha.zookeeper.auth.principal       fallback to kyuubi.kinit.principal
kyuubi.ha.zookeeper.auth.keytab          fallback to kyuubi.kinit.keytab
```

**Comment by wForget** [comment]
> As we already have `org.apache.kyuubi.KerberizedTestHelper` to setup a KDC, and zookeeper uses JAAS to integrates with kerberos , it should be easy to setup an kerberied embedded zookeeper server.
> 
> @wForget , would you mind to add these test cases ?
> 
> I'm also glad to do the work if you have no time.

Thanks @zhouyifan279 , I still have some configurations to be adjusted. After completion, I will improve the test cases according to your suggestions.
