### ISSUE TITLE
[DOC] Document support incremental collection

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1215]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add document for [KYUUBI #1198] Support incremental collection

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
any update on this, I think this doc needs to be updated in 1.5.0-incubating

**Comment by pan3793** [comment]
Will add the document soon
