### ISSUE TITLE
[Bug] Met error when run KyuubiServer in IDEA

### ISSUE THREAD

**Issue by charlesy6** [apache/incubator-kyuubi#1229]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When debug KyuubiServer in IDEA, IDEA: Intellij IDEA 2021.2(Ultimate Edition)

throw exception
```
/KyuubiHiveDriverSuite.scala:45:36
Class org.apache.hive.jdbc.HiveConnection not found - continuing with a stub.
    assert(connection.isInstanceOf[KyuubiConnection])
```

```
/KyuubiHiveDriverSuite.scala:47:34
Class org.apache.hive.jdbc.HiveDatabaseMetaData not found - continuing with a stub.
    assert(metaData.isInstanceOf[KyuubiDatabaseMetaData])
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by timothy65535** [comment]
cc @pan3793 
it happened after https://github.com/apache/incubator-kyuubi/pull/1151

**Comment by pan3793** [comment]
I see, ref: https://youtrack.jetbrains.com/issue/IDEA-126596

**Comment by pan3793** [comment]
It should happen after #1149

**Comment by timothy65535** [comment]
> I see, ref: https://youtrack.jetbrains.com/issue/IDEA-126596

I will check it.

BTW, I tried add following dependency, everything ok.
```
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-jdbc</artifactId>
            <version>${hive.jdbc.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by pan3793** [comment]
Would you please run `build/mvn clean install -pl kyuubi-hive-jdbc` first, and try debug in IDEA again?

**Comment by timothy65535** [comment]
> Would you please run `build/mvn clean install -pl kyuubi-hive-jdbc` first, and try debug in IDEA again?

Already tried

- Remove all `org/apache/kyuubi/*` directory from local mvn repos
- `mvn clean install -DskipTests`

OK, will try one more again.

**Comment by timothy65535** [comment]
Can not found `org.apache.hive` package from kyuubi-hive-jdbc-1.4.1.1.jar, so seems we need to add `hive-jdbc` to engine module.

![image](https://user-images.githubusercontent.com/86483005/137241562-40bdd8fe-60aa-4e80-9eb2-750983561b0b.png)

**Comment by pan3793** [comment]
The error gone in my laptop if I change `assert(connection.isInstanceOf[KyuubiConnection])` to `assert(connection.getClass.name === "org.apache.kyuubi.jdbc.hive.KyuubiConnection")` to cut the ref of shaded classes, please have a try.

**Comment by timothy65535** [comment]
> `kyuubi-hive-jdbc` module to resolve 1) and create a shaded jar to resolve 2)

We can use test scope.

Or fix it by using your solution.

**Comment by timothy65535** [comment]
> So we need to install module kyuubi-hive-jdbc to maven local repository first after this change?

No need.

**Comment by pan3793** [comment]
> Then I met the same error with this change.

Execute Build => Build Project(⌘+9) or Rebuild Project before running the test.

**Comment by timothy65535** [comment]
cc @pan3793, can not found class.

![image](https://user-images.githubusercontent.com/86483005/137265042-a55c141c-4fe3-4a7d-8673-26dff3a02b5b.png)
