### ISSUE TITLE
[FEATURE] Support use helm to deploy kyuubi server on k8s

### ISSUE THREAD

**Issue by hddong** [apache/incubator-kyuubi#1253]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We usally use helm to manager application yaml on k8s, we can use helm to delopy kyuubi server too.
Usages:
```
helm install kyuubi ${kyuubi_helm_url} -n kyuubi
```
```
helm uninstall kyuubi -n kyuubi
```

### Motivation

Easy delopy on k8s

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by avinovarov** [comment]
Helm chart actually exists: https://github.com/apache/incubator-kyuubi/tree/master/docker/helm

Some features like env vars from secrets, nodeSelectors and tolerations are yet missing but easy to add.

**Comment by hddong** [comment]
@avinovarov : Yes, will close this issuse. Welcome to submit PRs to improve .
