### ISSUE TITLE
[FEATURE] Support session && statements stats on SparkHistoryServer Page

### ISSUE THREAD

**Issue by cody195** [apache/incubator-kyuubi#1311]
### 1. Describe the feature

Support session && statements stats on SparkHistoryServer Page.

For more detail, please go to https://github.com/apache/incubator-kyuubi/issues/981

### 2. Test steps

- Run spark history server

```
\cp kyuubi-common/target/kyuubi-common_2.12-1.4.0-SNAPSHOT.jar /install/spark/spark-3.1.2-bin-hadoop2.7/jars
\cp externals/kyuubi-spark-sql-engine/target/kyuubi-spark-sql-engine_2.12-1.4.0-SNAPSHOT.jar /install/spark/spark-3.1.2-bin-hadoop2.7/jars

sbin/stop-history-server.sh
sbin/start-history-server.sh
```

- Run kyuubi job

```
./bin/beeline -u 'jdbc:hive2://192.168.17.129:10009/default;?spark.eventLog.enabled=true#'
```

### 3. Additional context

For free to take this ticket.

https://github.com/apache/spark/blob/master/sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/ui/HiveThriftServer2HistoryServerPlugin.scala

https://github.com/apache/spark/blob/master/sql/hive-thriftserver/src/main/resources/META-INF/services/org.apache.spark.status.AppHistoryServerPlugin

**Comment by cxzl25** [comment]
Implement KyuubiHistoryServerPlugin   https://github.com/apache/incubator-kyuubi/issues/1816  
You can try this function.

**Comment by yaooqinn** [comment]
@cxzl25 thanks for maintaining the issue list, I think we can close this now
