### ISSUE TITLE
[SUB-TASK][KPIP-2] Introduce EngineType to distinguish multiple engines

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1323]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This is a sub-task of KPIP-2 #KPIP-2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
I can’t wait to see this happen.
