### ISSUE TITLE
[BACKPORT] Backport commits from master that enables kyuubi engine to connect to kerberized zookeeper

### ISSUE THREAD

**Issue by zhouyifan279** [apache/incubator-kyuubi#1361]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

backport these PRs to branch-1.3:
- #933 
- #1176 
- #1204 

### Motivation

Branch-1.3, the current release branch, cannot connect to a kerberized zookeeper.
We think this is a fundamental function and should be back ported to branch-1.3.

### Describe the solution

1. backport #933 to branch-1.3 as it is needed by #1176. Rename HA_ZK_ENGINE_SESSION_ID to  HA_ZK_ENGINE_REF_ID.
2. change HA_ZK_ENGINE_REF_ID available version from 1.4.0 to 1.3.2
3. backport #1176
4. backport #1204 
4. update available version of related configurations to 1.3.2 in master branch

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
#1174 seems to be needed, can you backport it?

**Comment by zhouyifan279** [comment]
> #1174 seems to be needed, can you backport it? cc @zhouyifan279

As #1174 is included in Kyuubi 1.4.0 and 1.4.0 will be released soon (Vote has passed), backport #1174 seems to  be not necessary.

**Comment by wForget** [comment]
> As #1174 is included in Kyuubi 1.4.0 and 1.4.0 will be released soon (Vote has passed), backport #1174 seems to be not necessary.

OK, thank you.
