### ISSUE TITLE
[FEATURE] Leverage Scalafmt to auto format scala code

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1383]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Leverage Scalafmt to auto format scala code.

### Motivation

Currently, the project only uses ·scala-checkstyle· for format check, and the developer should resolve the format issue by themselves.

### Describe the solution

[Scalafmt](https://scalameta.org/scalafmt/) is a popular tool that supports auto format scala code, and it is supported by IDEA and Maven, we can use it to reduce the effort.

### Additional context

The `.scalafmt.conf` is credited by @zhouyifan279, and I did a small tune on it.

```hocon
version = 3.1.1
runner.dialect=scala212
project.git=true

align = none
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens = []
optIn.configStyleArguments = false
danglingParentheses.preset = false
danglingParentheses.defnSite = true
danglingParentheses.callSite = false
docstrings.style = Asterisk
docstrings.wrap = no
maxColumn = 100
newlines.topLevelStatementBlankLines = []
newlines.source = keep
importSelectors = singleLine
indent.extendSite = 2
rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
  ["javax?\\..*"],
  ["scala\\..*"],
  ["(?!org\\.apache\\.kyuubi\\.).*"],
  ["org\\.apache\\.kyuubi\\..*"]
]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
@zhouyifan279 would you like to send a PR to add `.scalafmt.conf`, and reformat all code to match the style?

**Comment by zhouyifan279** [comment]
> @zhouyifan279 would you like to send a PR to add `.scalafmt.conf`, and reformat all code to match the style?

OK
