### ISSUE TITLE
[Umbrella] Add more metrics similar to hive server2

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1393]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

[Cloudera hive server2 metrics](https://docs.cloudera.com/documentation/enterprise/latest/topics/cm_metrics_hiveserver2.html).

It should be helpful if we can add more metrics based on `kyuubi-metrics` module:
- avg rpc time for each operation on Kyuubi server
- current connection and opreation number
- etc ...

### Task list

TODO

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhenjiaguo** [comment]
LGTM. This is very helpful for us comprehensive evaluation of kyuubi.

**Comment by yaooqinn** [comment]
@zhenjiaguo would you like to take some of the subtask or maybe start with which ones we can add

**Comment by zhenjiaguo** [comment]
Yes, I'm very happy to take some subtask. Just assign the task to me if I can help.

**Comment by ulysses-you** [comment]
thank you @zhenjiaguo ! also cc @zhouyifan279
