### ISSUE TITLE
[FEATURE] Migrate Spark security module from submarine to kyuubi

### ISSUE THREAD

**Issue by anumee** [apache/incubator-kyuubi#1451]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Spark security module was retired from [submarine pull- 796](https://github.com/apache/submarine/pull/796)
and it is still missing here. This is needed with Spark 3.2 support.

### Motivation

Spark 3.2 support

### Describe the solution

1. Migrate Submarine security module here -  https://github.com/apache/submarine/pull/796 and,
2. Update Spark version to 3.2
 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lordk911** [comment]
Wonder to know when will this Spark security module to support Spark 3.2

**Comment by pan3793** [comment]
This task is of medium priority and we don't have ETA now, volunteers are welcome :)

**Comment by RamakrishnaChilaka** [comment]
@pan3793 ,can you please check this PR ? https://github.com/apache/submarine/pull/861

**Comment by pan3793** [comment]
Thanks @RamakrishnaChilaka for working on this feature, but ranger spark module is deprecated since  https://github.com/apache/submarine/pull/796, the test infrastructure become not runable in apache/submarine, would you please port this module to kyuubi firstly?

**Comment by RamakrishnaChilaka** [comment]
sure @pan3793 ,  Kindly, Please check whether the current code is valid for spark 3.2 ?

**Comment by pan3793** [comment]
> Please check whether the current code is valid for Spark 3.2?

We need CI to verify that.

**Comment by RamakrishnaChilaka** [comment]
Ok @pan3793, I am not aware of kyuubi code base.. can you please guide me in porting submarine spark security module into kyuubi ? I tried searching for spark security files in the codebase..

**Comment by izhangzhihao** [comment]
Code gets dropped in commit https://github.com/apache/submarine/commit/50ae48339df4a11d115ac4b76b363da9796a3260
previews commit: https://github.com/apache/submarine/commit/40904405f03f944d7a83da9d059ee1770e0085bf

**Comment by izhangzhihao** [comment]
You can find code [here](https://github.com/apache/submarine/tree/40904405f03f944d7a83da9d059ee1770e0085bf/submarine-security/spark-security)

**Comment by minyk** [comment]
@RamakrishnaChilaka I've done almost same thing for our product. I don't have the right to open the code, but this is commit list I made:
* parseRawDataType() removed by [SPARK-33641]
* child renamed to plan by [SPARK-34701]
* AlterTableRecoverPartitionsCommand renamed to RepairTableCommand by [SPARK-34518]
* CacheTableCommand renamed to CacheTalbe by [SPARK-33654]
* Change RunnableCommand to LeafRunnableCommand by [SPARK-34989]
* implements a withNewChildInteral method created by [SPARK-34989]

**Comment by pan3793** [comment]
cc @yaooqinn

**Comment by RamakrishnaChilaka** [comment]
thanks @minyk , your list was truly helpful, I didn't knew about `SPARK-34989`, I have incorporated it, one small change to your list is `UnCacheTableCommand` is renamed to `UnCacheTable`.

**Comment by RamakrishnaChilaka** [comment]
> here

Please note that, I have taken the code from submarine project.. But I couldn't find the code of spark-security inside Kyuubi.

**Comment by yaooqinn** [comment]
The spark security module currently contains 4 main features, including authorization, data masking, row-level filtering, and DCL(incomplete).

It contains a lot of legacy code for very old spark releases including spark 2.0, so I suggest we add them step by step starting with authorization.

FYI, https://issues.apache.org/jira/browse/SUBMARINE-409

**Comment by RamakrishnaChilaka** [comment]
Sure @yaooqinn. We will get started on this, as i am new to kyuubi, kindly, please guide me.. Thanks

**Comment by lordk911** [comment]
@yaooqinn will [[WIP] [KYUUBI #1451] Introduce Kyuubi Spark Authz Module #2160](https://github.com/apache/incubator-kyuubi/pull/2160) support ranger1.2 ?

**Comment by yaooqinn** [comment]
> @yaooqinn will [[WIP] [KYUUBI #1451] Introduce Kyuubi Spark Authz Module #2160](https://github.com/apache/incubator-kyuubi/pull/2160) support ranger1.2 ?

I don't know
