### ISSUE TITLE
[Bug] the new code style has issue when import `org.apache.kyuubi`

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1452]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

see the snapshot:
![image](https://user-images.githubusercontent.com/12025282/143377853-e14d57d8-d20b-4fc4-847a-ee9039fa15d7.png)

more detail see comment https://github.com/apache/incubator-kyuubi/pull/1378/files#r756092002

### Affects Version(s)

1.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
I think @zhouyifan279 has some investigation, scalafmt use regex to match the PREFIX, not the whole import statememt, there is no easy way to solve it. One workaround is using `import org.apache.kyuubi._` to import all things instead of `import org.apache.kyuubi`.

**Comment by ulysses-you** [comment]
is it possible we can make `import org.apache.kyuubi` to `import org.apache.kyuubi._` automatically  using script ?

**Comment by pan3793** [comment]
It should be rare to use `import org.apache.kyuubi` in our codebase, do you find it in other place?

**Comment by ulysses-you** [comment]
have not seen other similar issue
