### ISSUE TITLE
[Umbrella] [KPIP-3] Support Trino(Presto SQL) Engine

### ISSUE THREAD

**Issue by hddong** [apache/incubator-kyuubi#1456]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

[[KPIP-3] Support Trino(Presto SQL) Engine Design](https://github.com/apache/incubator-kyuubi/discussions/1455)

![image](https://user-images.githubusercontent.com/17537134/143553888-adbb6132-d06c-43d1-aaf8-62f25686a56d.png)
![image](https://user-images.githubusercontent.com/17537134/143554002-59dbe27b-bbc5-4fa1-a2a2-6a263efa5c5b.png)

### Task list
- #1510 @hddong 
- #1511 @hddong 
- #1515 @hddong 
- #1565 @hddong 
- #1581 @hddong 
- #1582 @hddong 
- #1641 @hddong 
- #1764 @hddong 
- #1885  @hddong 
- #1886 @hddong 
- #1887  @hddong 
- #1903  @SteNicholas 
- #1906 @SteNicholas 
- #1911 @SteNicholas 
- #1923 @SteNicholas 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@hddong, could you please help to add #1903, #1906, #1911, #1923 issues to the task list?

**Comment by yaooqinn** [comment]
@hddong @SteNicholas thanks for the great work, please also help build user-friendly docs for end-users in the future.
