### ISSUE TITLE
[Bug] Delta lake table columns won't show up in DBeaver

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-kyuubi#1458]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Please, see the details in the below discussion
````
https://github.com/apache/incubator-kyuubi/discussions/1189
````

### Affects Version(s)

1.3.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
@mmuru thanks for reporting this

**Comment by nousot-cloud-guy** [comment]
@mmuru @yaooqinn This doesn't appear to be working for me. I had to make [this](https://github.com/nousot/kyuubi/commit/f7e4675a77a0d220e4b73dd5e54e4dba751c781e) change in order for table schemas to correctly show up in DBeaver. Without it, I get a "table not found" error when listing columns. Do I have a misconfiguration somewhere or is this a bug?

**Comment by mmuru** [comment]
It works only for "default" schema. For a custom schema, your fix should
work. I've made a fix but did not raise PR.
