### ISSUE TITLE
[FEATURE] Add session conf provider

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1536]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add session conf provider to decouple the engine builder and session conf.

Introduce a new method in `SessionConfAdvisor`

```java
/** The returned conf will overwrite the session conf */
default Map<String, String> getConfOverlay(String user, Map<String, String> sessionConf) {
  return new HashMap<>();
}
```

So we can build the different conf by session.

### Motivation

We can get the session config from remote service.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaroslavambrozyak** [comment]
Hi guys, this is so useful feature and I'd like to use it on our Kyuubi server. I am just curious do you know approximately when the PR will be merged? Thanks

**Comment by yaooqinn** [comment]
sure. And you can help review the PR. I think it can be ready in v1.5.0
