### ISSUE TITLE
[FEATURE] Support multiple engine pools under one sharing level.

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#1554]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support configuring subdomain and engine pool together.

### Motivation

I want to be able to configure subdomain and engine pool together, and create multiple engine pools under one sharing level.

### Describe the solution

Configure subdomain and engine pool together. 
```
kyuubi.engine.share.level.subdomain=test001;
kyuubi.engine.pool.size=3
```
The engine namespace will look like:
![test11](https://user-images.githubusercontent.com/17894939/145993235-bc27fd58-e10a-4c71-a0ea-b07741273742.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Any reason not to use another account?

**Comment by pan3793** [comment]
I think we need more discussion before changing the subdomain behavior, would you please share your use case?

**Comment by wForget** [comment]
> I think we need more discussion before changing the subdomain behavior, would you please share your use case?

There is no good use case yet. I think it would be more flexible to configure these two parameters together, so that we can configure different engine pools for a user in different upper-layer services.

**Comment by pan3793** [comment]
Currently, we hardcode the pool name as `engine-pool`, WDYT introduce a new conf `engine.pool.name`, and set the default value to `engine-pool`?

**Comment by pan3793** [comment]
cc @timothy1024 as he is the author of this feature

**Comment by wForget** [comment]
> Currently, we hardcode the pool name as `engine-pool`, WDYT introduce a new conf `engine.pool.name`, and set the default value to `engine-pool`?

Yes, they are the same effect.

**Comment by wForget** [comment]
> the engine pool name sounds good to me

Thanks, i will do that.

**Comment by wForget** [comment]
The effect of using`kyuubi.engine.pool.name`  configuration.
configurations:
```
// test001 engine pool
kyuubi.engine.pool.name=test001
kyuubi.engine.pool.size=3

// test002 engine pool
kyuubi.engine.pool.name=test002
kyuubi.engine.pool.size=3
```
screenshots:
![image](https://user-images.githubusercontent.com/17894939/146304604-e2218394-3a39-4255-b325-294163418d27.png)
