### ISSUE TITLE
[Bug] Server connectionUrl shall respect user's setting first

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1564]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Currently, we force it to hostname, this is not right.

### Affects Version(s)

1.4.0,1.3.1,1.2.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @JeremyTon

**Comment by JeremyTon** [comment]
I'm working on this

**Comment by yaooqinn** [comment]
thank you @JeremyTon

**Comment by JeremyTon** [comment]
I have been pull request on #1604 
please check it ,thank you @yaooqinn
