### ISSUE TITLE
[FEATURE] Add time metric on each KyuubiBackendService method

### ISSUE THREAD

**Issue by zhenjiaguo** [apache/incubator-kyuubi#1586]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add time metric on each `KyuubiBackendService` method, like `opensession`, `executeStatement`, `fetchResults` etc...

### Motivation

Relate to #1393 
Add time metric on each `KyuubiBackendService` method can help us inspect Kyuubi Server running status inside. It can Indirect reflecting our RPC call time when using Kyuubi.

### Describe the solution

Use `Histogram` metrics to record every call time on every method in `KyuubiBackendService`.

### Additional context

Every Kyuubi frontend service will call `KyuubiBackendService` method. So it suitable to all user that use different frontend service.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by zhenjiaguo** [comment]
cc @yaooqinn  @ulysses-you

**Comment by yaooqinn** [comment]
sgtm
