### ISSUE TITLE
[Bug] Improve kyuubi-ctl output format

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1595]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

There is no spaces between column values when column_width > min_column_width
```
hadoop@kyuubi:~$ bin/kyuubi-ctl list server
/kyuubinamespacekyuubi01.corp  10010   1.4.0-incubating
/kyuubinamespacekyuubi02.corp  10010   1.3.1-incubating
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xifeng** [comment]
@pan3793 
maybe should set parameter -b, --verbose to default true ?

```
./bin/kyuubi-ctl list server -zk 172.16.20.228:9218 -b 

             Zookeeper service nodes            
+----------+-------------+----------+--------------+
|Namespace |    Host     |   Port   |   Version    |
+----------+-------------+----------+--------------+
| /kyuubi  |172.16.20.228|  10001   |1.5.0-SNAPSHOT|
+----------+-------------+----------+--------------+
```

**Comment by pan3793** [comment]
> maybe should set parameter -b, --verbose to default true ?

verbose also affects other things, but for render service nodes, I think we can always let it render in verbose mode, i mean, we can remove the arg `verbose` of `Tabulator.format`. cc @turboFei
