### ISSUE TITLE
[FEATURE] rename zookeeper.embedded.client.port.address to zookeeper.embedded.client.host

### ISSUE THREAD

**Issue by zwangsheng** [apache/incubator-kyuubi#1599]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

EmbeddedZookeeper using `zookeeper.embedded.client.port.address` to get user set local zk hostname.
But `zookeeper.embedded.client.port.address` has words with extra interference, like port, address.
We can see in logic like:
```
    val hostname = conf.get(ZK_CLIENT_PORT_ADDRESS).map(InetAddress.getByName)
      .getOrElse(findLocalInetAddress).getCanonicalHostName
```
The port setting doesn't do anything.

### Motivation

Rename `zookeeper.embedded.client.port.address` to `zookeeper.embedded.client.host`

### Describe the solution

Rename config and fix doc.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
client.port.address means rpc end point for zkclients not for server peers, I guess

**Comment by zwangsheng** [comment]
> client.port.address means rpc end point for zkclients not for server peers, I guess

In the code, however, this configuration `zookeeper.embedded.client.port.address`  is not found anywhere except to start EmbeddedZookeeper.

**Comment by zwangsheng** [comment]
It seems like zookeeper name style, so close this issue.
