### ISSUE TITLE
[Bug] Rest frontend service jetty server has started at null.

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1610]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

we shall print the actual bind-address 

### Affects Version(s)

master

### Kyuubi Server Log Output

```logtalk
Started ServerConnector@31b33e91{HTTP/1.1, (http/1.1)}{10.242.189.214:10099}
2021-12-23 11:59:56.620 INFO server.Server: jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 1.8.0_251-b08
2021-12-23 11:59:57.393 INFO handler.ContextHandler: Started o.e.j.s.ServletContextHandler@3bd3d05e{/,null,AVAILABLE}
2021-12-23 11:59:57.393 INFO server.Server: Started @3342ms
2021-12-23 11:59:57.393 INFO server.KyuubiRestFrontendService: Rest frontend service jetty server has started at null.
```

### Kyuubi Server Configurations

```yaml
kyuubi.frontend.protocols=THRIFT_BINARY,REST
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xifeng** [comment]
**rc:**

org.apache.kyuubi.server.KyuubiRestFrontendService#start

should add connector to jettyServer before jettyServer start

`jettyServer.addConnector(connector)`

**Comment by yaooqinn** [comment]
@xifeng， would you like to submit a PR?

**Comment by rvacaru** [comment]
I can give it a try at fixing it otherwise :)

**Comment by yaooqinn** [comment]
> I can give it a try at fixing it otherwise :)

assigned， thanks

**Comment by yaooqinn** [comment]
Hi, @rvacaru any update on this?

**Comment by rvacaru** [comment]
I fixed the issue like suggested, now I'm trying to mvn install the root project but I'm getting an error:
`java.lang.NoClassDefFoundError: Could not initialize class org.apache.kyuubi.service.authentication.PlainSASLServer$`

if I do an mvn compile it can't resolve the imports below:
```
import org.apache.kyuubi.jdbc.hive.logs.InPlaceUpdateStream;
import org.apache.kyuubi.shade.org.apache.hadoop.hive.common.log.InPlaceUpdate;
```
I'd like to run the kyuubi server to test the fix by looking at the logs again.

**Comment by yaooqinn** [comment]
try mvn with install?

**Comment by rvacaru** [comment]
I managed to build the whole repo by skipping tests in mvn install. Tho if I run the kyuubi server unit tests in intellij Idea I get:
```
not found: type KyuubiHiveDriver
    val driver = new KyuubiHiveDriver()
``` 
Same if I try running the `KyuubiServer`

**Comment by pan3793** [comment]
Please try `build/mvn clean install -DskipTests` before run ut in IDEA

**Comment by pan3793** [comment]
It's an old issue [IDEA-126596](https://youtrack.jetbrains.com/issue/IDEA-126596) which exists for nearly a decade
