### ISSUE TITLE
[Bug] Avoid hardcoded version in OpenAPIDefinition

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1614]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```scala
@OpenAPIDefinition(
  info = new Info(
    title = "Apache Kyuubi REST API Documentation",
    version = "1.4.0",
    description = "Apache Kyuubi REST API Documentation",
    contact = new Contact(
      name = "Apache Kyuubi Community",
      url = "https://kyuubi.apache.org/issue_tracking.html",
      email = "dev@kyuubi.apache.org"),
    license = new License(
      name = "Apache 2.0",
      url = "https://www.apache.org/licenses/LICENSE-2.0.html")),
  tags = Array(new Tag(name = "Session")))
```

the version shouldn't be 1.4.0 but org.apache.kyuubi.KYUUBI_VERSION

### Affects Version(s)

1.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cfmcgrady** [comment]
Scala annotation argument needs to be constant, we cant pass `org.apache.kyuubi.KYUUBI_VERSION` as the annotation input argument.

**Comment by yaooqinn** [comment]
sounds reasonable to me？ any suggestions？
