### ISSUE TITLE
[FEATURE] Add `restart` option for `bin/kyuubi`

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1660]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

if the server is running, perform stop and start, otherwise, start

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Narcasserun** [comment]
I'd love to take this one if it is good w/ you.

**Comment by yaooqinn** [comment]
@Narcasserun, thanks very much, I have assign this ticket to you.
