### ISSUE TITLE
[Bug] The value of hasResultSet is always set to true in Kyuubi Server

### ISSUE THREAD

**Issue by iodone** [apache/incubator-kyuubi#1678]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/incubator-kyuubi/blob/47533100f6f69b02a90985637a8fcc3f2cebb28c/kyuubi-server/src/main/scala/org/apache/kyuubi/operation/ExecuteStatement.scala#L56-L73

`hasResultSet` is set to true by default in the `beforeRun` method. `hasResultSet` value can be obtained from `remoteOpHandle`, whether to consider setting the value in the `executeStatement` ？

Like this: 
```
 private def executeStatement(): Unit = {
    try {
      // We need to avoid executing query in sync mode, because there is no heartbeat mechanism
      // in thrift protocol, in sync mode, we cannot distinguish between long-run query and
      // engine crash without response before socket read timeout.
      _remoteOpHandle = client.executeStatement(statement, true, queryTimeout)
      setHasResultSet(_remoteOpHandle.isHasResultSet) 
    } catch onError()
  }
```

### Affects Version(s)

master/1.4.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
what‘s the issue you met actually？

**Comment by iodone** [comment]
There is no problem in the Kyubi Engine scenario, only an exception in the proxy HiveServer, and some other services in the proxy that are not under our control may have no resultSet

**Comment by yaooqinn** [comment]
>       setHasResultSet(_remoteOpHandle.isHasResultSet) 

what if `_remoteOpHandle.isHasResultSet` changes

**Comment by iodone** [comment]
As I understand it, the remote service responds to the client's current operation via Thrift Reps `isHasResultSet` whether there are results returned. if there is no resultSet, the client mistakenly believes that it can currently go to fetch the results, which will lead to an exception when calling `client.getResultSetMetadata(_remoteOpHandle)`. 
![image](https://user-images.githubusercontent.com/5451385/148057734-894bf0ed-e4fe-45be-9880-e30b05d8f1b8.png)


`setHasResultSet(_remoteOpHandle.isHasResultSet)` to tell the client that there are no results returned by the server and that it does not need to continue fetch the results.

**Comment by yaooqinn** [comment]
Sounds reasonable
