### ISSUE TITLE
[Bug] Remove invalid column and field number check

### ISSUE THREAD

**Issue by link3280** [apache/incubator-kyuubi#1679]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

ResultSet checks if the column number of data matches the one in metadata by calling `iterator.next()` to get a sample row, which would make the first row missing in the final result.

The bug didn't appear in the tests, because the condition is wrong. Now it checks the column number only if data is empty, which should be another bug.

### Affects Version(s)

1.5.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
👍
