### ISSUE TITLE
[SUB-TASK][KPIP-2] Extend Flink ExecuteStatement to support more operations

### ISSUE THREAD

**Issue by link3280** [apache/incubator-kyuubi#1681]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

`ExecuteStatement` of Flink engine now supports QueryOperation only. We can extend it to support more operations that Flink Executor already supports. e.g. `ShowTableOperation`,`CreateTableOperation`, `ExplainOperation`.

### Motivation

This is a sub-task of KPIP-2 #1322 .

### Describe the solution

Add a case matching before executing operations. Execute QueryOperation (which returns ResultDescriptor) via `executor.executeQuery`, while execute other operations (which returns TableResult) via `executor.executeOperation`. 

There're several operations that `executor.executeOperation` doesn't support, such as `SetOperation`. We may address that afterward.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yanghua** [comment]
@link3280 Thanks for opening this issue, it would be better to follow this issue prefix: `[SUB-TASK][KPIP-2]` for archiving the Flink SQL engine.

**Comment by link3280** [comment]
> @link3280 Thanks for opening this issue, it would be better to follow this issue prefix: `[SUB-TASK][KPIP-2]` for archiving the Flink SQL engine.

OK, I'll follow the pattern. Thanks for the reminder.
