### ISSUE TITLE
[Bug] Fix trino client flaky test

### ISSUE THREAD

**Issue by hddong** [apache/incubator-kyuubi#1744]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```scala
TrinoStatementSuite:
- test query *** FAILED ***
  resultSet.toIterator.hasNext was false (TrinoStatementSuite.scala:32)
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Fixed in #1745
