### ISSUE TITLE
[SUB-TASK][KPIP-2] Support Flink Set/Reset operation

### ISSUE THREAD

**Issue by link3280** [apache/incubator-kyuubi#1778]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Set/Reset operations are crucial for tunning Flink SQL jobs and enabling/disabling features, but they're not executed as SQL statements in Flink, thus can't be supported by the current `ExecuteStatement` implementation. We should extend `ExecuteStatement` to support these operations.

### Motivation

This is a sub-task of KPIP-2 #1322.

### Describe the solution

Add matching cases for SetOperation and ResetOperation, and execute them via other table APIs.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by link3280** [comment]
cc @yanghua

**Comment by yanghua** [comment]
> cc @yanghua

+1
