### ISSUE TITLE
[SUB-TASK][KPIP-2] Make flink engine local quickstart demo hadoop lib free

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1814]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This is a subtask of KPIP-2 #1322 .

### Motivation

Currently, the Flink engine can not start without Hadoop classpath. We should fix it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yanghua, IMO, the Flink engine could start without hadoop classpath because the value of `FLINK_HADOOP_CLASSPATH` could be empty string in `flink-sql-engine.sh`.

**Comment by SteNicholas** [comment]
@yanghua @yaooqinn, could you please assign this ticket to me? I have pushed a pull request for this issue.

**Comment by SteNicholas** [comment]
@yanghua, as #1973 comment mentions, the Kyuubi module dependencies of the Flink engine need the hadoop client jars in the classpath. Therefore, the Flink engine couldn't be maken hadoop library free and this issue could be closed.

**Comment by yaooqinn** [comment]
thanks
