### ISSUE TITLE
[SUB-TASK][KPIP-2] Support closing Flink SQL engine process

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1819]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This is a subtask of KPIP-2 #1322 

### Motivation

Currently, we did not consider closing flink SQL engine process. We should support it ASAP.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yanghua, @pan3793, could you please assign this to me?

**Comment by SteNicholas** [comment]
@yanghua, please help to close the issue with #2054 .
