### ISSUE TITLE
Bump Prometheus 0.14.1

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1850]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Release notes: https://github.com/prometheus/client_java/releases

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@pan3793, could you please assign this ticket to me?
