### ISSUE TITLE
[SUB-TASK][KPIP-2] Document Flink SQL engine user guide

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1866]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This is a subtask of KPIP-2 #1322.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yanghua, could you please assign this ticket to me?

**Comment by yaooqinn** [comment]
Hi branch 1.5's been cut. Any update on this? I think we need at least a quick start at the doc side for flink engine.

**Comment by SteNicholas** [comment]
@yaooqinn, this ticket could assign to @deadwind4. I will work for reviewing the document.
