### ISSUE TITLE
[SUB-TASK][KPIP-2] Support `PlanOnlyStatement` operation like Spark SQL engine

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1867]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

This is a subtask of KPIP-2 #1322.

Currently, Spark SQL engine supports the `PlanOnlyStatement` operation, which is used to describe the SQL execution plan(logical and physical). Flink also supports [Explain](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/dev/table/sql/explain/) statement to do the same thing. IMO, it would be better to support it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yanghua, could you please assign this ticket to me? I'm working for this issue.
