### ISSUE TITLE
[Improvement] Make ProcBuilder decouple with YARN

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1872]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, `ProcBuilder#killApplication`'s implementation suppose that all the engine process would be started via submitting an application to YARN. But this suppose may be not right, e.g. Flink SQL Engine.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
+1
