### ISSUE TITLE
[SUB-TASK][KPIP-2] Support row limit on result set

### ISSUE THREAD

**Issue by link3280** [apache/incubator-kyuubi#1883]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, Flink engine would pull all result rows into memory before returning it to the client. This would be problematic for large result sets and infinite result sets.

This is a sub-task of KPIP-2 https://github.com/apache/incubator-kyuubi/issues/1322.

### How should we improve?

We could support setting max buffered rows for result sets, and stop pulling more rows when the threshold is reached. Moreover, if it's an infinite streaming query, we should cancel the query after that.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by link3280** [comment]
cc @yanghua

**Comment by yanghua** [comment]
ack
