### ISSUE TITLE
[Improvement] Rename some package named with ‘logs’

### ISSUE THREAD

**Issue by yulongz** [apache/incubator-kyuubi#1917]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Usually ，the directory name ‘logs’  is included in the file ‘.gitignore’ .  Kyuubi contians some package names with logs , for example , ’org.apache.kyuubi.jdbc.hive.logs‘ and ‘org.apache.hive.beeline.logs’ . Some git operations will lose processing of files in this package.
  

### How should we improve?

Rename package name with 'logs'  will avoid some misoperations and offer some convenience. For example , maybe we can rename 'logs' to 'logutils'.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yulongz, IMO, you could update the `.gitnore` for above, not rename the package. cc @yaooqinn

**Comment by yulongz** [comment]
@SteNicholas  Whether the file ‘https://github.com/apache/incubator-kyuubi/blob/master/.gitignore’ should contain the line 'logs/'?

**Comment by SteNicholas** [comment]
@yulongz, you could add the path to the `.gitignore`.

**Comment by SteNicholas** [comment]
@yaooqinn, this issue has no response. IMO. this could be closed.

**Comment by yaooqinn** [comment]
+1 to close this，free free to open it if youthink this is still an issue that needs to be fixed
