### ISSUE TITLE
[SUB-TASK][KPIP-2] Add more enum values for `OperationModes` 

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1919]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Add more enum values for `OperationModes` to map flink SQL engine's capacity.
This is a subtask of KPIP-2 #1322 

### Motivation

Currently, `OperationModes` only supports four enum values. While Flink can provide more detailed execution information for a SQL statement. So, we need to extend it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yanghua, could you please assign this ticket to me?

**Comment by yanghua** [comment]
> @yanghua, could you please assign this ticket to me?

ack
