### ISSUE TITLE
[FEATURE] Skipping use/cacheTable/createView command in PlanOnlyStatement like Set and ReSet Command

### ISSUE THREAD

**Issue by iodone** [apache/incubator-kyuubi#1920]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

When using planOnly mode to parse some SQL statements in kyuubi, there are usually multiple SQL statements containing `USE Database` that are context sensitive. If the `USE` statement is also just plan parsed and not really executed, the next SQL references a table name under the current database, it will throw a Table Not Found Exception when analyzing and optimizing the plan. And `create temporary view` and `cache table` have the same problem.

We can skip the Plan parsing of `UseStatement` | `CacheTableCommand` | `CreateViewStatement`and actually execute it like `SetCommand`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
Does `create temporary view` also have the same problem?

**Comment by SteNicholas** [comment]
@iodone, the title of the issue has the typo: Commond -> Command.

**Comment by iodone** [comment]
> wForget

It should have the same problem, including `cache table` statement is the same, I'm not sure if I need to fix these two. In the real application scenario, `UseStatement` is the most common.

**Comment by SteNicholas** [comment]
@iodone, IMO, the `create temporary view` and `cache table` statement could also be fixed in this issue. You could update the title and description of the issue for fix these statements. 
cc @wForget

**Comment by yaooqinn** [comment]
we can create a new issue and make it more generic after this one.

i.e, we can add a conf named `kyuubi.operation.plan.only.skip` for skipping `set/reset/use` and other custom commands/plans
