### ISSUE TITLE
[Bug] Engine token expired issue after idle for long time

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#1936]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

We have enabled the `HadoopCredentialsManager` to refresh delegation token, but met token expired issue when the backend engine is idle for long time.

I think that we can refresh the token when establishing a connection to prevent this issue.
```
22/02/18 00:58:44 INFO ExecuteStatement: 
           Spark application name: kyuubi_apollorno_USER_SPARK_SQL_b_stf_default_06dc1722-f0ff-4535-bea1-d2abe5d3ebf2
                 application ID: application_1635906065713_7300973
                 application web UI: https://apollo-rno-rm-1.vip.hadoop.ebay.com:50030/proxy/application_1635906065713_7300973,https://apollo-rno-rm-2.vip.hadoop.ebay.com:50030/proxy/application_1635906065713_7300973
                 master: yarn
                 deploy mode: cluster
                 version: 3.1.1.0.6.0
           Start time: 2022-02-15T05:07:49.417
           User: b_stf
22/02/18 00:58:45 WARN Client: Exception encountered while connecting to the server : org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.token.SecretManager$InvalidToken): token (HDFS_DELEGATION_TOKEN token 22821449 for b_stf) can't be found in cache
22/02/18 00:58:45 INFO DAGScheduler: Asked to cancel job group 292fd765-4f99-44f8-afb3-a35fcc96e1a6
22/02/18 00:58:45 INFO ExecuteStatement: Processing b_stf's query[292fd765-4f99-44f8-afb3-a35fcc96e1a6]: RUNNING_STATE -> ERROR_STATE, statement: select count(*) from ddm_notiplat_t.nss_event_queue where src_cre_dt>='2022-02-16 00:00:00', time taken: 1.108 seconds
22/02/18 00:58:45 ERROR ExecuteStatement: Error operating EXECUTE_STATEMENT: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.token.SecretManager$InvalidToken): token (HDFS_DELEGATION_TOKEN token 22821449 for b_stf) can't be found in cache
	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1586)
	at org.apache.hadoop.ipc.Client.call(Client.java:1530)
	at org.apache.hadoop.ipc.Client.call(Client.java:1430)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:255)
	at com.sun.proxy.$Proxy16.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:881)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Affects Version(s)

1.4.0-incubating

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
@lightning-L could you help on this issue?

**Comment by turboFei** [comment]
FYI:
here is the ticket for `Implement delegation token renewal framework`

**Comment by zhouyifan279** [comment]
We can send credentials  in `LaunchEngine` operation when it succeeds.

Another case should be taken into consideration:
1. kyuubi engine being idle and credentials have been expired.
2. User created a KyuubiSession to this engine on kyuubi-server-1.
3. Due to some reason (server restarted or server never talked to this engine),  kyuubi-server-1 has no cached credentials for this engine.
4. Invoking `HadoopCredentialsManager#sendCredentialsIfNeeded` triggered a task to renew credentials but engine did not receive new credentials.
5. Following SQL operation still fails due to expired credentials.

**Comment by turboFei** [comment]
> Invoking HadoopCredentialsManager#sendCredentialsIfNeeded triggers a task to renew credentials and returns. New credentials will not be sent to engine until renewal task succeeds.
> Following SQL operation still fails due to expired credentials.

Seems that we need wait the renewal task completion before executing query.
