### ISSUE TITLE
[Improvement] Upgrade thrift version to 0.16.0

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1948]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Due to spark side will upgrade thrift version to 0.16, see https://github.com/apache/spark/commit/4789e1f234a92b3c17d1f962c8f374ef9478612a which contains breaking API and it will be backported to 3.1 and 3.2.

So we need to sync with spark and shade the thrift libs for engines

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yaooqinn, could you please assign this ticket to me?
