### ISSUE TITLE
[Bug] 当并发创建会话时，EngineRef判断当前引擎数量为空时，会不会导致并发创建引擎？

### ISSUE THREAD

**Issue by shenbinglife** [apache/incubator-kyuubi#1951]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

当并发创建会话时，EngineRef判断当前引擎数量为空时，会不会导致并发创建引擎？

 getServerHost(zkClient, engineSpace).getOrElse {
        create(zkClient, extraEngineLog)
      }

这段代码在并发上是不是有问题？ 

### Affects Version(s)

1.5.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhouyifan279** [comment]
不会。`org.apache.kyuubi.engine.EngineRef#create`中会获取分布式锁。
