### ISSUE TITLE
[Improvement] Skip creating sparksession and starting engine if the max initialization time exceeds

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1960]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When a resource manager such as YARN is in high traffic, many engines will be pending and fail to get initialized in time. But sometimes, the pending engine is still waiting for YARN to accept it or run it. In the meanwhile, it already becomes orphaned and may get a re-submit at the server-side. This may become an endless loop.

We should avoid these kinds of engines be running.

### How should we improve?

One way to fix this is to add a timestamp that indicates the submit time of an engine at the serverside, then before we actually create the SparkSession instance, we check whether the `current time - submit time` already exceeds the maximum engine initialization time. If true, we skip; otherwise, we go the current way

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @wForget @turboFei

**Comment by wForget** [comment]
Sounds good, in this way, the orphaned engine will exit immediately without waiting for idle timeout.

**Comment by wForget** [comment]
@yaooqinn Could you please assign this to me? I want to try.

**Comment by yaooqinn** [comment]
Assigned.
