### ISSUE TITLE
[Improvement] Upgrade hive-service-rpc to 3.1.2

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1961]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

 Upgrade hive-service-rpc(2.3.9) to 3.1.2

### How should we improve?

1. We update the hive-service-rpc to 3.1.2
2. we leave the new APIs as unsupportted
3. we discuss how the support these new APIs properly

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yaooqinn, could you please assign this ticket to me?

**Comment by yaooqinn** [comment]
any updates on this @SteNicholas

**Comment by SteNicholas** [comment]
@yaooqinn, I have updated many copied class in kyuubi-hive-jdbc module and will have to compile and test the upgrade changes.
