### ISSUE TITLE
[Improvement] Make sparkSession or SparkContext as a scala.concurrent.Future to give it proper timeout

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1962]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/incubator-kyuubi/issues/1960 will fix a certain problem with master deploy mode, for client mode, the timeout describe there will almost not happen. The sc might get stuck will the driver is on and wait for the ApplicaitonMaster to be allocated. Although spark will have a timeout for checking for driver-am connected. But this may not happen when the AM is not able to be allocated in time.

### How should we improve?

We need a timeout for this whole progress.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @wForget @turboFei

**Comment by wForget** [comment]
+1, @yaooqinn Could you please assign this to me? I will implement this.

**Comment by wForget** [comment]
@yaooqinn @ulysses-you I found that this seems unnecessary, because the submit process will be killed when starting the Engine timeout, and the driver will also stop in client mode.
