### ISSUE TITLE
[Improvement] Make plan only mode skippable for configuable plans

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1963]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the plan only mode skip for certern plans, like use/set/reset, etc, we can add a conf to make it configurable

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yaooqinn, could you please assign this ticket to me?
