### ISSUE TITLE
Flaky test: SchedulerPoolSuite: Scheduler pool

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1972]
```
- Scheduler pool *** FAILED ***
  The code passed to eventually never returned normally. Attempted 558 times over 10.005535925 seconds. Last failure message: 1003 was not less than 1000. (SchedulerPoolSuite.scala:99)

```
cc @ulysses-you

**Comment by wForget** [comment]
Can we fix it by increasing the timeout?

**Comment by ulysses-you** [comment]
@wForget I think we can do this

**Comment by yaooqinn** [comment]
- Scheduler pool *** FAILED ***
  The code passed to eventually never returned normally. Attempted 1208 times over 20.014311831 seconds. Last failure message: 1558 was not less than 1000. (SchedulerPoolSuite.scala:99)

Still seeing it
