### ISSUE TITLE
[FEATURE] Kyuubi Restful API Kerberos authentication support

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#1978]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support the kerberos authentication for restful front end server.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
@turboFei 👍
