### ISSUE TITLE
[Bug] The documentation `Building Kyuubi` needs to be updated

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1985]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Most of the examples are broken due to changes we have made so far.

### Affects Version(s)

1.4.2, master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yangrong688** [comment]
Hi @yaooqinn  , could you please assign this ticket to me？

**Comment by yaooqinn** [comment]
thanks @yangrong688
