### ISSUE TITLE
[FEATURE] Support preserve user context in group share level

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#1987]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

In group share level, the use case can be:
- all user share the same session
- every session are independent
- every user share their own session

We have supported the first two use case by change config `kyuubi.engine.single.spark.session`. It would be good to support the third.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
+1
