### ISSUE TITLE
[Bug] Official documentation error

### ISSUE THREAD

**Issue by HYBG-1126** [apache/incubator-kyuubi#1997]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

**url**:https://kyuubi.readthedocs.io/en/v1.4.0-incubating/quick_start/quick_start_with_helm.html#running-kyuubi-with-helm

Getting Started With Kyuubi on kubernetes 
2.1.2. Get Kyuubi Started
[Optional] Create namespace on kubernetes

**cretate ns kyuubi **

the"**cretate ns kyuubi**" should be "**create ns kyuubi**" 

### Affects Version(s)

after version 1.4

### Kyuubi Server Log Output

```logtalk
kubectl cretate ns kyuubi
Error: unknown command "cretate" for "kubectl"

Did you mean this?
	create

Run 'kubectl --help' for usage.
```

### Kyuubi Engine Log Output

```logtalk
no this
```

### Kyuubi Server Configurations

```yaml
no this
```

### Kyuubi Engine Configurations

```yaml
no this
```

### Additional context

kubectl cretate ns kyuubi :

Error: unknown command "cretate" for "kubectl"

Did you mean this?
	create

Run 'kubectl --help' for usage.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
#1999
