### ISSUE TITLE
[Improvement] Bump Hadoop 3.3.2

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2000]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Hadoop 3.3.2 is out.
https://www.mail-archive.com/common-dev@hadoop.apache.org/msg36823.html

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
I would like to fix this.
