### ISSUE TITLE
[Improvement] Improve the readability of ServiceControl list/get operations

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#2006]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

When the `get server` and `list server` commands are displayed, when the namespace exceeds the minimum width, it will be glued to the hostname.

```sh
kyuubi/bin/kyuubi-ctl get  server
kyuubi/bin/kyuubi-ctl list server
```

### How should we improve?

Add a space beyond the minimum cell width in non-verbose mode.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Related issue #1595
