### ISSUE TITLE
[Bug] EventLoggingService creates an incorrect directory

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/incubator-kyuubi#2012]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In EventLoggingService.scala ，when EventLoggerType is set to Json
kyuubi created an error directory, it should not be the ENGINE_EVENT_JSON_LOG_PATH but the SERVER_EVENT_JSON_LOG_PATH

<img width="557" alt="微信图片_20220304165614" src="https://user-images.githubusercontent.com/14961757/156731812-6edfdce4-cf47-42ba-a8b9-86ceee815660.png">
<img width="605" alt="微信图片_20220304165633" src="https://user-images.githubusercontent.com/14961757/156731828-77b4b6c3-cb81-4f67-b6dd-c75baa772c7b.png">

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Thanks for reporting this issue, have a glance of code, the name is confusing, as we has 2 classes share the name `EventLoggingService` in both `kyuubi-server` module and `kyuubi-spark-sql-engine` module, would you please also rename them to `KyuubiEventLoggingService`(for kyuubi-server) and `SparkEventLoggingService` (for kyuubi-spark-sql-engine)?

**Comment by jiaoqingbo** [comment]
> Thanks for reporting this issue, have a glance of code, the name is confusing, as we has 2 classes share the name `EventLoggingService` in both `kyuubi-server` module and `kyuubi-spark-sql-engine` module, would you please also rename them to `KyuubiEventLoggingService`(for kyuubi-server) and `SparkEventLoggingService` (for kyuubi-spark-sql-engine)?

ok，I would rename them
