### ISSUE TITLE
[Subtask] Hive Backend Engine - Support HiveSQLEngine instance on YARN cluster

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2025]

**Comment by zhaomin1423** [comment]
I am interested in it. Could you provide more description?

**Comment by zhaomin1423** [comment]
> @zhaomin1423, are you working for this issue? If no, I will assign this ticket to @deadwind4.

I am working on it. But, I may be finished slow.

**Comment by deadwind4** [comment]
I have tested the hive on YARN, and I can fix this coming soon.

**Comment by zhaomin1423** [comment]
> I have tested the hive on YARN, and I can fix this coming soon. @zhaomin1423 May I fix this? Thanks a lot.

It's ok.
