### ISSUE TITLE
[Subtask] Hive Backend Engine - Events support

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2028]

**Comment by zhaomin1423** [comment]
I want to do it.

**Comment by zhaomin1423** [comment]
The default value of engine.event.loggers is spark, but it can't be used by other engines. Could we need to modify it？Otherwise, other engines must set it manually. @yaooqinn

**Comment by yaooqinn** [comment]
maybe we can ignore it and change the desc
