### ISSUE TITLE
[INFRA][Improvement] Redirect Issues/PR Notifications to notifications@kyuubi.apache.org

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2036]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Reduce SPAM-like mails in dev list.

### How should we improve?

- Create notifications@kyuubi.apache.org, this requires ASF member privilege for https://selfserve.apache.org/ so we need help from our mentors
- update .asf.yaml 

https://github.com/apache/incubator-kyuubi/blob/master/.asf.yaml#L45-L46

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @WillemJiang @aajisaka @zjffdu @Apache9, kindly ping mentors for help. thanks

**Comment by zjffdu** [comment]
@yaooqinn I have created this mail list, but you have to wait for 24 hours. 
```
Your request for a new mailing list has been received and will automatically be processed within 24 hours.
 We will notify your PMC when the list has been created.
```

**Comment by yaooqinn** [comment]
Thanks very much, @zjffdu. If you don't mind, can you also send a PR to update `update .asf.yaml`? If you can't find the time, I can cc this to others

**Comment by zjffdu** [comment]
@yaooqinn PR is created https://github.com/apache/incubator-kyuubi/pull/2042 let me know if jira ticket is needed.

**Comment by yaooqinn** [comment]
thanks Jeff for the PR, Jira is not necessary as we use Github issues as a tracking tool.

**Comment by yaooqinn** [comment]
thanks, pr merged
