### ISSUE TITLE
[Improvement] Upgrade log4j/2.x/ to 2.17.2

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2043]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2

### How should we improve?

log4j.version from 2.17.1 to 2.17.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by RishiKumarRay** [comment]
Do we just have to update the version

**Comment by yaooqinn** [comment]
Yes, we only need to update the version and `build/dependency.sh --replace` to re-generate to dependency checker if nothing breaks in log4j-2.17.2.

**Comment by RishiKumarRay** [comment]
@yaooqinn please review PR #2046
