### ISSUE TITLE
[Bug] there are Spelling mistakes and inappropriate naming

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/incubator-kyuubi#2066]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In TFrontendService.scala the comment **hive-service-prc** should be **hive-service-rpc**

the **HiveTBinaryFrontend.scala** should be rename to **HiveTBinaryFrontendService** 
 ，the same pattern as **SparkTBinaryFrontendService**、**FlinkTBinaryFrontendService**

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
lets rm the service from spark and flink instead？be shorter be better

**Comment by jiaoqingbo** [comment]
> lets rm the service from spark and flink instead？be shorter be better
may be more appropriate to keep the service suffix for consistency

**Comment by SteNicholas** [comment]
> lets rm the service from spark and flink instead？be shorter be better

@yaooqinn, IMO, it's better to rename by adding `Service` which is directly known as service.

**Comment by yaooqinn** [comment]
Ok
