### ISSUE TITLE
[Improvement] Support Flink yarn-session job

### ISSUE THREAD

**Issue by deadwind4** [apache/incubator-kyuubi#2070]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The 'flink-sql-client.jar' has supported submitting a job to Yarn. We only make a few changes.

### How should we improve?

We only change 2 lines of code.
The following is the change code.

add GenericCLI in FlinkSQLEngine class
```
     val engineContext = new DefaultContext(
        dependencies.asJava,
        flinkConf,
        List[CustomCommandLine](new DefaultCLI, new GenericCLI(flinkConf, flinkConfDir)).asJava)
```

append HADOOP_CLASSPATH to FLINK_HADOOP_CLASSPATH in flink-sql-engine.sh

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @yanghua shall this be included in 1.5?

**Comment by yanghua** [comment]
> cc @yanghua shall this be included in 1.5?

I suggest we can move it into 1.6. Additionally, the session mode needs more discussion. WDYT?

**Comment by deadwind4** [comment]
When we debug Flink SQL and transform data by Flink Batch job, we need yarn-session mode. Some users submit ten thousand Flink batch jobs that transform a few data in a short time, they need to submit speed faster.

**Comment by yaooqinn** [comment]
Yea we can target this to master, thanks @deadwind4 and waiting for your PR.

**Comment by deadwind4** [comment]
As only support yarn-session mode, so we will not load HADOOP_CLASSPATH. Users only set HADOOP_CONF_DIR or YARN_CONF_DIR.
