### ISSUE TITLE
[Improvement] YARN_CONF_DIR shall be added to kyuubi server classpath as HADOOP_CONF_DIR

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2081]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

YARN_CONF_DIR aslo contains configurations for kyuubi server to respect

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaoqingbo** [comment]
please assign to me

**Comment by ulysses-you** [comment]
> please assign to me

@jiaoqingbo done, thank you !

**Comment by jiaoqingbo** [comment]
> > please assign to me
> 
> @jiaoqingbo done, thank you !

please assign to @SteNicholas，he has submitted a more reasonable pr ，thx

**Comment by ulysses-you** [comment]
thank you @jiaoqingbo and @SteNicholas !
