### ISSUE TITLE
[Improvement] Support arbitrary parameters for KyuubiConf or kyuubi prefixed only

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2084]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

  private def loadFromMap(props: Map[String, String] = Utils.getSystemProperties): KyuubiConf = {
    for ((key, value) <- props if key.startsWith("kyuubi.") || key.startsWith("spark.") ||
        // for user specific defaults
        key.startsWith("___")) {
      set(key, value)
    }
    this
  }

In KyuubiConf, we now load kyuubi.* and spark.* from the kyuubi-defaults.conf config file or sys.props, but we now support other engine types, we shall support all engine conf or remove spark.* here

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@jiaoqingbo, do you have interest to take this ticket? Sorry for previous work for the issue assigned to you.

**Comment by jiaoqingbo** [comment]
i would like to do this，thx
