### ISSUE TITLE
[Improvement] Add a labeler github action to triage PRs

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2085]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Using https://github.com/marketplace/actions/label-actions to triage PRs roughly to get reviewers' attention easier

### How should we improve?

![image](https://user-images.githubusercontent.com/8326978/157582082-f75bb3fc-55a2-4040-9f2e-424c768e1178.png)

![image](https://user-images.githubusercontent.com/8326978/157582293-3ade2b3f-d796-478d-8bf1-d4a1e62ddbe6.png)

a label.yml related to our codebase, and an action to trigger this flow will be needed.

Labels shown above maybe easily tagged by robot

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @cfmcgrady , are you interested?

**Comment by cfmcgrady** [comment]
let me try when I have time :)

**Comment by yaooqinn** [comment]
thanks
