### ISSUE TITLE
[Improvement] Add issue template for subtasks

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2086]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add issue template for subtasks for easily being labeled and linked to it's umbrella

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
I can help this
