### ISSUE TITLE
[Improvement] Add issue template for documentation improvement

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2087]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add issue template for documentation improvement

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yangrong688** [comment]
Hi @yaooqinn , could you please assign this ticket to me？

**Comment by yaooqinn** [comment]
done, thanks @yangrong688
