### ISSUE TITLE
[CI] Upload Test Log for CI failure shall contain trino engine log

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2094]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/incubator-kyuubi/blob/master/.github/workflows/master.yml#L93

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
I am willing to do it.
