### ISSUE TITLE
[FEATURE] Enhance the retry logic for thrift rpc

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2102]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

For the ExecuteStatement operation, if the internal thrift connection(between kyuubi server and kyuubi engine) has broken, it still retry and costs long time.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by samochod23** [comment]
ACCUWETHERIN ŻONĘ PARK T14:48P.M.3789
