### ISSUE TITLE
Kill yarn job using yarn client API when kyuubi engine initialization times out and yarn application status is accepted 

### ISSUE THREAD

**Issue by 942011334** [apache/incubator-kyuubi#2104]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In a mixed cluster, both Kyuubi Server and NodeManger are deployed in the same machine. When the kyuubi engine initialization times out and the yarn application status is accepted, the kyuubi server will execute the local stop-application.sh script to kill the application. Executing "yarn application -kill appid" command throws NodeManger's Jmx port conflict exception. 

### How should we improve?

 it is better to use yarn client API to kill the Application. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
Looks reasonable

**Comment by SteNicholas** [comment]
@942011334, do you have interest to fix the bug? If no, @yaooqinn could you please assign to me?

**Comment by 942011334** [comment]
Yes , I am willing to submit a PR!

**Comment by 942011334** [comment]
hello  PMC , @yaooqinn  help review and merge code . 
https://github.com/apache/incubator-kyuubi/pull/2110

**Comment by yaooqinn** [comment]
hi @942011334 jiadongdong@bilibili.com shall be added to your github account - emails. thus，your following PRs will run CI automatically
