### ISSUE TITLE
[Improvement] Support output progress bar in Spark engine

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#2119]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In the `ExecuteStatement#waitStatementComplete` method, only output Query is Running to the log, the user does not know the progress of the query.

### How should we improve?

Add a listener to the Spark engine to output the stage progress of the current statement.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
## Current

![image](https://user-images.githubusercontent.com/3898450/158053283-f0c5f37a-ccc9-4100-a70d-4583f2424c41.png)

## Fix

![image](https://user-images.githubusercontent.com/3898450/158053320-f0c96ae6-106a-4fb8-92cd-da3934792c4f.png)

**Comment by yaooqinn** [comment]
looks great
