### ISSUE TITLE
[SUB-TASK][KPIP-2] GetColumns operation throws UnsupportedOperationException

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-kyuubi#2129]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

#1322

### Motivation

GetColumns operation throws UnsupportedOperationException

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by fsk119** [comment]
I am willing to contribute. Could you assign it to me? @SteNicholas

**Comment by pan3793** [comment]
Thanks @fsk119
