### ISSUE TITLE
[Improvement] Add IDEA Setup Guide in Contribution Guidelines of Documents

### ISSUE THREAD

**Issue by deadwind4** [apache/incubator-kyuubi#2142]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add IDEA IDE Setup Guide in [Contribution Guidelines](https://kyuubi.apache.org/docs/latest/community/contributions.html#contribution-guidelines)

Inspired by Flink docs.
https://nightlies.apache.org/flink/flink-docs-master/docs/flinkdev/ide_setup/#checkstyle-for-scala

### How should we improve?

I want to add a Copyright Profile setup, a CheckStyle for Scala setup and a Scalafmt setup.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
please add it to dev tools and add a link in contribution guide

**Comment by pan3793** [comment]
Closed by #2142
