### ISSUE TITLE
[Bug] Flink ui can not access

### ISSUE THREAD

**Issue by cutiechi** [apache/incubator-kyuubi#2147]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Flink ui can not access

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @yanghua @deadwind4

**Comment by deadwind4** [comment]
Can't you access Flink Web UI? Either standalone or yarn-session?
In my opinion,  Flink Web UI has nothing to do with Kyuubi.

**Comment by cutiechi** [comment]
@deadwind4 Can you show me the config?

**Comment by deadwind4** [comment]
@cutiechi You can run ${FLINK_HOME}/bin/start-cluster.sh and access Flink UI in localhosts:8081

**Comment by cutiechi** [comment]
@deadwind4 but when i execute sql there is no job on flink ui
<img width="334" alt="image" src="https://user-images.githubusercontent.com/27606234/158536626-b57d9d32-9cf6-4ce8-814b-eb23a3034325.png">

**Comment by pan3793** [comment]
It's does not like an issue but a question, please go ahead in discussion channel
