### ISSUE TITLE
[Improvement] Change log to reflect exactly why getting token failed

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/incubator-kyuubi#2156]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In HiveDelegationTokenProvider.scala when forget to Specify Hive metastore configurations In $KYUUBI_HOME/conf/kyuubi-defaults.conf or Place  hive-site.xml into $KYUUBI_HOME/conf，the
metastoreUris will be empty，which will make the if condition return false，cause the client is null。

![image](https://user-images.githubusercontent.com/14961757/158722885-fecf90e3-54ba-49c6-ad73-82d01400134e.png)

In HadoopCredentialsManager，provider.delegationTokensRequired will return false，the log 
 is Inaccurate，
![image](https://user-images.githubusercontent.com/14961757/158722997-3b743c2e-7f17-4e4d-80ca-aed1fb0d16b4.png)

### How should we improve?

“Check your configuration to see if security is disabled or not.”

should be changed to “Check your configuration to see if security is disabled or not.If security is enabled,some configuration of ${provider.serviceName} is missing”

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @zhouyifan279
