### ISSUE TITLE
Bump Jersey 2.35

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2197]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/eclipse-ee4j/jersey/releases/tag/2.35

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
this issue should be jersey no jetty?

**Comment by pan3793** [comment]
> this issue should be jersey no jetty?

Oops, you are right.
