### ISSUE TITLE
[Improvement] Add CHANGELOG.md to codebase for maintaining release notes

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2211]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, we use the GitHub release page to draft release notes for the voting processes both in dev and general mailing lists. The problem is that this page is modifiable during the whole release process, people who help vote may see different things.
According to the suggestion[1] from Jiajie Zhong in generaral@, we'd better maintain a `CHANGELOG.md` and deliver it together with future releases.

[1] https://lists.apache.org/thread/fq4q06xrtobdk1s30r034zm52yyq7q03

### How should we improve?

- A `CHANGELOG.md` in the codebase to curate changes for each milestone or releases
- A ease-to-use stript,  or a CI flow, or a manually manner to do this work

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yangrong688** [comment]
Hi @yaooqinn , could you please assign this ticket to me？

**Comment by yaooqinn** [comment]
thanks @yangrong688

**Comment by cfmcgrady** [comment]
kindly ping @yangrong688, Are you working on this?

**Comment by yangrong688** [comment]
@cfmcgrady Yes, I'm planning to write a script like [build_changelog_annotations.py](https://github.com/apache/airflow/blob/main/dev/chart/build_changelog_annotations.py) in this week, maybe slow but I'm still working on it.
