### ISSUE TITLE
[Improvement] Add Spark Cluster mode on Kubernetes integration test

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#2216]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add Spark cluster mode it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ulysses-you** [comment]
in general, this is for you @zwangsheng  : )

**Comment by zwangsheng** [comment]
Ok, I'll catch up.
