### ISSUE TITLE
[FEATURE] Support Flink 1.15

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2238]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Flink 1.15.0 is out, Kyuubi needs to support it.

BTW, considering the frequent changes of the Flink API and the resource limitations of Kyuubi, we need to discuss Kyuubi's support for Flink's version strategy. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @SteNicholas @yanghua @link3280 @deadwind4

**Comment by deadwind4** [comment]
I will research Apache Zeppelin's code of supporting the Flink multiple version.

**Comment by link3280** [comment]
Flink adopts a time-based release strategy and releases a new version every 3-4 months. However, most companies wouldn't follow very closely and might stick to some favorable version for some time (I think 1.11/1.12 still has the most user base). Thus, I think it's good to support the latest 3 versions if possible (Flink officially maintained versions plus 1), to leave some time for users to upgrade.

**Comment by KenjiFujima** [comment]
@pan3793 @deadwind4 @link3280, thanks for the feedback of the Flink engine support. Flink 1.15 version is delayed and will release for some time. IMO, the multiple Flink version support could refer to the implementation of the Zeppelin, which is currently supported by @zjffdu.
@zjffdu, could you please give some suggestion for the multiple Flink version support?

**Comment by yanghua** [comment]
> Flink adopts a time-based release strategy and releases a new version every 3-4 months. However, most companies wouldn't follow very closely and might stick to some favorable version for some time (I think 1.11/1.12 still has the largest user base). Thus, I think it's good to support the latest 3 versions if possible (Flink officially maintained versions plus 1), to leave some time for users to upgrade.

+1 for maintaining multiple Flink versions (I am ok about 2 or 3).

**Comment by wolfboys** [comment]
Hello everyone, Regarding the support for multiple versions of flink, I have implemented it in the StreamX project, have relevant experience, and have supported the latest flink 1.15 support, and can switch flink versions freely. I am very interested in this issue, can you please assign to me, 😊

**Comment by wolfboys** [comment]
Hello everyone, Regarding the support for multiple versions of flink, I have implemented it in the StreamX project, have relevant experience, and have supported the latest flink 1.15 support, and can switch flink versions freely. I am very interested in this issue, can you please assign to me, 😊

**Comment by yaooqinn** [comment]
@wolfboys feel free to submit a PR
