### ISSUE TITLE
[Umbrella][KPIP-4] Support to submit batch job

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2240]
### Describe the proposal

See the proposal in https://github.com/apache/incubator-kyuubi/discussions/2304

![ccoe_review-Page-4 drawio](https://user-images.githubusercontent.com/6757692/168047188-9f08a509-6e39-494e-8f9d-ea8391446a79.png)

### Task list
- [x] #2305 @turboFei 
- [x] #2306 @turboFei 
- [x] #2307 @turboFei 
- [x] #2308 @turboFei 
- [x] #2309 @turboFei 
- [x] #2373 @turboFei 
- [x] #2374 @turboFei 
- [x] #2375 @zhaomin1423 
- [x] #2376 @turboFei 
- [x] #2573 @ulysses-you 
- [x] #2377 @ulysses-you 
- [x] #2378 
- [x] #2556 @turboFei 
- [x] #2379 @turboFei 
- [ ] #2322  
- [x] #2628 @lightning-L 
- [x] #2632 @ulysses-you 
- [x] #2643 @lightning-L 
- [ ] #2646 @ulysses-you 
- [x] #2661 @turboFei 
- [x] #2674 @turboFei 
- [x] #2697 @turboFei 
- [x] #2715 @turboFei 
- [x] #2719 @turboFei 
- [x] #2765 @lightning-L 
- [x] #2820 @turboFei 
- [x] #2834 @turboFei 
- [x] #2859 @turboFei 
- [x] #2880 @ulysses-you 
- [x] #2911 @turboFei 
- [x] #2957 @turboFei 
- [x] #2962 @turboFei 
- [x] #2964 @turboFei 
- [x] #2978 @turboFei 
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
## API Design
### GET /batches

Returns all the active batch sessions.

#### Request Parameters

| Name | Description                       | Type |
| :--- | :-------------------------------- | :--- |
| from | The start index to fetch sessions | int  |
| size | Number of sessions to fetch       | int  |

#### Response Body

| Name     | Description                                                  | Type |
| :------- | :----------------------------------------------------------- | :--- |
| from     | The start index of fetched sessions                          | int  |
| total    | Number of sessions fetched                                   | int  |
| sessions | [Batch](#batch) list | list |

### POST /batches

#### Request Body

| Name      | Description                                        | Type            |
| :-------- | :------------------------------------------------- | :-------------- |
| resource  | The resource containing the application to execute | path (required) |
| proxyUser | User to impersonate when running the job           | string          |
| className | Application Java/Spark main class                  | string(required)          |
| jars      | jars to be used in this session                    | list of strings |
| files     | files to be used in this session                   | list of strings |
| name      | The name of this session                           | string          |
| conf      | Configuration properties                           | Map of key=val  |
| args      | Command line arguments for the application         | list of strings |


#### Response Body

The created [Batch](#batch) object.

### GET /batches/{batchId}

Returns the batch session information.

#### Response Body

The [Batch](#batch).

### GET /batches/{batchId}/state

Returns the state of batch session

#### Response

| Name  | Description                        | Type   |
| :---- | :--------------------------------- | :----- |
| id    | Batch session id                   | tring  |
| state | The current state of batch session | string |

### DELETE /batches/{batchId}

Kills the [Batch](#batch) job.

### GET /batches/{batchId}/log

Gets the log lines from this batch.

#### Request Parameters

| Name | Description                       | Type |
| :--- | :-------------------------------- | :--- |
| from | Offset                            | int  |
| size | Max number of log lines to return | int  |

#### Response Body

| Name | Description              | Type            |
| :--- | :----------------------- | :-------------- |
| id   | The batch id             | string          |
| from | Offset from start of log | int             |
| size | Number of log lines      | int             |
| log  | The log lines            | list of strings |

### Batch

| Name    | Description                        | Type                                                         |
| :------ | :--------------------------------- | :----------------------------------------------------------- |
| id      | The session id                     | string                                                       |
| appId   | The application id of this session | string                                                       |
| appInfo | The detailed application info      | Map of key=val,<br />such as submitssion command,<br />submission time. |
| log     | The log lines                      | list of strings                                              |
| state   | The batch state                    | string                                                       |

**Comment by turboFei** [comment]
The livy [Multi node HA for batch sessions](https://github.com/meisam/livy/wiki/Multi-node-HA-for-batch-sessions)

**Comment by turboFei** [comment]
cc @SteNicholas  has created ticket for flink

**Comment by zhaomin1423** [comment]
Hi , I am interested in it , could you assign 2375-2379 to me?

**Comment by turboFei** [comment]
> Hi , I am interested in it , could you assign 2375-2379 to me?

Thanks.
You can try to take them one by one.

Because I am focus on this in my company recently, so, I need implement it in a planning time window.

**Comment by waywtdcc** [comment]
Can I read the table list and table field list under the Flink catalog database?

**Comment by turboFei** [comment]
> Can I read the table list and table field list under the Flink catalog database?

It is not the goal of this umbrella, you might need interactive session instead of batch.
