### ISSUE TITLE
[Bug] when start kyuub server ,the log print ERROR Filters contains invalid attributes "onMatch", "onMismatch"

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/incubator-kyuubi#2247]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

![image](https://user-images.githubusercontent.com/14961757/160552156-d3898e81-68da-4b8d-9233-e317c81f0d2b.png)

### Affects Version(s)

1.5.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
Looks like a bug of log4j2
https://stackoverflow.com/questions/34085162/multiple-filters-for-log4j-using-properties-file

**Comment by deadwind4** [comment]
@pan3793 May we change `log4j2.propertes` to `log4j2.xml`? I want to fix this.

**Comment by pan3793** [comment]
Spark should suffer this as well, considering Spark and Hive both use `log4j2.propertes`, we'd better keep the consistent with the ecosystem, and we can get rid of this issue once get thrift upgraded.
