### ISSUE TITLE
[FEATURE] Support to limit the spark engine max running time

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2250]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

For some use case, we might need restart the spark engine periodically.
For example, to load the latest UDFs and jars.

So we need support to limit the spark engine max running time.

1. if the spark engine has run for the specified time, it can deregister itself from engine discovery space(such as zookeeper) so that it will not receive new request
2. wait the current connection closed, then terminate the engine life

Note that, this feature is not suite for flink engine, not sure whether it is suite for trino engine.
We will implement it for spark in this PR.

### Motivation

Restart the engine to load the latest udf and jars.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
cc @lightning-L

**Comment by lightning-L** [comment]
Ok, I will take on this task
