### ISSUE TITLE
[Bug] The engine state of Spark's EngineEvent is hardcoded with 0

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2255]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The wrong output..
```
2022-03-31 16:27:53.041 INFO spark.SparkSQLEngine:
    Spark application name: kyuubi_USER_SPARK_SQL_kentyao_default_dc3acf5b-52d0-4ae8-888d-55a005890ae9
          application ID:  local-1648715265202
          application web UI: http://10.242.189.214:64540
          master: local[*]
          version: 3.2.1
          driver: [cpu: 1, mem: 1g]
          executor: [cpu: 2, mem: 1g, maxNum: 2]
    Start time: Thu Mar 31 16:27:44 CST 2022

    User: kentyao (shared mode: USER)
    State: LATENT
```

Where the state shall be STARTED at the time.

### Affects Version(s)

1.3.1, 1.4.1, 1.5.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
could you please assign it to me?

**Comment by yaooqinn** [comment]
thanks @Nick-0723
