### ISSUE TITLE
[Improvement] Use unique tag to kill applications

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2289]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, we use yarn APPLICATION IDs grabbed from logs to kill unhealthy spark applications

We can improve it by using a unique tag pre-set in `spark.yarn.tags`. In this way, we can extend this feature to other cluster managers like k8s

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
Hi, I want to help improve this, could you please assign this to me, thanks

**Comment by Nick-0723** [comment]
Do we need handle this for Flink engine ?

**Comment by yaooqinn** [comment]
let's fix them step by step
