### ISSUE TITLE
[Subtask] HiveEngineEvent toString is not pretty

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2297]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

2022-04-08T11:34:33,368 INFO [main] org.apache.kyuubi.engine.hive.HiveSQLEngine - org.apache.kyuubi.engine.hive.events.HiveEngineEvent@ec865c63

### Parent issue

#2010 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wolfboys** [comment]
please assign to me.😁

**Comment by yaooqinn** [comment]
assigned @wolfboys ,thanks
