### ISSUE TITLE
[DOCS] Fix typo and style issue on GitHub issue template and website

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-kyuubi#2315]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Affects Version(s)

ALL

### Imporving the documentation

1) Fix the header for this section: "Imporving the documentation" => "Improving the documentation"

2) Fix the download page. HTML attribute values should be quoted.
e.g. href=/mailing_lists.html => href="/mailing_lists.html"
Similarly for all other values.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
> Fix the download page. HTML attribute values should be quoted.
e.g. href=/mailing_lists.html => href="/mailing_lists.html"
Similarly for all other values.

Hi @yangrong688, I saw you send a PR to fix the issue 1, and the issue 2 should be fixed in https://github.com/apache/incubator-kyuubi-website,  would you like to fix it?

**Comment by yangrong688** [comment]
@pan3793 I'd like to have a try.

**Comment by pan3793** [comment]
Thanks @sebbASF for reporting the issues, and thanks @yangrong688 for fixing!

**Comment by sebbASF** [comment]
Thanks for the very quick fix!
