### ISSUE TITLE
Upgrade hive-service-rpc 3.1.3

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2317]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Upgrade hive-service-rpc 3.1.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
I would like to take it, please assign this to me.
