### ISSUE TITLE
Separate events to a submodule - `kyuubi-event` like `kyuubi-metrics`

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2323]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Separate events to a submodule - `kyuubi-event` like `kyuubi-metrics` 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
I am willing to do it.

**Comment by zhaomin1423** [comment]
Event moudule need use common module, but Session in common module also use KyuubiEnvet, there are circular dependencies. Should we move the method to subclass of Session, or separate session to a module?

**Comment by yaooqinn** [comment]
> Should we move the method to subclass of Session

+1
