### ISSUE TITLE
[Improvement] Add dependabot to auto update maven dependencies.

### ISSUE THREAD

**Issue by yangrong688** [apache/incubator-kyuubi#2335]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Projects like Apache Hadoop / Zeppelin enabled dependabot to auto detect maven dependency update.
We can also enable it to help us better update maven dependencies' version.

ref:
https://github.com/apache/hadoop/pull/3890
https://github.com/apache/zeppelin/pull/4342

### How should we improve?

1. add configuration file dependabot.yml
2. enable dependabot ( should operate by committer)
this step can follow the directions of below article

https://cloud.tencent.com/developer/article/1910792

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yangrong688** [comment]
@pan3793 @yaooqinn WDYT?

**Comment by pan3793** [comment]
It may not suitable for Kyuubi, because
1. Kyuubi has a `dev/dependencyList` to avoid unexpected dependency change
2. Kyuubi has integate to many components like hive zookeeper, we can not just use the latest version, it may breaks the compatible with other components.

**Comment by yangrong688** [comment]
Thanks of your detail explaination, I got it.

> It may not suitable for Kyuubi, because
> 
> 1. Kyuubi has a `dev/dependencyList` to avoid unexpected dependency change
> 2. Kyuubi has integrated to many components like hive zookeeper, we can not just use the latest version, it may break the compatible with other components.

Thanks for your detail explaination, I got it. I will close this issue then.
