### ISSUE TITLE
Bump Delta Lake 1.2.0

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2355]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Delta Lake 1.2.0 is available few days ago, which is compatible with Spark 3.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
plz assign it to me, tks.
