### ISSUE TITLE
[Subtask] Configuring Hive engine heap memory and java opts

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2360]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Introduce

-  kyuubi.engine.hive.memory
    - default 1g
    -  The heap memory for the hive query engine
-  kyuubi.engine.hive.java.options
    - default optional
    -  The extra java options for the hive query engine
-  kyuubi.engine.hive.extra.classpath
    - default optional ()
    - The extra classpath for the hive query engine, for configuring location of hadoop client jars, etc

the current HIVE_HADOOP_CLASSPATH/HADOOP_CLASSPATH can be replaced by kyuubi.engine.hive.extra.classpath

### Parent issue

#2010

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
I will do it later.
