### ISSUE TITLE
[Improvement] Configuring Trino Engine heap memory and java opts

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2361]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Introduce

- kyuubi.engine.trino.memory
   - default 1g
   - The heap memory for the trino query engine
- kyuubi.engine.trino.java.options
    - default optional
    - The extra java options for the trino query engine
- kyuubi.engine.trino.extra.classpath
    - default optional
    - The extra classpath for the trino query engine, for configuring other libs which may need by the trino engine =

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
I am willing to do it.
