### ISSUE TITLE
[SUB-TASK][KPIP-4] Implement BatchesResource GET /batches 

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2375]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

#2240

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
@zhaomin1423  would you like to take this at first?

**Comment by zhaomin1423** [comment]
sure, thank you.



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Fei ***@***.***> |
| 日期 | 2022年04月16日 11:34 |
| 收件人 | ***@***.***> |
| 抄送至 | Xiao ***@***.******@***.***> |
| 主题 | Re: [apache/incubator-kyuubi] [SUB-TASK][KPIP-4] Implement BatchesResource GET /batches (Issue #2375) |

@zhaomin1423 would you like to take this at first?
