### ISSUE TITLE
[SUBTASK][#2100] Support Flink StringData Data Type

### ISSUE THREAD

**Issue by link3280** [apache/incubator-kyuubi#2405]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, Flink uses its legacy data type system in CollectSink, but sooner would move to the new type system. Kyuubi should adapt to the new data type system beforehand.

### How should we improve?

Support both the legacy and the new Flink type system in Kyuubi.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by link3280** [comment]
The new type system is more complicated than I anticipated, thus I'm preparing to split this into multiple PRs.

**Comment by yaooqinn** [comment]
thank you @link3280

**Comment by link3280** [comment]
Closed via https://github.com/apache/incubator-kyuubi/pull/2718.
