### ISSUE TITLE
[Test]  Test coverage for PrivilegesBuilder

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2416]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Add Unit tests for
```scala
AlterTableChangeColumnCommand
InsertIntoDataSourceCommand
InsertIntoDataSourceDirCommand
LoadDataCommand
RepairTableCommand
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @packyan, are you interested?

**Comment by packyan** [comment]
> ```scala
> InsertIntoDataSourceCommand
> ```

ok, asign it to me.
