### ISSUE TITLE
[Bug] For connection level engines if exception occurs in open session phase, it may be orphaned

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2419]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

For connection-level engines, if an exception is thrown in the open session phase, it will not be reached again, it may be orphaned

### Affects Version(s)

1.5.0,1.4.1,1,3.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
How about adding a close method to `EngineRef`?

**Comment by yaooqinn** [comment]
Sorry for being late! @wForget 

I am working on #2447, an application management layer.

Maybe we can handle that via the APIs newly added when connection fail for connection share level

**Comment by wForget** [comment]
> Sorry for being late! @wForget
> 
> I am working on #2447, an application management layer.
> 
> Maybe we can handle that via the APIs newly added when connection fail for connection share level

That doesn't seem to be enough, we also need to kill the ProcBuilder process.
