### ISSUE TITLE
[DOCS] button "Download" is invalid

### ISSUE THREAD

**Issue by zhanqian-1993** [apache/incubator-kyuubi#2432]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

![image](https://user-images.githubusercontent.com/14138772/164390299-9265ec12-dd1a-4a40-8fc0-4a6675077540.png)
without "href" attribute, click has no response and it can't jump the right website "https://kyuubi.apache.org/releases.html". I think It will mistake getting started develop. 

### Affects Version(s)

master

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
yes, this shall target https://kyuubi.apache.org/releases.html, can you send a PR to fix?

**Comment by ulysses-you** [comment]
good catch ! @zhanqian-1993
