### ISSUE TITLE
[Improvement] Add FilteredShowDatabasesCommand to AuthZ module

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2473]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

FilteredShowDatabasesCommand filters the results from ShowDatabasesCommand and leaves those only with permissions

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
I am interested in it.

**Comment by yaooqinn** [comment]
thanks @zhaomin1423

**Comment by MLikeWater** [comment]
@yaooqinn We can use ShowNamespaces, I have completed this feature and passed the test. I will submit the PR later.

**Comment by MLikeWater** [comment]
@yaooqinn @zhaomin1423 https://github.com/apache/incubator-kyuubi/pull/2580 Please help to check it, thanks.
