### ISSUE TITLE
Backport HIVE-19018 to Kyuubi Beeline

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2478]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Allow `sql` w/o `;` at end to execute when using `beeline -e 'sql'`

### How should we improve?

Backport https://github.com/apache/hive/commit/52290e72b3029eddc17f0a0482fd6c1a05840bb0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaoqingbo** [comment]
please assgin this to me

**Comment by yaooqinn** [comment]
shall we also add a doc or faq?
