### ISSUE TITLE
[FEATURE] show session level runtime config for SparkSql engine

### ISSUE THREAD

**Issue by gabrywu** [apache/incubator-kyuubi#2484]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

show session level runtime config for SparkSqlEngine. 

### Motivation

> For now, a SparkSQLEngine can be shared by USER/POOL. In this case, each connection holds an isolated spark session instance. And each isolated spark session instance inherits its own runtime configs from the SparkSQLEngine.

> we want to know the runtime configs of each SQL, especially when a SQL throws errors or has a bad performance.

> if community agree with that, I will create a PR for this feature 

### Describe the solution

My proposal is that we add a runtime config  page to `Kyuubi Query Engine Session` tab 

<img width="980" alt="image" src="https://user-images.githubusercontent.com/8545796/165269387-6b5618f2-e0f9-4456-8656-34c15b1c2869.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
I'm implementing it. I've finished development and I'm testing it

**Comment by gabrywu** [comment]
> I'm implementing it. I've finished development and I'm testing it

It's great, expecting your PR
