### ISSUE TITLE
[FEATURE] Implement the progress of statement

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#2493]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

I want to implement progress of statement in kyuubi. 

Implementation steps:
1. Add `JobProgressUpdate` property in OperationStatus and pass to `TProgressUpdateResp` of TGetOperationStatusResp in `GetOperationStatus` method.
2. Calculate JobProgressUpdate and update into ExecuteStatement Operation.

How we calculate JobProgressUpdate?
1. Calculate it by `SparkStatusTracker` like in hive. [RemoteSparkJobStatus.java](https://github.com/apache/hive/blob/branch-3.1/ql/src/java/org/apache/hadoop/hive/ql/exec/spark/status/impl/RemoteSparkJobStatus.java)

or

2. Calculate it in `SQLOperationListener`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
@wForget SGTM

**Comment by ic4y** [comment]
Does it support progress retrieval for other engines, such as the Hive engine and Trino engine?

**Comment by pan3793** [comment]
Not yet, but I suppose it's not very difficult if the engine itself has an API to expose the progress, would you like to try? @ic4y
