### ISSUE TITLE
[Subtask] Kyuubi Spark TPC-DS Connector - Set nullable in table schema

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2541]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Follow the TPC-DS document[1] to set `nullable` for columns in the table schema.

https://tpc.org/TPC_Documents_Current_Versions/pdf/TPC-DS_v3.2.0.pdf

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/2538

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
Could you please assign this to me?

**Comment by pan3793** [comment]
Thanks, assigned.
