### ISSUE TITLE
[Subtask] Kyuubi Spark TPC-DS Connector - Add tiny scale

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2553]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Current available scales: 0, 1, 10, 100, 300, 1000, 3000, 10000, 30000, 100000.

Event scale 1G is a little bit large for demo on laptop, we can introduce a scale 0.01 and name the database as `tiny` for demo purpose.

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/2538

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yihua** [comment]
I’m interested in taking this up.

**Comment by pan3793** [comment]
Assigned, thx.
