### ISSUE TITLE
[FlakyTest] open batch session *** FAILED ***

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#2578]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

```
- open batch session *** FAILED ***
  The code passed to eventually never returned normally. Attempted 3577 times over 3.0007155053 minutes. Last failure message: FINISHED did not equal ERROR. (KyuubiBatchYarnClusterSuite.scala:87)
```

https://github.com/apache/incubator-kyuubi/runs/6320947639?check_suite_focus=true

### Parent issue

#1733

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cfmcgrady** [comment]
cc @turboFei

**Comment by turboFei** [comment]
Thanks for ping me.
It is duplicated with #2522 
And has been fixed by https://github.com/apache/incubator-kyuubi/pull/2557
