### ISSUE TITLE
[INFRA] Migrate to Ubuntu 22.04

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2584]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Ubuntu 22.04 is available and is the latest LTS version, we can migrate our CI workload from 20.04 to this new one.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
I want to try it. @pan3793

**Comment by pan3793** [comment]
Thanks, assigned

**Comment by deadwind4** [comment]
Now, `actions-setup-minikube ` doesn't support Unbuntu 22, we wait for it?

https://github.com/manusa/actions-setup-minikube

**Comment by pan3793** [comment]
Yea, it's not an urgent matter, let's wait for it.
