### ISSUE TITLE
[Improvement] Remove embedded mode support in Kyuubi Hive JDBC driver

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2616]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In embedded mode, Kyuubi Hive JDBC driver will create a `EmbeddedThriftBinaryCLIService` instead of connecting to Kyuubi server. 

Currently, the Kyuubi Hive JDBC driver uses embedded mode if host and port absent in JDBC url, e.g.

- `jdbc:hive2:///`
- `jdbc:hive2:///dbName;sess_var_list?hive_conf_list#hive_var_list`

### How should we improve?

The embedded mode makes no sense for Kyuubi.
We should remove the support of embedded mode, and change this behavior to use Kyuubi default host(localhost) and default port(10009) if host and port absent.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaoqingbo** [comment]
please assign this to me

**Comment by pan3793** [comment]
Thanks @jiaoqingbo, assigned
