### ISSUE TITLE
[FlakyTest] support engine alive probe to fast fail on engine broken

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2682]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

- KYUUBI #2102 - support engine alive probe to fast fail on engine broken *** FAILED ***
  1644 was not greater than 3000 (KyuubiOperationPerConnectionSuite.scala:253)

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @turboFei

**Comment by wForget** [comment]
Duplicate of #2594

**Comment by turboFei** [comment]
ack
