### ISSUE TITLE
[Improvement] Add Datasource V2 commands to Authz module

### ISSUE THREAD

**Issue by minyk** [apache/incubator-kyuubi#2693]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

PR #2675 introduces some V2 commands, but there are missing commands like `CreateV2Table` or `SetTableProperties`. So we add these commands first, then add other third-party commands from `Iceberg` or `Delta.io`.

### How should we improve?

Add V2 commands to `PrivilegesBuilder` like V1s. Some minor commands are ignored like V1 cases.
Added commands are in these files:
* [org.apache.spark.sql.catalyst.plans.logical.v2Commands.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2Commands.scala)
* [org.apache.spark.sql.catalyst.plans.logical.v2AlterTableCommands.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2AlterTableCommands.scala)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by minyk** [comment]
I'm almost done: https://github.com/minyk/incubator-kyuubi/commit/2a0367ed2f8ec5ea81b93a03ea70c2fd606bd8cc and trying to make some unit tests for DSv2 commands.

**Comment by yaooqinn** [comment]
yes

> Can I make V2 table(except Iceberg) with a query? I'm trying with parquet like current tests but it makes only v1 tables.

**Comment by bowenliang123** [comment]
Shall we consider close this issue?
since closed `#3424 [FEATURE] [AUTHZ] Access privilege checks for namespaces and tables of DatasourceV2` may have covered major parts of commands in DataSource v2 for table and namespaces, and #3515 closed for supporting iceberg commands.

**Comment by minyk** [comment]
@bowenliang123 thx for great work. I think we have no problem to close this issue.

**Comment by yaooqinn** [comment]
thanks @minyk @bowenliang123

**Comment by bowenliang123** [comment]
Thanks. And as for #3424,  it covered only major parts of V2 commands for namespaces and tables, ( and it is also the reason that I didn't reuse this issue). So there's still some work to improve support for other v2 commands.
