### ISSUE TITLE
[FEATURE] Implement dedicated set/get catalog/database operators

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2721]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, we implement  `KyuubiConnection#setSchema` and `KyuubiConnection#getSchema` by using SQL `use <database>`/`SELECT current_database()`, and does not implement `KyuubiConnection#setCatalog` and `KyuubiConnection#getCatalog`, it's ambiguous in some scenarios.

For instance, in Spark, if we have a default catalog `spark_default`, which has a database `db1`, and have another catalog `iceberg` which has a database `db2`. Then `KyuubiConnection#setSchema("iceberg")` will change the current catalog to `iceberg` rather than throw exception.

### Motivation

Create dedicated operators to implement the following JDBC API.

```
KyuubiConnection#setCatalog
KyuubiConnection#getCatalog
KyuubiConnection#setSchema
KyuubiConnection#getSchema
```

### Describe the solution

On Kyuubi server side,

`SetCurrentCatalog extends KyuubiOperation` encodes as
`TExecuteStatementReq` with `conf = Map("kyuubi.operation.set.current.catalog" -> <catalog>)`

`GetCurrentCatalog extends KyuubiOperation` encodes as
`TExecuteStatementReq` with `conf = Map("kyuubi.operation.get.current.catalog" -> "")`

`SetCurrentDatabase extends KyuubiOperation` encodes as
`TExecuteStatementReq` with `conf = Map("kyuubi.operation.set.current.database" -> <catalog>)`

`GetCurrentDatabase extends KyuubiOperation` encodes as
`TExecuteStatementReq` with `conf = Map("kyuubi.operation.get.current.database" -> "")`

On engine side, check `TExecuteStatementReq.conf` and decode it as a dedicated set/get catalog/database operator

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
I am interested in implementing it, can you assign me?
