### ISSUE TITLE
Upgrade Jackson 2.13.3

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2736]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/FasterXML/jackson-databind/issues/2816
https://github.com/FasterXML/jackson-databind/issues/3446

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaoqingbo** [comment]
please assgin to me
