### ISSUE TITLE
Remove binary files from source release

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2748]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

#2475 added a `test-funcation.jar` for UT, it must be part of source release otherwise can not pass UT. But it violate the ASF release policy, source release can not bundle binary files.

### How should we improve?

We should remove the unexpected binary files from source release.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @iodone @turboFei @ulysses-you

**Comment by ulysses-you** [comment]
it seems we can delete this jar, that pr generates the class dynamically.

**Comment by turboFei** [comment]
> it seems we can delete this jar, that pr generates the class dynamically.
+1
