### ISSUE TITLE
[FEATURE] Support Spark SQL lineage plugin

### ISSUE THREAD

**Issue by zhaomin1423** [apache/incubator-kyuubi#2757]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support Spark SQL lineage

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
may be similar: #2282

**Comment by zhaomin1423** [comment]
> may be similar: #2282

Thanks, close it.
