### ISSUE TITLE
Yarn accepts a application that varies its resource constraints

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#278]
**Describe the bug**

When an engine varies YARN's resource constraints, sometimes it does not reject the application directly but responses a msg in diagnosis like,
```logtalk
[Tue Jan 12 14:08:19 +0800 2021] Application is added to the scheduler and is not yet activated. 

Queue's AM resource limit exceeded. 

 Details : AM Partition = abcdefg;

 AM Resource Request = <memory:2048, vCores:1>; Queue Resource Limit for AM = <memory:3072, vCores:1>;

 User AM Resource Limit of the queue = <memory:3072, vCores:1>; 

Queue AM Resource Usage = <memory:1536, vCores:2>;
```

this will lead to a Kyuubi session fail with a timeout exception and no errors feed back to end-users.

1. We shall fail fast with certain yarn diagnoses errors
2. the diagnoses errors shall be delivered to the end-users
3. How many of these errors are?

**To Reproduce**
1. Configurations
2. Environments
3. Operations

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yaooqinn** [comment]
cc @pan3793 can you take a look at this?

**Comment by pan3793** [comment]
Seems we should enhance the parser logic of job output logs and extract the key information then feedback to beeline.
