### ISSUE TITLE
[Bug] Fix KyuubiDataSource#getConnection

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2781]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

The implementation ignores `username` and `password`, it's does not make sense.
```
public class KyuubiDataSource implements SQLDataSource {

  @Override
  public Connection getConnection(String username, String password) throws SQLException {
    try {
      return new KyuubiConnection("", null);
    } catch (Exception ex) {
      throw new SQLException("Error in getting HiveConnection", ex);
    }
  }
}
```

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
@pan3793 I would like to take this.

**Comment by pan3793** [comment]
Thanks, assigned
