### ISSUE TITLE
[Improvement] Decouple Kyuubi Hive JDBC from Hive Serde

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#2782]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, Kyuubi Hive JDBC will convert the result from thrift type to Hive type first, then use Hive Serde to deserialize it to Java type.

### How should we improve?

Convert the data from thrift type to Java type directly, and remove `hive-serde` dependencies in Kyuubi Hive JDBC module.

Ref: https://github.com/apache/spark/pull/36373

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jiaoqingbo** [comment]
I would like to take this

**Comment by pan3793** [comment]
@jiaoqingbo, you don't need to be assigned to work on an issue. Feel free to open a pull request for it.

We avoid assigning issues because it prevents things from getting fixed more often than it helps people coordinate. It's not uncommon for someone to think they'll have time and never get to an issue and having it assigned deters other people from working on it (which is the point). And we almost never see people working on the same thing at the same time.
