### ISSUE TITLE
[FEATURE] Customer behavior audit - forbid to upload local files

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#2801]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We should forbid the customer to upload local files and throw exception if there is any extra local file involved in the engine.

Such as `spark.files=/etc/security/keytabs/kyuubi.keytab`.

### Motivation

It is not security for kyuubi server.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
cc @yaooqinn @ulysses-you @pan3793

**Comment by ulysses-you** [comment]
I'm fine with it as a configurable feature
