### ISSUE TITLE
[Bug] kyuubi cannot trigger SparkListener onApplicationEnd event

### ISSUE THREAD

**Issue by Narcasserun** [apache/incubator-kyuubi#2885]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I added listener conf and --jars to kyuubi's submit, and neither the writing to hdfs nor print is triggered when onApplicationEnd

### Affects Version(s)

1.5.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhouyifan279** [comment]
Can you provide more details? Such as your listener code in brief, KyuubiSparkSQLEngine submit command and KyuubiSparkSQLEngine logs.
