### ISSUE TITLE
[DOCS] Update the number of new committers in MATURITY.md

### ISSUE THREAD

**Issue by aajisaka** [apache/incubator-kyuubi#2905]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

> The community has elected 0 new PPMC members and 2 new committers during incubation, based on meritocracy.

Currently there are more newly added committers during incubation. Maybe 5?

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ulysses-you** [comment]
thank you @aajisaka  for the reminder ! will update it

**Comment by aajisaka** [comment]
Thank you @ulysses-you
