### ISSUE TITLE
[DOCS] The option to specify the Spark version is outdated

### ISSUE THREAD

**Issue by aajisaka** [apache/incubator-kyuubi#2906]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

https://kyuubi.apache.org/developer-tools.html

Since v1.1.0, Kyuubi support building with different Spark profiles,

Profile | Default  | Since
--- | --- | --- 
-Pspark-3.0 | Yes | 1.0.0
-Pspark-3.1 | No | 1.1.0

### Affects Version(s)

master/1.5.2

### Improving the documentation

`-Pspark-3.2` option is also available and looks like it is default in version 1.5.2.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Thanks, the document is outdated, we definitely need to update it.

**Comment by pan3793** [comment]
Fixed by https://github.com/apache/incubator-kyuubi-website/commit/a70d771b8825a8f0a6a2a3c268f7e50a30580a2d
