### ISSUE TITLE
[Bug] KyuubiBeeline cannot get correct zookeeper connection url

### ISSUE THREAD

**Issue by AdobeStu** [apache/incubator-kyuubi#2940]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When I use kyuubi beeline to connect some HA servers like hiveserver2, it will always "connect to" the first host in each line even if I didn't install Kyuubi in the first host. But actually,  it is not a correct connection sometimes. JDBC connected to another host in fact. 

A sample code as following:

`beeline> !connect jdbc:hive2://host1:2181,host2:2181,host3:2181/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;
Connecting to jdbc:hive2://host1:2181,host2:2181,host3:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;
Enter username for jdbc:hive2://host1:2181,host2:2181,host3:2181/:
Enter password for jdbc:hive2://host1:2181,host2:2181,host3:2181/:
Connected to: Apache Hive (version 3.1.0.3.1.0.0-78)
Driver: Kyuubi Project Hive JDBC Client (version 1.5.1-incubating)
0: jdbc:hive2://host1>`

### Affects Version(s)

1.5.1

**Comment by wForget** [comment]
![image](https://user-images.githubusercontent.com/17894939/175475556-1623bc25-a385-40bd-bc47-7d1ebcdefe9f.png)
Do you mean `host1` is always shown here?

**Comment by AdobeStu** [comment]
> ![image](https://user-images.githubusercontent.com/17894939/175475556-1623bc25-a385-40bd-bc47-7d1ebcdefe9f.png) Do you mean `host1` is always shown here?

Yes. Actually I found that Kyuubi use hive beeline to do this. Maybe this issue need to be solved in Hive source code.

**Comment by wForget** [comment]
> Yes. Actually I found that Kyuubi use hive beeline to do this. Maybe this issue need to be solved in Hive source code.

This is the connection url substring, not the kyuubi server host.

**Comment by AdobeStu** [comment]
> > Yes. Actually I found that Kyuubi use hive beeline to do this. Maybe this issue need to be solved in Hive source code.
> 
> This is the connection url substring, not the kyuubi server host.
> 
> ![image](https://user-images.githubusercontent.com/17894939/175478733-4c8a1d13-ba86-4333-bcf7-3359ee77cc1d.png)

You're right. However, in my opinion,  it is not suitable for zookeeper connection url. The substring contributes to help user know which host has connected from the begining.
