### ISSUE TITLE
[FEATURE]   EOL Support for Spark 3.0

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2974]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

this ticket aims to drop support for spark 3.0 from compiling/building and test.

Following the discussion on dev list https://lists.apache.org/thread/3mw8zz9r0tzg2dpj6717xy59610bhkp4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by huage1994** [comment]
hi @yaooqinn , I'm Interested in this ticket and willing to submit a PR~

**Comment by yaooqinn** [comment]
thanks @huage1994
