### ISSUE TITLE
[Improvement] Refactor TPCDS configurations using SparkConfParser

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#2984]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In #2882, we implemented SparkConfParser for parsing spark connector configurations, we need to use SparkConfParser to refactor  all TPCDS configurations.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Kwafoor** [comment]
Yes I am willing to submit a PR!

**Comment by wForget** [comment]
> I want to implement it please assign me

Thanks, assigned.
