### ISSUE TITLE
[Improvement] Prompt configuration when starting engine timeout

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#2985]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Now Spark Engine start timeout, usually in the YARN UI will be prompted configuration, but the user see is the server throws an exception without prompting configuration.

https://github.com/apache/incubator-kyuubi/blob/3bc299d01e1399d6e82cad00419b1c647f9c1915/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/SparkSQLEngine.scala#L270-L272

https://github.com/apache/incubator-kyuubi/blob/3bc299d01e1399d6e82cad00419b1c647f9c1915/kyuubi-server/src/main/scala/org/apache/kyuubi/engine/EngineRef.scala#L208-L210

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mattshma** [comment]
I want to implement it please assign me

**Comment by cxzl25** [comment]
> I want to implement it please assign me

Thanks, assigned.
