### ISSUE TITLE
Bump prometheus from 0.14.1 to 0.16.0

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3008]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/prometheus/client_java/releases/tag/parent-0.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
cc @lightning-L

**Comment by turboFei** [comment]
@xinsun6 would you like to help take this one?

**Comment by xinsun6** [comment]
Sure

**Comment by pan3793** [comment]
Fixed by #3097
