### ISSUE TITLE
[Bug] `bin/beeline` without `-u` exits unexpectedly

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#3030]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

```
bin/beeline
Warn: Not find kyuubi environment file /Users/kentyao/incubator-kyuubi/dist/conf/kyuubi-env.sh, using default ones...
org.apache.hive.beeline.BeeLine.defaultBeelineConnect()
```

the command above exits with no reason whereas `bin/beeline -u 'jdbc:hive2://localhost:10009/'` works properly

### Affects Version(s)

master

### Kyuubi Server Log Output

```logtalk
not related.
```

### Kyuubi Engine Log Output

```logtalk
not related.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
cc @turboFei

**Comment by yaooqinn** [comment]
also cc @pan3793 @jiaoqingbo

**Comment by turboFei** [comment]
seems related to #2478

**Comment by jiaoqingbo** [comment]
KyuubiBeeLine.java Line 154 
connSuccessful = (boolean) defaultBeelineConnectMethod.invoke(this);
should be changed to 
connSuccessful = (boolean) defaultBeelineConnectMethod.invoke(this,cl);

**Comment by jiaoqingbo** [comment]
I will fix this problem
