### ISSUE TITLE
[Subtask] Connectors for Spark SQL Query Engine -> Flink Table Store

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-kyuubi#3067]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

[Flink Table Store](https://nightlies.apache.org/flink/flink-table-store-docs-release-0.1) is a unified streaming and batch store for building dynamic tables on Apache Flink. It is designed to be the best connector to Flink as the storage for streaming warehouse. The document how to use connectors for Spark SQL query engine to connect Flink Table Store should support.

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/3059

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by deadwind4** [comment]
I would like to take this.

**Comment by yaooqinn** [comment]
thanks, @deadwind4

**Comment by huage1994** [comment]
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
> 
> ### Search before asking
> * [x]  I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.
> 
> ### Describe the subtask
> [Flink Table Store](https://nightlies.apache.org/flink/flink-table-store-docs-release-0.1) is a unified streaming and batch store for building dynamic tables on Apache Flink. It is designed to be the best connector to Flink as the storage for streaming warehouse. The document how to use connectors for Spark SQL query engine to connect Flink Table Store should support.
> 
> ### Parent issue
> #3059
> 
> ### Are you willing to submit PR?
> * [x]  Yes I am willing to submit a PR!

Hi @SteNicholas   ,I‘d like to submit a PR!

**Comment by SteNicholas** [comment]
@huage1994, assigned to you. Go ahead to contribute the document.
