### ISSUE TITLE
[FEATURE] Support CostMode for PlanOnlyStatement

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#3128]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

I want to support cost mode for PlanOnlyStatement.

### Motivation

Show the statistics of optimizedPlan.

### Describe the solution

Add `OPTIMIZE_WITH_STATS` plan mode

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Kwafoor** [comment]
I want to implement it please assign me.

**Comment by wForget** [comment]
> I want to implement it please assign me.

Thanks, assigned.
