### ISSUE TITLE
Bump gRPC from 1.47.0 to 1.48.0

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3135]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/grpc/grpc-java/releases/tag/v1.48.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ParisaTork** [comment]
Happy to do this for you, if you'd like?

**Comment by pan3793** [comment]
Feel free to open PR :)

**Comment by ParisaTork** [comment]
Thanks @pan3793 - the [PR](https://github.com/apache/incubator-kyuubi/pull/3188) is ready :)
