### ISSUE TITLE
[Improvement] Change Map to a case class ApplicationInfo as the application info holder

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#3136]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Change Map to a case class ApplicationInfo as the application info holder so the caller side can get info easily and stable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
PR title: Change Map to a case class ApplicationInfo as the application info holder

PR desc: Change Map to a case class ApplicationInfo as the application info holder so the caller side can get info easily and stable.
