### ISSUE TITLE
Bump log4j from 2.17.2 to 2.18.0

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3145]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

- https://logging.apache.org/log4j/2.x/changes-report.html#a2.18.0
- https://issues.apache.org/jira/projects/LOG4J2/versions/12351152

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ParisaTork** [comment]
Happy to do this for you, if you'd like?

**Comment by pan3793** [comment]
Feel free to open PR :)

**Comment by ParisaTork** [comment]
Thanks @pan3793 - here's the [PR](https://github.com/apache/incubator-kyuubi/pull/3187) :)
