### ISSUE TITLE
[KYUUBI-3169][SUB-TASK] Expose rest rpc metrics

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3156]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Sub-task of #3169 
Expose the metrics likes:

```
kyuubi.rest.connection.opend
kyuubi.rest.connection.failed
kyuubi.rest.connection.total
kyuubi.rest.connection.${method}.opened
kyuubi.rest.connection.${method}.failed
kyuubi.rest.connection.${method}.total
```
The method value could be one of the following: get, post, put, delete

### Motivation

monitor the rest rpc

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by turboFei** [comment]
cc @yaooqinn

**Comment by yaooqinn** [comment]
only rest，how about the rest？

**Comment by turboFei** [comment]
> kyuubi.rest.connection.opend

Do you mean `kyuubi.rest.opend` instead of `kyuubi.rest.connection.opend`?

**Comment by yaooqinn** [comment]
oh.. i mean only recording the REST frontends? what about the rest frontends

**Comment by turboFei** [comment]
The rest frontends seems special, because it is not interactive connection.


and now there is metrics(THRIFT_HTTP_CONN) for KyuubiTHttpFrontendService.

**Comment by yaooqinn** [comment]
we need an umbrella then to support all of them, not just for rest, wdyt?

**Comment by turboFei** [comment]
> we need an umbrella then to support all of them, not just for rest, wdyt?


Agree with that, will raise an umbrella ticket.

**Comment by yaooqinn** [comment]
we can also check apache/hive for referecnes

**Comment by lightning-L** [comment]
Reference:
https://github.com/apache/hive/blob/9ad5a0b28b136521ded27b4b5418f61b610da788/service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java#L241
https://github.com/apache/hive/blob/7b3ecf617a6d46f48a3b6f77e0339fd4ad95a420/itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHs2ConnectionMetricsHttp.java
