### ISSUE TITLE
[DOCS] logging page is out of date due to log4j1 -> log4j2

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#3157]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

https://kyuubi.readthedocs.io/en/latest/monitor/logging.html

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zwangsheng** [comment]
I'm willing to fix it. Please assign it to me
