### ISSUE TITLE
[Subtask] Expose thrift binary connection metrics #3156

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3170]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

expose connection metrics for thrift binary connection.

### Parent issue

#3169 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lightning-L** [comment]
reference: https://github.com/apache/hive/blob/9ad5a0b28b136521ded27b4b5418f61b610da788/service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
