### ISSUE TITLE
[FEATURE] Support applying Row-level Filter policies for DatasourceV2 in Authz module

### ISSUE THREAD

**Issue by bowenliang123** [apache/incubator-kyuubi#3186]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Support DataSourceV2Relation to apply applying Row-level Filter policies on Icerberg tables.

Recently we are trying to applying Ranger's row-level filters on Iceberg tables via AuthZ plugin in Spark 3.3.'

We realieze `RuleApplyRowFilterAndDataMasking` in AuthZ currently applys row-level filters correctly on both `HiveTableRelation` fro Hive tables and `LogicalRelation`, but is not affcecting the execution plan for Iceberg tables.

The main reason is Iceberg table is accssesed via `DataSourceV2Relation` and RuleApplyRowFilterAndDataMasking lack of support for it.

### Motivation

With this feature implemented, 
- iceberg tables and any other tables via DataSourceV2 will be benefit 
- row-fitler policies will be correctly applied and also with the masking policies

### Describe the solution

The suggestion and draft implementation is to identify `DataSourceV2Relation` in `RuleApplyRowFilterAndDataMasking`, and parsing database name and table name in `org.apache.spark.sql.connector.catalog.Table` for the next steps of fetching Ranger policies.

`org.apache.iceberg.spark.source`

Considering an iceberg table `gftest.sampleice`, with an row-level filter as `id='1'`.

SQL：
`EXPLAIN EXTENDED select *from gftest.sampleice limit 5;`

Current Execution Plan (1.6.0-SNAPSHOT on master)：
```
== Parsed Logical Plan ==
'GlobalLimit 5
+- 'LocalLimit 5
   +- 'Project [*]
      +- 'UnresolvedRelation [gftest, sampleice], [], false

== Analyzed Logical Plan ==
id: bigint, data: string
GlobalLimit 5
+- LocalLimit 5
   +- Project [id#13332L, data#13333]
      +- SubqueryAlias spark_catalog.gftest.sampleice
         +- RelationV2[id#13332L, data#13333] spark_catalog.gftest.sampleice

== Optimized Logical Plan ==
GlobalLimit 5
+- LocalLimit 5
   +- RelationV2[id#13332L, data#13333] spark_catalog.gftest.sampleice

== Physical Plan ==
CollectLimit 5
+- *(1) ColumnarToRow
   +- BatchScan[id#13332L, data#13333] spark_catalog.gftest.sampleice [filters=] RuntimeFilters: []

```

Expected Execution Plan with draft implementation:
```
== Parsed Logical Plan ==
'GlobalLimit 5
+- 'LocalLimit 5
   +- 'Project [*]
      +- 'UnresolvedRelation [gftest, sampleice], [], false

== Analyzed Logical Plan ==
id: bigint, data: string
GlobalLimit 5
+- LocalLimit 5
   +- Project [id#142L, data#143]
      +- SubqueryAlias spark_catalog.gftest.sampleice
         +- Project [id#142L, data#143]
            +- Filter (id#142L = cast(1 as bigint))
               +- RowFilterAndDataMaskingMarker
                  +- RelationV2[id#142L, data#143] spark_catalog.gftest.sampleice

== Optimized Logical Plan ==
GlobalLimit 5
+- LocalLimit 5
   +- Filter (isnotnull(id#142L) AND (id#142L = 1))
      +- RelationV2[id#142L, data#143] spark_catalog.gftest.sampleice

== Physical Plan ==
CollectLimit 5
+- *(1) Filter (isnotnull(id#142L) AND (id#142L = 1))
   +- *(1) ColumnarToRow
      +- BatchScan[id#142L, data#143] spark_catalog.gftest.sampleice [filters=id IS NOT NULL, id = 1] RuntimeFilters: []
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
@bowenliang123 thanks for driving this feature.

**Comment by bowenliang123** [comment]
How to link the PR https://github.com/apache/incubator-kyuubi/pull/3197 to this issue?

**Comment by yaooqinn** [comment]
the prefix `[KYUUBI #XXX]` in the PR title will be used to automatically link and close this issue during merging.

**Comment by luoyedeyi** [comment]
If the custom catalog name is presented, such as iceberg.gftest.sampleice , this rule will work?

**Comment by bowenliang123** [comment]
> If the custom catalog name is presented such as iceberg.gftest.sampleice , this rule will work?

Not fully tested but it supposed to work fine, since current implementation rely on `identifier: Option[Identifier]` of `DataSourceV2Relation`. The identifier itself ` Identifies an object in a catalog` (refer to Spark code base) which is a concept inside the catalog.

In suggested case, session catalog `spark_catalog` was used as it works for both Iceberg and non-Iceberg tables.(<https://iceberg.apache.org/docs/latest/spark-configuration/#replacing-the-session-catalog>)

Currently authorization for all the catalogs are relied on the same singleton of Ranger Plugin and the same Ranger policy. For further implements of Authz module, I suggest to change to use different plugin and policies for each catalog.

**Comment by yaooqinn** [comment]
does ranger policy support the catalog field? or support creating a policy with a dot-separated database, for example, a database/namespace named `abc.efg` in Spark SQL?

**Comment by bowenliang123** [comment]
> does ranger policy support the catalog field? or support creating a policy with a dot-separated database, for example, a database/namespace named `abc.efg` in Spark SQL?

It depends on each ranger service type. For Hive service type, only `database`-`table`. For Presto(and Trino since 2.3.0), `catalog`-`database`-`table`. Currently ranger lacks of direct support for Spark engine in policy definition.

In our planned senarios, we applied all the access/masking/rowfilter policies in Hive type serivce. As we mix usings Hive/Iceberg tables in one session catalog with one Hive metastore. And the tables with same policies will be shared with HiveServer2, Kyuubi and Trino (in Trino plugin, use chaining plugin feature or customized version to chain Hive policies and then Trino's).

**Comment by yaooqinn** [comment]
maybe it's ok to reuse hive service with a database field containing one or more dots?

**Comment by bowenliang123** [comment]
> maybe it's ok to reuse hive service with a database field containing one or more dots?

Your suggestion is a good way to apply.
But I am afraid that it will disturbance the hiveserver2 plugin's actions and puzzled it to use the database field in convention way like `custom_catalog.a`. And also in ranger admin web, it will lookup resource by the policy definition in Hive policies with Hive driver to Hiveserver which will cause warnings.

**Comment by bowenliang123** [comment]
> maybe it's ok to reuse hive service with a database field containing one or more dots?
> 
> if it is an HMS based table, for example, 'spark_catalog.a.b', a policy would have `a` as database, and `b` as table; for other catalogs, for example, 'custom_catalog.a.b', a policy would have `custom_catalog.a` as database, and `b` as table;

Your suggestion is a good way to apply.
But I am afraid that it will disturbance the hiveserver2 plugin's actions and puzzled it to use the database field in convention way like custom_catalog.a. And also in ranger admin web, it will lookup resource by the policy definition in Hive policies with Hive driver to Hiveserver which will cause warnings.

**Comment by yaooqinn** [comment]
> But I am afraid that it will disturbance the hiveserver2 plugin's actions and puzzled it to use the database field in convention way like custom_catalog.a

for ranger plugins, I guess it's just a search key for a policy, whether matches or not, maybe not a big deal?

**Comment by rameeshm** [comment]
@bowenliang123  does this row-level filter can be used in context with Apache Iceberg REST Catalog API https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml?
