### ISSUE TITLE
[Improvement] The killEngine button should not show in KyuubiEngineTab of SparkHistoryServer

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#3220]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The killEngine button should not show in KyuubiEngineTab of SparkHistoryServer.

![image](https://user-images.githubusercontent.com/17894939/184280061-08e16505-77c4-4a9e-acf9-b39015402ce2.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
make sense!
