### ISSUE TITLE
[DOCS] `Building a Runnable Distribution` needs to be updated

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#3241]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Which parts of the documentation do you think need improvement?

https://kyuubi.readthedocs.io/en/latest/develop_tools/distribution.html

- Fix [Kyuubi Release Page](https://github.com/apache/incubator-kyuubi/releases) to correct download page
- Update `/build/dist --help` hints
- Fix the name kyuubi-{version}-bin-custom-name.tgz
- Fix the name kyuubi-{version}-bin.tgz

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zwangsheng** [comment]
I'm willing to improve this part of doc.
