### ISSUE TITLE
[Subtask][KPIP-5] Init frontend framework

### ISSUE THREAD

**Issue by tongwl** [apache/incubator-kyuubi#3249]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

This is a subtask of KPIP-5 https://github.com/apache/incubator-kyuubi/issues/3248

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/3248

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Closed by #3250
