### ISSUE TITLE
[FEATURE] support table/column lineage

### ISSUE THREAD

**Issue by melin** [apache/incubator-kyuubi#3284]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

ref: https://github.com/maropu/spark-sql-flow-plugin

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhaomin1423** [comment]
https://github.com/apache/incubator-kyuubi/pull/3185#issue-1329564580
