### ISSUE TITLE
[Improvement] Make the behavior of close session after disconnect configurable

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#3339]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently the kyuubi server closes the session after the client disconnects, I want to make it configurable so we can restore the connection.

### How should we improve?

Add a config like hive's:
```
HIVE_SERVER2_CLOSE_SESSION_ON_DISCONNECT("hive.server2.close.session.on.disconnect", true,
  "Session will be closed when connection is closed. Set this to false to have session outlive its parent connection.")
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/issues/3112 I will close this, please link your PR to the former one.
