### ISSUE TITLE
[Bug] Backport HIVE-20583: Use canonical hostname only for kerberos auth in HiveConnection

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#3352]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

In https://github.com/apache/incubator-kyuubi/pull/2560 , canonical-ize the connection host parameters.
```java
host = Utils.getCanonicalHostName(connParams.getHost());
```

[HIVE-17218](https://issues.apache.org/jira/browse/HIVE-17218): Canonical-ize hostnames for Hive metastore, and HS2 servers

This may have the problem mentioned by JIRA

[HIVE-20583](https://issues.apache.org/jira/browse/HIVE-20583): Use canonical hostname only for kerberos auth in HiveConnection

### Affects Version(s)

master/1.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cxzl25** [comment]
There may also be problems with using `getCanonicalHostName` in the kerberos environment.
But this patch has not been merged.

[HIVE-21899](https://issues.apache.org/jira/browse/HIVE-21899) Utils.getCanonicalHostName() may return IP address depending on DNS infra

**Comment by pan3793** [comment]
cc @zhouyifan279
