### ISSUE TITLE
[FEATURE] permission control needs to support views

### ISSUE THREAD

**Issue by lianneli** [apache/incubator-kyuubi#3397]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

View is also supported in Hive and other Apache family members, but it is not supportte in `KyuubiRangerExtension` now[](url)

### Describe the solution

I modify the extension related code by adding a check layer in `CheckRule`, in which the View Logical Plans are not "optimized" . 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/commit/1989e4c7934d7f4d80f488fd0bf9e5adbda5ed9c does it work after this?

**Comment by lianneli** [comment]
> [1989e4c](https://github.com/apache/incubator-kyuubi/commit/1989e4c7934d7f4d80f488fd0bf9e5adbda5ed9c) does it work after this?

I readed the related codes in version 1.6 just now, and found that this need has been satisfied. the solutions are different between us, but both can meet the target. Here is my idea of solutions:
1.  add an extension in `injectCheckRule`. In this extension, search logical plan tree:
   a. if nodes contains Views , run the `RuleAuthorization.checkPrivileges(spark, plan)`, and add `KYUUBI_AUTHZ_TAG` to all the child table node if permission allowed. Those node with `KYUUBI_AUTHZ_TAG` will not check permissions again in `RuleAuthorization`.
   b. otherwise, let it go and this query will check permissions in `RuleAuthorization`.

this solution need modify `PrivilegesBuilder` at the sametime.

**Comment by yaooqinn** [comment]
yes, your solution sounds also like a good alternative. If something wrong might be reported in the future for the current way, it is worth a shot. but now let's keep it AS-IS.

**Comment by lianneli** [comment]
> yes, your solution sounds also like a good alternative. If something wrong might be reported in the future for the current way, it is worth a shot. but now let's keep it AS-IS.

Yes, of course，it‘s just an idea sharing. The solutions now is logical completed, and I believe it will run well.
