### ISSUE TITLE
[FEATURE] Support to delete the engine node from engine discovery space with AdminResource

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3410]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

 Support to delete the engine node from engine discovery space with AdminResource

### Motivation

Even now we can delete the engine node with kyuubi-ctl, but it is not a good solution.

1. we can not do it with kyuubi server authentication
2. we can not do it with programming way.

### Describe the solution

We can implement the function in AdminResource and user can call it in restful way.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lightning-L** [comment]
started working on it...
