### ISSUE TITLE
[Subtask] Change default Spark version to 3.3

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3441]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Change default Spark version to 3.3

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/2608

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by goldwater2019** [comment]
Can i submit this PR? And I wandering for how to be a commiter

**Comment by pan3793** [comment]
Of course, PR is welcome.

> And I wandering for how to be a commiter

Please refer [Become A Committer of Apache Kyuubi](https://kyuubi.apache.org/become_committer.html)
