### ISSUE TITLE
[Improvement] [INFRA] The Parent issue attribute of the flaky-test-report template should not have a definite value

### ISSUE THREAD

**Issue by Yikf** [apache/incubator-kyuubi#3447]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The Parent issue attribute of the flaky-test-report template should not have a definite value, currently behavior as follow:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/51110188/189038385-5194efd0-9d5a-45ad-ad71-bf31dfb4c3b4.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
it's on purpose, #1733 is a dedicated umbrella to track flaky tests.
