### ISSUE TITLE
[Improvement] Implement GetInfo for JDBC engine

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3451]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Follow up #3122

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by selectbook** [comment]
Hello, I would like to contribute in this issue. can i have a try?

**Comment by pan3793** [comment]
Of course, PR is welcome, anytime.
