### ISSUE TITLE
[Improvement] Implement GetInfo for Trino engine

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3452]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Follow up #3122

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Muxsidov** [comment]
I do not understand, what is the issue exactly? Should I Follow up #3122?

**Comment by pan3793** [comment]
#3323 describes the requirements, and part of it is done in #3122.
