### ISSUE TITLE
Bump Jackson from 2.13.3 to 2.13.4

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3460]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Bump Jackson from 2.13.3 to 2.13.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by QianyongY** [comment]
please assgin to me

**Comment by pan3793** [comment]
You don't need to be assigned, please send PR directly.
