### ISSUE TITLE
[Improvement] No interface to set MVN OPTS in the dist script

### ISSUE THREAD

**Issue by baifachuan** [apache/incubator-kyuubi#3462]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Using the 
```
 ./build/dist --tgz
```
command to build the tarball throw Exception:

```
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default) on project kyuubi-parent: Too many files with unapproved license: 1 See RAT report in: /incubator-kyuubi/target/rat.txt -> [Help 1]
```

But no interface to set MVN OPTS : -Drat.skip=true

We need to provide the MVN OPTS interface in the dist script.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
```
./build/dist - Tool for making binary distributions of Kyuubi

Usage:
+------------------------------------------------------------------------------------------------------+
| ./build/dist [--name <custom_name>] [--tgz] [--flink-provided] [--spark-provided] [--hive-provided]  |
|              [--mvn <maven_executable>] <maven build options>                                        |
+------------------------------------------------------------------------------------------------------+
```

For your specific requirements, use `build/dist --tgz -Drat.skip=true`

**Comment by yaooqinn** [comment]
does the official repo produce this error or after your modification? if it is the former, it's a bug that need to be fixed

**Comment by baifachuan** [comment]
@pan3793 Thanks for your replay, @yaooqinn it's not a bug, I miss the introduction.

```
build/dist --tgz -Drat.skip=true
```

It works!

Thanks.
