### ISSUE TITLE
[FEATURE] Provide Hive JDBC Dialect support for Spark/PySpark to connect Kyuubi via JDBC Source

### ISSUE THREAD

**Issue by bowenliang123** [apache/incubator-kyuubi#3487]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently, it is not able to read data correctly from Kyuubi as JDBC Dataframe with either KyuubiHiveDriver or HiveDriver.

As Hive JDBC Dialect is not provided in Spark, Spark will force JdbcRDD to use default JDBC dialect which is quoting column name wrapping in column name to 'col_name' instead of Hive style \`col_name\`. It causes two major unexpected situations:

1. if all the columns of table are in string type, all row data is identical to their column name.
2. if any column has number type, it will failed to convert value to number type with wrong data (the column name).

<img width="882" alt="image" src="https://user-images.githubusercontent.com/1935105/190183045-66e456ea-6e9c-4d8c-ae12-204239d9cd2e.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/1935105/190179710-06bcb8a4-e897-41fe-90ea-4fce0b297641.png">

### Describe the solution

Introduce a spark plugin, 
1. providing Hive JDBC Dialet for jdbc url starting with `jdbc:kyuubi://` or `jdbc:hive2://` , with quoting column names in Hive style as \`col_name\`
2. registing Hive JDBC Dialet  by  executing `JdbcDialects.registerDialect` 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wForget** [comment]
I found this hope it can help you. https://medium.com/@viirya/custom-jdbc-dialect-for-hive-5dbb694cc2bd

**Comment by bowenliang123** [comment]
Yes, likely the same way. And I have draft implementation in hand. My intention is to provide a general client side plugin for both Spark scala user and PySpark.

**Comment by bowenliang123** [comment]
Many thanks to my colleague @jeanlyn from Guangfa Secirities for the detailed investigation in Spark and indispensible help for practicable solution to this problem.

**Comment by pan3793** [comment]
Thanks, @bowenliang123 @jeanlyn @wForget!
