### ISSUE TITLE
[Improvement] Extend JDBC URL to support catalog

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3504]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current JDBC URL pattern is 
```
jdbc:kyuubi://<host>:<port>/<dbName>;<sessionVars>?<kyuubiConfs>#<engineVars>
```
As Kyuubi supports the "catalog" concept, we should extend the current JDBC URL pattern to support it.

### How should we improve?

Option 1:

Trino JDBC URL pattern[1] supports catalog and database, we can extend Kyuubi JDBC URL pattern to

```
jdbc:kyuubi://<host>:<port>/<catalogName>/<dbName>;<sessionVars>?<kyuubiConfs>#<engineVars>
```

For compatibility, if only one part is supplied, we should treat it as `dbName` rather than `catalogName`
```
jdbc:kyuubi://<host>:<port>/<dbName>;<sessionVars>?<kyuubiConfs>#<engineVars>
```

Option 2:

Add a new session variable "catalog" in `<sessionVars>` part, e.g.
```
jdbc:kyuubi://localhost:10009/sf1;catalog=tpcds
```

PostgreSQL uses a similar pattern(PostgreSQL uses `<database>.<schema>.<table>` to locate table)

```
jdbc:postgresql://localhost:5432/<database>?currentSchema=<schema>
```

[1] https://trino.io/docs/current/client/jdbc.html#connecting
[2] https://jdbc.postgresql.org/documentation/use/

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
cc @cxzl25 @yaooqinn @ulysses-you

**Comment by turboFei** [comment]
+1 for option 1
