### ISSUE TITLE
[Improvement] bin/kyuubi stop should check pid after force kill

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#3544]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

`kill -9 <pid>` can not guarantee process shutdown immediately, we should check and wait until pid disappeared before returning.

Otherwise, `bin/kyuubi restart` may fail w/ bind failed.

![image](https://user-images.githubusercontent.com/26535726/191907295-7eb1cb38-293b-4bb4-949d-eba0e5734f21.png)

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by asagjj** [comment]
@hddong Hello, I would like to contribute in this issue. can i have a try?

**Comment by pan3793** [comment]
Of course, PR is welcome, anytime :)

**Comment by hddong** [comment]
Welcome and assigned to you. @asagjj
