### ISSUE TITLE
[TEST] Fix Spark nightly build

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#3671]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [ ] Fix flaky tests.
- [X] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

1. `KYUUBI #1059: Plan only operations`
```
"Error operating PlanOnlyStatement: org.apache.spark.sql.AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `t` cannot be found. Verify the spelling and correctness of the schema and catalog. ..."
did not contain "Table or view not found" (SparkQueryTests.scala:485)
```

2. `set session conf - wrong database`
```
"[SCHEMA_NOT_FOUND] The schema `default2` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a catalog, verify the current_schema() output, or qualify the name with the correct catalog.
To tolerate the error on drop use DROP SCHEMA IF EXISTS." 
did not contain "Database 'default2' not found"
```

more  details see https://github.com/apache/spark/pull/37887

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by ulysses-you** [comment]
cc @bowenliang123 if you are interested in

**Comment by bowenliang123** [comment]
Let me have a check.
