### ISSUE TITLE
[Improvement] The `authentication.kerberos.principal` value posted to zk should keep the original value

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#3686]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Hive HiveServer2

https://github.com/apache/hive/blob/f3e3c91b882c442ffd872de998f8db40f7bff162/service/src/java/org/apache/hive/service/server/HiveServer2.java#L564-L566

Kyuubi Server

https://github.com/apache/incubator-kyuubi/blob/c25961ea0271ea38e67e046fc3696605df2958b8/kyuubi-ha/src/main/scala/org/apache/kyuubi/ha/client/zookeeper/ZookeeperDiscoveryClient.scala#L332-L334

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by QianyongY** [comment]
I want to implement it please assign me.
