### ISSUE TITLE
[Bug] Spark engine do not support GetPrimaryKeys operation

### ISSUE THREAD

**Issue by jiaoqingbo** [apache/incubator-kyuubi#3740]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

add GetPrimaryKeys operation in spark egine

### Affects Version(s)

master

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
Does Spark have the primary key concept? And have you checked the STS implementation?

**Comment by jiaoqingbo** [comment]
Sorry I will close this
