### ISSUE TITLE
[TEST] MetadataManagerSuite: - metadata request metrics *** FAILED ***

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#3752]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

https://github.com/apache/incubator-kyuubi/actions/runs/3382522626/jobs/5617532323

```
MetadataManagerSuite:
- retry the metadata store requests
- metadata request metrics *** FAILED ***
  2 did not equal 1 (MetadataManagerSuite.scala:135)
```

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
it should has been resolved?

**Comment by turboFei** [comment]
fixed by https://github.com/apache/incubator-kyuubi/pull/3748
