### ISSUE TITLE
[FEATURE] Can we mix python the same way we mix scala?

### ISSUE THREAD

**Issue by dik111** [apache/incubator-kyuubi#3758]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Compared with Scala, Python is more commonly used by data analysts and bi development engineers. Can we support mixing python, just like mixing scala?

**Comment by pan3793** [comment]
cc @cfmcgrady

**Comment by cfmcgrady** [comment]
PySpark support is coming so :)

![WechatIMG2085](https://user-images.githubusercontent.com/8537877/199713891-3e343de3-f406-4ae1-a524-6e65acedeba5.jpeg)

**Comment by dik111** [comment]
> PySpark support is coming soon :)
> 
> ![WechatIMG2085](https://user-images.githubusercontent.com/8537877/199713891-3e343de3-f406-4ae1-a524-6e65acedeba5.jpeg)

wow,look forward fot it !
