### ISSUE TITLE
[Improvement] Do not show the app Diagnostic for list batch command

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3786]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Do not show the app Diagnostic for list batch command

### How should we improve?

only show the app Diagnostic for get batch command.

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
cc @lightning-L

**Comment by lightning-L** [comment]
Yes, it makes list result hard to read and it is unnecessary because we could get the info by `get `command
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/21362040/200723185-effd162f-b2b5-4d03-bd4a-c4a7382d84d0.png">
