### ISSUE TITLE
[Bug]  Kyuubi Spark Authz plugin can't sync the policy from Apache Ranger

### ISSUE THREAD

**Issue by xiaozhch5** [apache/incubator-kyuubi#3791]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Hello, I used Apache Ranger to control the access policy of the Hadoop cluster, and kyuubi sync the policy of hive. When I config the properties using the instroduction of  "https://kyuubi.apache.org/docs/latest/security/authorization/spark/install.html", some problem arised:
![3fef83d927220022c6819e0a90590d1](https://user-images.githubusercontent.com/46479816/200717467-23b7b2db-8c14-41d2-83cc-9f6ec046aaec.png)
The log shows that, It's not certified by Ranger Admin.

So I changed the code of org.apache.ranger.admin.client.RangerAdminRESTClient, add username and password  to be authenticated by Ranger Admin.

![3bbda584715eddaaaaf566a5c2fa0b3](https://user-images.githubusercontent.com/46479816/200718094-9b688a05-c329-4e81-8d01-2d0374ce2ea7.png)

![8b9dc4ec8eb2e49c3db83508aeac6f3](https://user-images.githubusercontent.com/46479816/200718116-810af69e-9157-4878-a18b-80cd07d0aaf7.png)

Both on client mode and cluster mode, kyuubi spark can successful sync the policy from Ranger Admin.

### Affects Version(s)

1.6.0

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to fix.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
It does not sound like a Kyuubi side issue, and I'm even not sure if it's a bug or caused by the wrong usage. The 401 response indicates that there are some issues with authentication/authorization.

- have you checked the Ranger server log?
- what are your configurations of each component?

**Comment by xiaozhch5** [comment]
> It does not sound like a Kyuubi side issue, and I'm even not sure if it's a bug or caused by the wrong usage. The 401 response indicates that there are some issues with authentication/authorization.
> 
> * have you checked the Ranger server log?
> * what are your configurations of each component?

It may be a configuration isssue in configing Kyuubi Spark AuthZ Plugin.

At presenet, according to the instroduction of the document in "https://kyuubi.apache.org/docs/latest/security/authorization/spark/install.html#ranger-spark-security-xml", the property of 'ranger.plugin.spark.policy.source.impl' is set to 'org.apache.ranger.admin.client.RangerAdminRESTClient'. 

![1667984835900](https://user-images.githubusercontent.com/46479816/200787809-00fb79fa-4f67-4be1-b669-b165f811f39a.png)


When spark sync the hive policy from Ranger Admin, it shoud use the username and password to authenticate the url http://ranger-admin.org:6080.

But by default, if the property of 'ranger.plugin.spark.policy.source.impl' is set to 'org.apache.ranger.admin.client.RangerAdminRESTClient'. It doesn't authenticate with username and password. Therefore, I got the 401 response.

 So, I change some code of 'org.apache.ranger.admin.client.RangerAdminRESTClient', and pass username and password to it so that spark can successful sync the policy from Ranger Admin and pass the authentication of the url of http://ranger-admin.org:6080.

Maybe the instroduction of the document in "https://kyuubi.apache.org/docs/latest/security/authorization/spark/install.html#ranger-spark-security-xml" is not so complete?

**Comment by xiaozhch5** [comment]
full content of ranger-spark-security.xml
```xml
<configuration>
    <property>
        <name>ranger.plugin.spark.service.name</name>
        <value>cluster_hive</value>
        <description>Name of the Ranger service containing policies for this SPARK instance</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.source.impl</name>
        <value>org.apache.ranger.admin.client.RangerAdminRESTClient2</value>
        <description>Class to retrieve policies from the source</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.rest.url</name>
        <value>http://host121:6080</value>
        <description>URL to Ranger Admin</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.rest.url.username</name>
        <value>admin</value>
        <description>username to Ranger Admin</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.rest.url.password</name>
        <value>admin123#</value>
        <description>password to Ranger Admin</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.pollIntervalMs</name>
        <value>30000</value>
        <description>How often to poll for changes in policies?</description>
    </property>
    <property>
        <name>ranger.plugin.spark.policy.cache.dir</name>
        <value>/etc/ranger/cluster_spark/policycache</value>
        <description>Directory where Ranger policies are cached after successful retrieval from the source</description>
    </property>
</configuration>
```

**Comment by pan3793** [comment]
> When spark sync the hive policy from Ranger Admin, it should use the username and password to authenticate ...

WHY IT SHOULD use the username and password?

**Comment by xiaozhch5** [comment]
> > When spark sync the hive policy from Ranger Admin, it should use the username and password to authenticate ...
> 
> WHY IT SHOULD use the username and password?

So that spark can successful sync the policy. Like using curl tool, it's ok to get the policy use the username and password.

![image](https://user-images.githubusercontent.com/46479816/200796053-7390a436-b137-4090-92c1-21d0cb946e1d.png)

But I get nothing without the username and password.

![image](https://user-images.githubusercontent.com/46479816/200796404-c42fd025-ff6d-4a1b-b6d0-700771defa94.png)

**Comment by xiaozhch5** [comment]
> So the key point here is the ranger does not expose the API to setup basic authentication information, then Kyuubi can not do that(maybe we can use reflection but it's may be a dirty way). Then it's not a Kyuubi bug, you'd better to push the Ranger community to expose the new API so that the downstream project can leverage.

Thank you too much for your reply, I will close this issue and raise it  in the Ranger community.

**Comment by xiaozhch5** [comment]
@pan3793 Hello, I test again and put 
```xml
      <property>
      <name>ranger.credential.provider.path</name>
      <value>/etc/ranger/admin/rangeradmin.jceks</value>
    </property>
```
into ranger-spark-security.xml and spark works well to sync policies from ranger admin.

Maybe we can improve the document of "https://kyuubi.apache.org/docs/latest/security/authorization/spark/install.html" and add the property list before to ranger-spark-security.xml.

**Comment by pan3793** [comment]
This configuration seems tightly depends on your environment.

**Comment by risyomei** [comment]
I am having this issue too. Normally Ranger policy will be synced with GSSAPI (Kerberos authentication), not sure if Kyuubi plans to support that.

**Comment by pan3793** [comment]
@risyomei the original reporter are talking about basic authentication but you are talking about GSSAPI(Kerberos) authentication, are you SURE you are meeting the same issue?

**Comment by risyomei** [comment]
Even in a fully-kerberized cluster, we see authz is trying to use simple authentication when accessing the ranger admin and failed with the same error message. 

Therefore, I think there are two ways of resolving this issue:
1. Using the credential store as @xiaozhch5 suggests in the comment (https://github.com/apache/kyuubi/issues/3791#issuecomment-1315249377).
2. Using the Kerberos (GSSAPI) to access the Ranger. <-- That's the thing I am not sure if Kyuubi plans to support.

**Comment by pan3793** [comment]
> ... Using the Kerberos (GSSAPI) to access the Ranger. <-- That's the thing I am not sure if Kyuubi plans to support.

It already done, in Spark client mode.

**Comment by risyomei** [comment]
Thank you very much for your confirmation, that's exactly what I wanted to know.
I was having problem with Spark cluster mode + Kyuubi LDAP Authentication.

Is there any way to use Spark cluster mode + Kyuubi LDAP Authentication + authz at the moment?

**Comment by pan3793** [comment]
I explained the technical details on https://github.com/apache/kyuubi/discussions/3620, it also mentioned some workaround, and approach to support it directly(looking forward volunteer to send PR)

**Comment by risyomei** [comment]
@pan3793 
Thank you very much for the explanation.
Totally answered my question! 🙇

**Comment by isteven-xu** [comment]
I got the same issue like you, but its not working when change some code to add username and password , I repleace the ranger-plugin-common-2.3.0.jar in spark classpath and then also got 401 ,but I test with curl like : curl -v -u admin:admin http://ip:6080/service/plugins/secure/policies/download/spark_service work fine.

**Comment by isteven-xu** [comment]
I change the code and work fine.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/32054226/210937102-e8683685-72d0-46c5-ab81-7da86fac6ee5.png">
