### ISSUE TITLE
[Improvement] Support to execute python language with yarn cluster mode

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3896]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Support to execute python language with yarn cluster mode

<img width="528" alt="image" src="https://user-images.githubusercontent.com/6757692/205447872-692e8b24-3db6-470e-bdb0-7414f08fd7ea.png">

### How should we improve?

Seems need upload pyspark lib when initializing the spark engine.

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
cc @cfmcgrady

**Comment by cfmcgrady** [comment]
cc @bowenliang123

**Comment by turboFei** [comment]
temp workaround
```
--hivevar  spark.yarn.dist.archives=viewfs://apollo-rno/apps/b_stf/spark-3.1.1.0.12.0-bin-ebay.zip#spark_home \
--hivevar spark.yarn.appMasterEnv.SPARK_HOME=spark_home
```

**Comment by bowenliang123** [comment]
> temp workaround
> 
> ```
> --hivevar spark.yarn.dist.archives=hdfs:/path/to/spark.zip#spark_home \
> --hivevar spark.yarn.appMasterEnv.SPARK_HOME=spark_home
> ```
And this must set before switching to python language.

**Comment by turboFei** [comment]
Yes，it is a static conf.

**Comment by turboFei** [comment]
We can add a parameters for spark python language mode, for the spark archive.
so that we can add archive for python mode on need.

If SPARK_HOME is not defined,  invoke SparkContext::addArchive to add archive file and use it as SPARK_HOME.
```
  @Experimental
  def addArchive(path: String): Unit = {
    addFile(path, false, false, isArchive = true)
  }
```

**Comment by bowenliang123** [comment]
> We can add a parameters for spark python language mode, for the spark archive. so that we can add archive for python mode on need.
> 
> If SPARK_HOME is not defined, invoke SparkContext::addArchive to add archive file and use it as SPARK_HOME.
> 
> ```
>   @Experimental
>   def addArchive(path: String): Unit = {
>     addFile(path, false, false, isArchive = true)
>   }
> ```

Sounds good. 
But pyspark also requires Python environment on cluster nodes, whether this `addArchive` can be used for uploading Python interpreter and dependencies as well?

**Comment by turboFei** [comment]
> whether this addArchive can be used for uploading Python interpreter and dependencies

sure
