### ISSUE TITLE
[TEST] KyuubiOperationKubernetesClusterClusterModeSuite: - Spark Cluster Mode On Kubernetes Kyuubi KubernetesApplicationOperation Suite *** FAILED ***  

### ISSUE THREAD

**Issue by turboFei** [apache/incubator-kyuubi#3952]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

```
KyuubiOperationKubernetesClusterClusterModeSuite:
- Check if spark.kubernetes.executor.podNamePrefix is invalid
- Spark Cluster Mode On Kubernetes Kyuubi KubernetesApplicationOperation Suite *** FAILED ***
  failKillResponse._1 was true (SparkOnKubernetesTestsSuite.scala:225)
```
https://github.com/apache/incubator-kyuubi/actions/runs/3650086442/jobs/6165632082
### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by turboFei** [comment]
cc @zwangsheng

**Comment by zwangsheng** [comment]
I'll check this Flaky Test with this #3176 issue together.
