### ISSUE TITLE
[TEST] DockerizedZkServiceDiscoverySuite - distribute lock *** FAILED ***

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#3956]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [ ] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

- distribute lock *** FAILED ***
  lockLatch.await(5000L, MILLISECONDS) was false (DiscoveryClientTests.scala:146)

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by cxzl25** [comment]
duplicate #3920
