### ISSUE TITLE
[Kubernetes]Add Tests for scheduling Kyuubi engines with minikube support

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#444]
### 1. Describe the feature

https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
https://github.com/marketplace/actions/minikube-single-node-kubernetes-action

### 2. Motivation

for Kubernetes support

**Comment by yaooqinn** [comment]
cc @zwangsheng @ulysses-you @pan3793

**Comment by ulysses-you** [comment]
ah, sounds good. it might take some times to test it locally in my laptop.

**Comment by pan3793** [comment]
Should we test with such matrix?
```
matrix:
  kyuubi-server: [local, k8s]
  spark-engine: [local, k8s]
```

**Comment by yaooqinn** [comment]
The tests of the engine module are basically for improving the debugging experience for developers using IDEs.
It's not that necessary for CI
