### ISSUE TITLE
[Bug] kyuubi-server package missing mysql dependency jar

### ISSUE THREAD

**Issue by imperio-wxm** [apache/incubator-kyuubi#4778]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When `kyuubi.metadata.store.jdbc.database.type=MYSQL` is set, kyuubi-server starts to report an error.
```java
Caused by: java.lang.RuntimeException: Failed to load driver class com.mysql.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
```
Log in to the kyuubi-server host to view the dependent jars in the `/opt/kyuubi/jars` directory, and find that the mysql dependency is missing.

In the pom.xml file of kyuubi-server, the scope that mysql depends on is test.
```xml
<dependency>
    <groupId>com.mysql</groupId>
    <artifactId>mysql-connector-j</artifactId>
    <scope>test</scope>
</dependency>
```

And it is known from the parent pom.xml that the mysql jdbc version is `<mysql.jdbc.version>8.0.32</mysql.jdbc.version>`. 
It is more appropriate to replace `com.mysql.jdbc.Driver` with `com.mysql.cj.jdbc.Driver`

### Affects Version(s)

master/1.7.0

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

**Comment by imperio-wxm** [comment]
PR: https://github.com/apache/kyuubi/pull/4779

**Comment by bowenliang123** [comment]
-1.
I think Kyuubi is not shipped with MySql JDBC Driver on purpose.
1. Mysql JDBC driver follows a different license, the GPLv2
2. Mysql support for metadata is an optional feature to Kyuubi server
3. Should not ship with a specific version of Mysql 5 or 8

**Comment by imperio-wxm** [comment]
1. It is strange if mysql is an option, but users cannot work on it. Many people install kyuubi directly through the release package(.tgz), which means need to manually copy the mysql dependency to the jars directory before deploying.

2. And maybe kyuubi officially provides the docker image in the docker hub, does it mean that users who use docker deployment need to package the image themselves? https://github.com/apache/kyuubi-docker

**Comment by bowenliang123** [comment]
As for 1, we must prevent introducing license violation and the dependency  contamination.  "Many people install kyuubi directly through the release package" you mentioned is just not the general case, as for Mysql 5 or 8 users. They will be both confused by the packed Mysql JDBC driver version and detail of it. And again, license issue.
Reply to 2, Docker image is NOT evidence for distributed packages itself, which is only an assemble WITH the distributed tarball.

**Comment by pan3793** [comment]
Please read the [ASF 3RD PARTY LICENSE POLICY](https://www.apache.org/legal/resolved.html#category-x)

In short, projects under ASF are prohibited by LAW from including the MySQL JDBC driver in their binary release artifacts.

**Comment by bowenliang123** [comment]
Closing this issue with discussion and clarification above.
