### ISSUE TITLE
Enable `env:` type configuration in JDBC connection url to switch env settings during engine bootstrap

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#508]
### 1. Describe the feature

Now we set hiveconf/sparkconf/systemconf etc to `sessionConf`, then `env:` prefixed shall go engines environments

**Comment by pan3793** [comment]
Let me take this task.

**Comment by pan3793** [comment]
Have a quick look on SparkThriftServer and HiveServer2 implementation, those two doesn't support set env neither, and beeline and JDBC url doesn't expose the env setting place, the only function of env vars is for variable substitution. In other words, env vars are read only.

To match the HiveServer2 behavior, we need to add the check on `set:env:xxxx` configurations on creating session. And seems `set env:TERM=abc` should handle by Spark itself?
