### ISSUE TITLE
[Improvement] Bump iceberg 1.4.3

### ISSUE THREAD

**Issue by cxzl25** [apache/incubator-kyuubi#6063]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Apache Iceberg 1.4.3
Dec 28, 2023
https://iceberg.apache.org/releases/

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by GGHWS** [comment]
Please assgin to me, thanks.
