### ISSUE TITLE
Hudi support

### ISSUE THREAD

**Issue by zxding** [apache/incubator-kyuubi#703]
Spark thrift server support hudi sql feature, such as insert into, update,delete,merge into grammer;will kyuubi plan to support feature like this?

**Comment by yaooqinn** [comment]
yes. hudi shall work fine with Kyuubi, but we've tested that. are you interested in this?

**Comment by zxding** [comment]
Yes，will have product application using kyuubi ,and I try to add some new grammer feature using kyuubi 0.7 version to support hudi spark sql. If you have already work on this, would you please tell the deadline , so that I can using your code and change my plan. 3q.

**Comment by yaooqinn** [comment]
0.7 is pretty old, have you tried the laster 1.2.0-rc5?

**Comment by zxding** [comment]
Ok，1.2.0 have already support hudi spark sql update and merge into grammer??

**Comment by yaooqinn** [comment]
you are talking about a feature that should be supported by Spark and Hudi's side. If they both do not have any plan to make it work, we will consider adding some extensions

**Comment by zxding** [comment]
If possible ,I wanna to talk about this issue with wechat.I work at hik.

**Comment by yaooqinn** [comment]
yaooqinn

**Comment by lxk000000** [comment]
We have achieved kyuubi support hudi with hudi datasource mode on the spark version 2.4.5. 
Follow-up consideration in version 3.0. Hope to merge these codes

**Comment by yaooqinn** [comment]
that sounds nice. But can you detail what we are going to have in kyuubi? Do we have a design doc for it?
