### ISSUE TITLE
How to configure spark executor pod name prefix?

### ISSUE THREAD

**Issue by cutiechi** [apache/incubator-kyuubi#773]
### 1. Describe the bug

How to configure spark executor pod name prefix?
#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by ulysses-you** [comment]
I think it's the Spark behavior. You can set the related config `spark.kubernetes.executor.podNamePrefix` into `spark-defaults.conf`.

**Comment by cutiechi** [comment]
@ulysses-you Ok, thx
