### ISSUE TITLE
How to disable ha zk?

### ISSUE THREAD

**Issue by cutiechi** [apache/incubator-kyuubi#774]
### 1. Describe the bug
How to disable ha zk? I set kyuubi.ha.enabled=false, but not working

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
Zookeeper (HA mode) is optional for Kyuubi Server but required for Engine.

When a new engine(spark driver) is launched, it will register itself in Zookeeper, then Kyuubi Server knows how to connect to the engine.

**Comment by cutiechi** [comment]
@pan3793 Ok, thx
