### ISSUE TITLE
redesign kyuubi-ctl module 

### ISSUE THREAD

**Issue by timothy65535** [apache/incubator-kyuubi#775]
### 1. Describe the feature

Currently, the kyuubi-ctl module is hard to scale inclusing(add new command, parse the args, the usage for commands), and the order of command line parameters is not user-friendly.

Here is the new design.
- improve the order of command line parameters. the new command line consisting of multiple commands, each command has its own parameters.
    - **OLD**: kyuubi-ctl <create|get|delete|list> <server|engine> [options]
    - **NEW**: kyuubi-ctl <server|engine> <create|get|delete|list> [options]
- scale the command framework by using `Jcommander` https://jcommander.org/
    - JCommander is released under the Apache 2.0 license.
    - JCommander is an annotation-based library for parsing command-line parameters
    - Help us provide a good user experience 
    - With JCommander, we can offload tricky tasks such as parsing, validation, and type conversions, to allow us to focus on our application logic.

```java
class DemoCommand {
    @Parameter(names={"--length", "-l"})
    int length;
    @Parameter(names={"--pattern", "-p"})
    int pattern;
}
```

#### Commands Diagram

![image](https://user-images.githubusercontent.com/86483005/125246089-e7f6be00-e323-11eb-86c8-0da53ba980c9.png)

#### CMD call flow

![image](https://user-images.githubusercontent.com/86483005/125246379-49b72800-e324-11eb-942b-3de080b9ace3.png)

#### ALL commands's usage

```
Usage: kyuubi-ctl <server|engine> <create|get|delete|list> [options]
[ server ]
create
  -h, --help  
  --host      the namespace, using kyuubi-defaults/conf if absent
  --namespace The connection string for the zookeeper ensemble, using 
                kyuubi-defaults/conf if absent
get
  -h, --help  
  --host      the namespace, using kyuubi-defaults/conf if absent
  --namespace The connection string for the zookeeper ensemble, using 
                kyuubi-defaults/conf if absent

[ engine ]
get
  --namespace The connection string for the zookeeper ensemble, using 
                kyuubi-defaults/conf if absent
  --host      the namespace, using kyuubi-defaults/conf if absent
  -h, --help  

```

#### Single command's usage
```
java -cp .:target/kywork-command-V1.0-jar com.kywork.KyuubiShell server get --help
get
  -h, --help  
  --host      the namespace, using kyuubi-defaults/conf if absent
  --namespace The connection string for the zookeeper ensemble, using 
                kyuubi-defaults/conf if absent
```

**Comment by pan3793** [comment]
The rework of `kyuubi-ctl` is on the way based on scopt #754

**Comment by timothy65535** [comment]
hi @pan3793,

#754 aims to use scopt to parse args, but the topic of this issue aims to talk about several things:
- Improve the order of command line parameters, which may is more friendly(put `service` in first, `action` in second, then parms)
  - `kyuubi-ctl <server|engine> <create|get|delete|list> [options]`
- Make the commands more scalable. Just based on my understanding of scopt, it will still hard to scale, scopt is more suitable for standalone command line. For exampe, scopt is used in spark project's examples. Please correct me if wrong.
- Improve the usage of shell, which benefits from JCommander, the above output is generated from JCommander.

Thanks.

**Comment by yaooqinn** [comment]
I am OK with both means. The output looks good to me.

The current command style is following `kubectl`, e.g. `kubectl get pods -n abc`.

Why nobody uses apache common-cli? LOL

**Comment by pan3793** [comment]
> - Improve the order of command line parameters, which may is more friendly(put `service` in first, `action` in second, then params)

Agreed. It's more intuitive.

> - Make the commands more scalable. Just based on my understanding of scopt, it's still hard to scale...

Could you please explain more about **scalable**? As my understand, both JCommander and scopt support sub command, option(accept zero values), argument(accept one or more values).

> - ... the above output is generated from JCommander. It's more clearer for user.

The helper message generated from JCommander LGTM, and scopt also does.

In my view, JCommander is a more powerful tool than scopt, but do we really need that? The most different things I think are JCommander written in Java but scopt written in Scala, and JCommander is an annotation-based library but scopt use DSL style.

**Comment by pan3793** [comment]
BTW, besides the parser tool, the rest design LGTM.

**Comment by timothy65535** [comment]
hi @pan3793, maybe the best way to compare them is to make a demo. I'm working on it, we can discuss them later.

by the way, can we write it in Java?

Thanks.

**Comment by yaooqinn** [comment]
yes

**Comment by pan3793** [comment]
Nice, I'm looking forward to your demo. Personally, I prefer writing it in Scala to match the whole style of the project, but writing in Java is also acceptable.

**Comment by timothy65535** [comment]
### Task List
- [ ] Introduce jcommander framework to kyuubi project
