### ISSUE TITLE
Remove obsolete CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#779]
### 1. Describe the feature

We shall switch to use https://www.apache.org/foundation/policies/conduct.html now

**Comment by yaooqinn** [comment]
cc @zhang1002

**Comment by wuchunfu** [comment]
@yaooqinn If @zhang1002  doesn't have time, I can do it

**Comment by yaooqinn** [comment]
@wuchunfu thanks~
