### ISSUE TITLE
Fix status badges in README to point the current repo

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#781]
### 1. Describe the bug

![GitHub top language](https://img.shields.io/github/languages/top/NetEase/kyuubi)
[![GitHub release](https://img.shields.io/github/release/NetEase/kyuubi.svg)](https://github.com/NetEase/kyuubi/releases)
[![codecov](https://codecov.io/gh/NetEase/kyuubi/branch/master/graph/badge.svg)](https://codecov.io/gh/NetEase/kyuubi)
[![Travis](https://travis-ci.com/NetEase/kyuubi.svg?branch=master)](https://travis-ci.com/NetEase/kyuubi)
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/NetEase/kyuubi/Kyuubi/master?style=plastic)

NetEase -> apache
kyuubi -> incubator-kyuubi

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by yaooqinn** [comment]
cc @wuchunfu, are you interested in this?

**Comment by wuchunfu** [comment]
@yaooqinn OK, I'll do the task.
