### ISSUE TITLE
[question] How to connect the HA mode Kyuubi with Beeline

### ISSUE THREAD

**Issue by loovia** [apache/incubator-kyuubi#787]
I add kyuubi.ha configures in conf/kyuubi-defaults.conf
```
kyuubi.ha.enabled true
kyuubi.ha.zookeeper.namespace kyuubi
kyuubi.ha.zookeeper.quorum 1.zookeeper.xyz,2.zookeeper.xyz,3.zookeeper.xyz
kyuubi.ha.zookeeper.client.port 2181
```
and kyuubi has been registered in zooKeeper.
when I execute `/opt/spark/spark-3.1.1-bin-hadoop2.7/bin/beeline -u jdbc:hive2://1.zookeeper.xyz:2181,2.zookeeper.xyz:2181,3.zookeeper.xyz:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNameSpace=kyuubi `, it's wrong:
> Connecting to jdbc:hive2://1.zookeeper.xyz:2181,2.zookeeper.xyz:2181,3.zookeeper.xyz:2181/
21/07/13 15:53:47 INFO Utils: Supplied authorities: 1.zookeeper.xyz:2181,2.zookeeper.xyz:2181,3.zookeeper.xyz:2181
21/07/13 15:53:47 INFO Utils: Resolved authority: 1.zookeeper.xyz:2181
21/07/13 15:53:47 WARN HiveConnection: Failed to connect to 1.zookeeper.xyz:2181
Unexpected end of file when reading from HS2 server. The root cause might be too many concurrent connections. Please ask the administrator to check the number of active connections, and adjust hive.server2.thrift.max.worker.threads if applicable.
Error: Could not open client transport with JDBC Uri: jdbc:hive2://1.zookeeper.xyz:2181/: null (state=08S01,code=0)
Beeline version 2.3.7 by Apache Hive
beeline> 

I don't know How to connect kyuubi(ha mode) by beeline. Please take a look~ thanks

**Comment by pan3793** [comment]
I think @wForget has already given a solution to this issue, so I'm going to close it and feel free to reopen or create new issues if you have other questions.
