### ISSUE TITLE
[QUESTION] Does kyuubi project plan to create apache jira space?

### ISSUE THREAD

**Issue by timothy65535** [apache/incubator-kyuubi#810]
### Describe the question

Hi, maintainers

Does kyuubi project plan to create jira space in [Apache JIRA](https://issues.apache.org/jira)? 
It's useful when we can add subtasks for importent bug/featuer.

Thanks

**Comment by yaooqinn** [comment]
Based on my research so far, the Milestone is close to the expectation

**Comment by timothy65535** [comment]
From github docs, find a doc about subtasks https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists , will try to use in https://github.com/apache/incubator-kyuubi/issues/775

**Comment by yaooqinn** [comment]
sounds nice
