### ISSUE TITLE
Fix requestTimeoutUnit in FrontendService

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#813]
### 1. Describe the bug

requestTimeoutUnit should be millisecond

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by yaooqinn** [comment]
cc @wuchunfu

**Comment by wuchunfu** [comment]
@yaooqinn OK
