### ISSUE TITLE
Manage Spark-Block-Cleaner log

### ISSUE THREAD

**Issue by zwangsheng** [apache/incubator-kyuubi#828]
### 1. Describe the feature
Use Spark Block Cleaner to clean shuffle file, but itself will remain logs.
In my opinion, there are two way to help clean block cleaner log:
* add a feature to spark block cleaner to help clean log
* make log file store in dirs which start with `spark-`(use cleaner self will clean `spark-` to help cleaning)

### 2. Motivation
Clean up spark block cleaner log

### 3. Describe the solution
Above

**Comment by zwangsheng** [comment]
WIP @yaooqinn  @ulysses-you

**Comment by yaooqinn** [comment]
RollingFileAppender

**Comment by zwangsheng** [comment]
> RollingFileAppender

Do you mean using rollingFileAppenderto split into files, and then clean up those files regularly?
