### ISSUE TITLE
Support Restful API for Kyuubi server

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#835]
### 1. Describe the feature
Currently, Kyuubi does not provide a suite of restful APIs. This proposal tries to support this feature so that Kyuubi server can expose a group of functional APIs to interact with the outer world.

### 2. Motivation
Having a restful API service is very useful to do the interaction and integration with the third-party component.

### 3. Describe the solution
We can design and list all the planned API interfaces. Then, talking the technology details.

**Comment by yanghua** [comment]
@yaooqinn WDYT about this feature.

**Comment by yaooqinn** [comment]
#32 duplicated？ we do wanna a thrift http frontend

**Comment by yanghua** [comment]
> #32 duplicated？ we do wanna a thrift http frontend

Yes, what's the status? Does anyone drive this feature?

**Comment by yaooqinn** [comment]
Not yet taken. Are you interested？

**Comment by yanghua** [comment]
> Not yet taken. Are you interested？

Yes, I can drive this feature. In our company, we have built a restful service and UI based on the old Kyuubi version.

**Comment by yaooqinn** [comment]
thanks a lot

**Comment by yanghua** [comment]
Closing this one and move to #32
