### ISSUE TITLE
How to read the new data by spark which was writed by flink DataStream

### ISSUE THREAD

**Issue by lordk911** [apache/incubator-kyuubi#837]
I hava a flink datastream keep write data to iceberg. And I try to use kyuubi to read it , I found I can't read the newly incoming data , even after I run :
`refresh table test.xxx`
only after I close current connection and reconnect to kyuubi then I can read the new data.

Please let me know which is the right way to do it.

**Comment by pan3793** [comment]
`refresh table test.xxx` should work in my mind, would you please add more context, like versions of iceberg, flink, and spark, and have you enabled format v2 on the table?

**Comment by lordk911** [comment]
Thanks for reply.
iceberg 0.11.1 \ flink 1.11.3 \ spark 3.1.2 .  iceberg table was created by spark sql , and data was write by flink using  datastream api

Now I have resolve it by setting `spark.sql.catalog.catalog-name.cache-enabled`  to false.  Maybe it's not quite suitable.

**Comment by pan3793** [comment]
> format v2 is the default for spark3 ?

No, Iceberg format v2 is not public open to end-users.

Sounds like Spark cannot see the table changes made by Flink, I'm not familiar with Flink, and I just have a quick test that `refresh table` works after writing data by Spark.

**Comment by yaooqinn** [comment]
maybe try `msck repair table`?

**Comment by lordk911** [comment]
> > format v2 is the default for spark3 ?
> 
> No, Iceberg format v2 is not public open to end-users.
> 
> Sounds like Spark cannot see the table changes made by Flink, I'm not familiar with Flink, and I just have a quick test that `refresh table` works after writing data by Spark.

yes, data write by spark will be readable immediately

**Comment by lordk911** [comment]
What happen when reconnect to kyuubi server. 
Even though the sparksession was not killed,  so when I reconnect to kyuubi ,the sparksession was same as before, but I can read the newly data wtire by flink.
If I use spark-shell, The only way is to restart spark-shell.


And set `spark.sql.catalog.catalog-name.cache-enabled` to false work for both situation.

**Comment by pan3793** [comment]
Different Kyuubi connections may share the same SparkContext, but not the same SparkSession.

**Comment by yaooqinn** [comment]
cc @cloud-fan can you check this, thanks

**Comment by cloud-fan** [comment]
It seems like Iceberg catalog has internal caches and `REFRESH TABLE` can't clear that cache. I'm not familiar with iceberg though/.

**Comment by yaooqinn** [comment]
+1 for @cloud-fan's explanation. @lordk911 I would suggestest you create an issue on the iceberg side and cc them with this ticket

**Comment by lordk911** [comment]
> +1 for @cloud-fan's explanation. @lordk911 I would suggest you create an issue on the iceberg side and cc them with this ticket

ok I will

**Comment by pan3793** [comment]
Find one same issue reported by another guy, but he said that `refresh table` works.

https://github.com/apache/iceberg/issues/2447

**Comment by lordk911** [comment]
org.apache.iceberg.spark.SparkSessionCatalog will have this problem; 
org.apache.iceberg.spark.SparkCatalog is fine;

**Comment by pan3793** [comment]
https://github.com/apache/iceberg/issues/2972

**Comment by lordk911** [comment]
If use kyuubi for BI data souce, the refreh statment have no opportunity to execute.

So need to set spark.sql.catalog.{catalog-name}.cache-enabled to false.

**Comment by yaooqinn** [comment]
Hi, @lordk911   have you addressed #925 ? It would be great if you can share your story there:)

**Comment by lordk911** [comment]
Thanks for Kyuubi team's great job. We will do it, After we use it in production environment scaled, Now we still under testing.
 
We may also want to use Kyuubi for data transformation between diffrent hadoop cluster of diffrent department. Because of it's authentication and authorization ability. But may be all data will collect to spark driver is not suitable for this situation.
