### ISSUE TITLE
Upgrade ZooKeeper 3.4.14 to 3.5.5

### ISSUE THREAD

**Issue by timothy65535** [apache/incubator-kyuubi#838]
### 1. Describe the feature

When the kyuubi server start with embedded zookeeper, will always output following warn log.
Also, ZooKeeper 3.4.x is now at end-of-life. Consequently, the latest versions of Curator have removed support for it.
```
2021-07-20 14:54:34.883 INFO server.PrepRequestProcessor: Got user-level KeeperException when processing sessionid:0x10002067d5c0002 type:create cxid:0x2 zxid:0x6 txntype:-1 reqpath:n/a Error Path:/kyuubi_USER/lock/anonymous/locks Error:KeeperErrorCode = NoNode for /kyuubi_USER/lock/anonymous/locks
2021-07-20 14:54:34.885 WARN utils.ZKPaths: The version of ZooKeeper being used doesn't support Container nodes. CreateMode.PERSISTENT will be used instead.
2021-07-20 14:54:34.896 INFO server.PrepRequestProcessor: Got user-level KeeperException when processing sessionid:0x10002067d5c0002 type:create cxid:0xd zxid:0xc txntype:-1 reqpath:n/a Error Path:/kyuubi_USER/lock/anonymous/leases Error:KeeperErrorCode = NoNode for /kyuubi_USER/lock/anonymous/leases
```

### 2. Describe the solution

- Upgrade ZooKeeper 
- Upgrade CuratorFramework

### 3. Additional context

https://curator.apache.org/zk-compatibility-34.html

**Comment by yaooqinn** [comment]
maybe we can catch up with spark now

**Comment by timothy65535** [comment]
Hi @yaooqinn, the modules in spark do not use zookeeper dependency.

**Comment by yaooqinn** [comment]
> the modules in spark do not use zookeeper dependency

Spark standalone use zk for HA

**Comment by timothy65535** [comment]
> > the modules in spark do not use zookeeper dependency
> 
> Spark standalone use zk for HA

Sorry, it's my mistake. 😃

**Comment by yaooqinn** [comment]
yes, but I am not sure if it works for spark 3.0/3.1. we can give it a try

**Comment by pan3793** [comment]
AWS EMR still using Zookeeper 3.4.x https://docs.aws.amazon.com/emr/latest/ReleaseGuide/ZooKeeper-release-history.html

**Comment by timothy65535** [comment]
hi @pan3793, when connect to the embedded zookeeper in own project, it throws `UnimplementedException`.

It's ok if upgrate to zookeeper 3.5.5.

```
Exception in thread "main" org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /data
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
	at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)
	at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:217)
```

**Comment by timothy65535** [comment]
From the pr in spark, it aims to run spark in jdk14.
https://github.com/apache/spark/pull/31177

**Comment by timothy65535** [comment]
hi @yaooqinn @pan3793 I think zookeeper 3.5.5 is enough. What is your opinion?

**Comment by yaooqinn** [comment]
As long as we can ensure backward-compatibility, i am ok with it

**Comment by pan3793** [comment]
We don't recommend using the embedded zookeeper in production.
Assume you have a zookeeper 3.4/3.5/3.6 cluster, both Kyuubi with zookeeper 3.4 client and another zookeeper client (keep the client version lower than the server) can access the zookeeper cluster at the same time.
If bump Kyuubi zookeeper client (embedded zookeeper and client share the same jar) to 3.5, it means we drop the support of zookeeper 3.4. 
PS. CDH6, AWS EMR use zookeeper 3.4

**Comment by pan3793** [comment]
http://zookeeper.apache.org/releases.html

> ZooKeeper clients from 3.4 and 3.5 branch are fully compatible with 3.6 servers.

**Comment by timothy65535** [comment]
Thanks for your reply @pan3793. And, from spark master branch, we can see that if kyuubi run on jdk14 later, we will meet the same error.
|  ZK SERVER  | ZKCLIENT | compatible | jdk14
|  ----  | ----  | --- | -- |
| 3.4  | 3.4 | ok | error |
| 3.4  | 3.5 | error | error |
| 3.5  | 3.4 | ok | ok |
| 3.5  | 3.5 | ok | ok |

**Comment by pan3793** [comment]
From the table, Kyuubi will be broken if run jdk14+ when embedded zookeeper, and works fine with remote high version Zookeeper Cluster. But the upgrade means we drop the support of CDH6 and AWS EMR. I vote to keep using 3.4.

**Comment by yaooqinn** [comment]
Do we have issues at compile phase?

**Comment by timothy65535** [comment]
> Do we have issues at compile phase?

No, it's ok at compile phase. it always output `WARN` log when tests.
```
2021-07-20 14:54:34.885 WARN utils.ZKPaths: The version of ZooKeeper being used doesn't support Container nodes. CreateMode.PERSISTENT will be used instead.
```

**Comment by yaooqinn** [comment]
> hi @pan3793, when connect to the embedded zookeeper in own project, it throws `UnimplementedException`.
> 
> It's ok if upgrate to zookeeper 3.5.5.
> 
> ```
> Exception in thread "main" org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /data
> 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:106)
> 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
> 	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1538)
> 	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
> 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
> 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
> 	at org.apache.curator.framework.recipes.locks.StandardLockInternalsDriver.createsTheLock(StandardLockInternalsDriver.java:54)
> 	at org.apache.curator.framework.recipes.locks.LockInternals.attemptLock(LockInternals.java:217)
> ```

If we shade the zk client, can we bypass the error in you custom branch?

**Comment by timothy65535** [comment]
When I test the embedded zookeeper in local env, the `UnimplementedException` will throw if use high version client.

**Comment by yaooqinn** [comment]
What if we only upgrade the zk in kyuubi server？

**Comment by timothy65535** [comment]
> What if we only upgrade the zk in kyuubi server？

I think it's better to upgrate zk and curator together. If keep curator version, we need to do more things.
https://curator.apache.org/zk-compatibility-34.html

It's ok only upgrate zk in kyuubi server like spark project.

**Comment by timothy65535** [comment]
The root cause is zk3.4.x can not compatible with high version curator, but zk3.5.x can compatible with both zk3.4 and zk3.5

**Comment by yaooqinn** [comment]
if a higher curator can work with zk 3.4, that's ok

**Comment by timothy65535** [comment]
> if a higher curator can work with zk 3.4, that's ok

No, the main problem is the version of zk is low.

**Comment by timothy65535** [comment]
It's nice that everything is ok after upgrade zk to 3.5.5.

**Comment by timothy65535** [comment]
Hi @yaooqinn @pan3793, Just only upgrade zk server to 3.5.5 is ok. I had test it just now.

- kyuubi-ctl get engine ---> ok
- `WARN utils.ZKPaths: The version of ZooKeeper being used doesn't support Container nodes`  is gone.
- curator client 2.12.0 ---> ok
- zookeeper client 3.4.14 and 3.5.5 ---> ok

how about only upgrate zk server to 3.5.5. I think it'll not cause drop the support of CDH6 and AWS EMR, because we keep the curator client version.

**Comment by yaooqinn** [comment]
OK

**Comment by pan3793** [comment]
Upgrate zk server means upgrade `org.apache.zookeeper:zookeeper`?

**Comment by timothy65535** [comment]
> Upgrate zk server means upgrade `org.apache.zookeeper:zookeeper`?

right

**Comment by pan3793** [comment]
zookeeper client and server share the `org.apache.zookeeper:zookeeper`, you also upgraded the client.

**Comment by timothy65535** [comment]
> zookeeper client and server share the `org.apache.zookeeper:zookeeper`, you also upgraded the client.

The zookeeper 3.5.5 can compatible with curator 2.12.0 and curator 4.2.0. We still use curator 2.12.0 client.

**Comment by pan3793** [comment]
The key point here is Zookeeper 3.5.x clients are incompatible with 3.4 server, but CDH 6 and EMR only provided 3.4 server.

**Comment by timothy65535** [comment]
Wow, get your point. You mean use curator 2.12.0 with zk3.5.5 to connect zk cluster is 3.4. 🙁

**Comment by timothy65535** [comment]
@pan3793 Thanks for your advice and get your point, will close this issue. 
By the way, zk3.4 is now at end-of-life. In product we already use zk3.5.x, will come back if anyone meets `UnimplementedException`.

**Comment by yaooqinn** [comment]
can we add a zk profile instead？

**Comment by timothy65535** [comment]
> can we add a zk profile instead？

Nice!!! The spark3.2 will include zk3.6.2, we can go back here when kyuubi support spark3.2 or 3.3

**Comment by yaooqinn** [comment]
If we are able to bump up curator to 4.2.x then we are able to work with both zk 3.4 and 3.5?

**Comment by yaooqinn** [comment]
this is also reported by meituan once, I am glad if we can have a proper solution here

**Comment by timothy65535** [comment]
> If we are able to bump up curator to 4.2.x then we are able to work with both zk 3.4 and 3.5?

Curator4.2.0 can work with zk3.4 and zk3.5. whether throw `UnimplementedException` or not depending on the version of zookeeper dependency.

```
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
<!--            <version>3.4.14</version>-->
            <version>3.5.5</version>
        </dependency>

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
        </dependency>
```

**Comment by timothy65535** [comment]
> this is also reported by meituan once, I am glad if we can have a proper solution here

I‘m glad to have a try to solve this issue.

**Comment by yaooqinn** [comment]
maybe we can use https://mvnrepository.com/artifact/org.apache.flink/flink-shaded-zookeeper-3/3.5.6-13.0 ?

**Comment by timothy65535** [comment]
It seems not ok if we just use zk profile.

- `dependencyList` just include only one zookeeper version
- externals jars will inflict with spark jars

![image](https://user-images.githubusercontent.com/86483005/126341785-1dfd6978-dd64-48b8-98c3-255a22fe9790.png)

![image](https://user-images.githubusercontent.com/86483005/126341801-ba71b960-29f3-4e3c-b2ba-9f3276222281.png)

**Comment by timothy65535** [comment]
> maybe we can use https://mvnrepository.com/artifact/org.apache.flink/flink-shaded-zookeeper-3/3.5.6-13.0 ?

nice, have a try.

**Comment by pan3793** [comment]
I'd like to talk about what I thought about this issue.

Actually, we have tried to do something to solve the jar conflicts and try our best to keep the dependencies up-to-date but also be compatible with most components.

You can find some previous discussion at #488, but unfortunately, the PR got reverted finally because it's not friendly to developers. (`mvn clean install` must be run first, then IDEA and `mvn clean package` works)

And I think shade is the right direction to solve this issue.

If we shade `curator 2.12` and `zookeeper 3.4` then Kyuubi will be compatible with zookeeper 3.4/3.5/3.6, and it can co-exist with the normal `curator 4.2` and `zookeeper 3.5/3.6`(i.e. kyuubi engine running with spark 3.2)

Then the problem becomes which is the best way to shade and use shaded jars?

There are some options I have thought of.

1. shade jar in independent modules (#488)
2. shade jar in independent repos, like https://github.com/apache/flink-shaded
3. migrate from maven to gradle, and shade jar in independent sub-project, like https://github.com/apache/iceberg

Now, as Spark 3.2 is on the way, and more people reported the issues, I think it's time to make the decision, and I'd like to hear what other people thought.

**Comment by timothy65535** [comment]
Thanks @pan3793, close it now. Free to reopen or create a new one.
