### ISSUE TITLE
Fix load user specific defaults from properties file

### ISSUE THREAD

**Issue by hddong** [apache/incubator-kyuubi#839]
### 1. Describe the bug

`loadFromMap` ignored user specific defaults that start with '___'.

#### 2.1 Versions

- Kyuubi
  - [X] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [X] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 2.2 Kyuubi Configurations
`___test3___.spark.driver.memory=8g`

#### 4.2 Log of the corresponding engine

**Comment by yaooqinn** [comment]
nice catch
