### ISSUE TITLE
[Umbrella] Kyuubi Spark Monitor: Getting metrics from statement and dumpping them into a file

### ISSUE THREAD

**Issue by zhang1002** [apache/incubator-kyuubi#852]
# Describe the proposal

This module's major feature is event tracking and dumpping them into a file(local log file or remote file like hdfs).
Now event granularity just have statement, job and stage.
You can get each statement's summary info and use statementId to look up the jobs' or stages' metrics.
According to those metrics, it will be easier to find out where the problem lies and optimize performance.

# Task list

- [x] #845 
- [x] #846
- [x] #847
- [ ] #848 
- [x] #850 
- [x] #851
- [x] #860 
- [ ] #869
- [] #906

**Comment by zhang1002** [comment]
The feature: event tracking for stage, have finished.
Now, develop #846, #860 and #850

**Comment by yaooqinn** [comment]
create #906 for session event,@zhang1002

**Comment by pan3793** [comment]
Moved to v1.4.0

**Comment by turboFei** [comment]
Moved to v1.5.0
