### ISSUE TITLE
[Typo] Change KPIP to KBIP in the official web site.

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#876]
### 1. Describe the bug

https://kyuubi.apache.org/improvement-proposals.html

Search "KPIP"

**Comment by yaooqinn** [comment]
nice catch

**Comment by yanghua** [comment]
@yaooqinn Where is the codebase of the official website?

**Comment by yaooqinn** [comment]
https://github.com/apache/incubator-kyuubi/blob/master/docs/community/improvement-proposals.md

**Comment by pan3793** [comment]
@yanghua FYI https://github.com/apache/incubator-kyuubi-website

**Comment by yanghua** [comment]
thanks, guys~
