### ISSUE TITLE
Access Kyuubi with ODBC Drivers

### ISSUE THREAD

**Issue by zhangbutao** [apache/incubator-kyuubi#883]
Hi, kyuubi dev. kyuubi doc show it can be accessed by odbc driver. I have test kyuubi with spark odbc driver and hive odbc drive, but it did't work. 

So, how to configure kyuubi or odbc drive to make it work? thanks!

**Comment by butaozhang** [comment]
![kyuubi_odbc_error](https://user-images.githubusercontent.com/9760681/127826892-b49dfa32-60fe-4846-9f93-eeb09e74f01a.png)

**Comment by yaooqinn** [comment]
Not familiar with ODBC, can you show us to server log too?

**Comment by butaozhang** [comment]
Unfortunately, there was no server log output. I encounter the problem with master branch.  Does the previous kyuubi version work well? Because I see the issue **https://github.com/apache/incubator-kyuubi/issues/180**.

**Comment by yaooqinn** [comment]
Does jdbc or beeline work well with the Kyuubi backend you started?

**Comment by butaozhang** [comment]
I have test kyuubi with beeline and it works well. I start kyuubi with command  “**/kyuubi-1.3.0-SNAPSHOT-bin-without-spark/bin/kyuubi** ".

**Comment by yaooqinn** [comment]
According to the errors above, it seems that the SSL is off by default in ODBC driver. Maybe you need to turn it on

**Comment by butaozhang** [comment]
Thanks. The error should to be unrelated to SSL.  I will do further research about the issue.

**Comment by yaooqinn** [comment]
Hope you make it work

**Comment by pan3793** [comment]
Solved by #3122, docs are welcome

**Comment by zhangbutao** [comment]
It was a long time ago. Actually, I have found the reason was that my host env had two ip(internal ip & external ip), and kyuubi started with interal ip which could not be accessed by external tools.  If i specified the external ip to start kyuubi, the odbc drive would be ok. :)
