### ISSUE TITLE
[Umbrella] Add HTTP transport mode support to KYUUBI

### ISSUE THREAD

**Issue by RamakrishnaChilaka** [apache/incubator-kyuubi#886]
### 1. Describe the feature
Access KYUUBI HTTP calls.

### 2. Motivation
if we can support submitting queries via HTTP mode,  this will enable us to use this via HAPROXY/NGINX reverse proxys.
We can use Jupyter Notebooks and backend servers to query spark sql as a service.

### 3. Tasks

- [ ] #1761
- [ ] Implement a httpserver by jetty

**Comment by RamakrishnaChilaka** [comment]
https://github.com/apache/incubator-kyuubi/issues/32 this already talks about HTTP frontend. Closing this.

**Comment by yaooqinn** [comment]
that ticket is not exactly the same，you can work on this if you are interested

**Comment by RamakrishnaChilaka** [comment]
I am interested @yaooqinn , can you point me to the codebase documentation ?

**Comment by yaooqinn** [comment]
docs/ ？

**Comment by iodone** [comment]
@RamakrishnaChilaka This mode is just like Hive Thrift Server HttpMode?  The protocol for client interaction with Kyubi is still Thrift, and the communication protocol is HTTP.

**Comment by RamakrishnaChilaka** [comment]
Yes @iodone .

**Comment by SteNicholas** [comment]
@yaooqinn, could you please assign this ticket to me?
