### ISSUE TITLE
Enhance kyuubi-zookeeper module

### ISSUE THREAD

**Issue by timothy65535** [apache/incubator-kyuubi#894]
### 1. Describe the feature

Kyuubi use `TestingServer` as the EmbeddedZookeeper service in codebase, and require many args to init the service. These `electionPort`, `quorumPort`, `serverId` parameters only work in cluster mode, these ports are not bound to the host. 

From hadoop and bookkeeper project, they use `ZooKeeperServer` as a built-in zk service, especially the bookeeper project.
- https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-registry/src/main/java/org/apache/hadoop/registry/server/services/MicroZookeeperService.java
- https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/shims/zk/ZooKeeperServerShimImpl.java

### 2. Describe the solution

Improve
- Remove `electionPort`, `quorumPort`, `serverId` which are nerver be used, hadoop and bookkeer do the same
- Replace `TestingServer` with `ZooKeeperServer`
- Remove `curator-test` dependency

**Comment by yaooqinn** [comment]
Removing TestingServer sounds good to me 

> Remove electionPort, quorumPort, serverId which are nerver be used, hadoop and bookkeer do the same

Can we make each KyuubiServer served as a quorum peer?

**Comment by timothy65535** [comment]
> Removing TestingServer sounds good to me
> 
> > Remove electionPort, quorumPort, serverId which are nerver be used, hadoop and bookkeer do the same
> 
> Can we make each KyuubiServer served as a quorum peer?

Maybe we don't need to do this, because `TestingServer` is not a full feature supported.

For zookeeper quorum peer, it is recommended to use a separate zookeeper cluster.

For kyuubi quorum peer, it seems raft is a better choice(I not sure).

**Comment by yaooqinn** [comment]
Ok, we can keep optimizing this module when we find better solutions someday. we can remove the testing server here first

**Comment by timothy65535** [comment]
Got @yaooqinn, do you have any ideas @pan3793

**Comment by pan3793** [comment]
Thanks for this proposal, replace `TestingServer` with `ZooKeeperServer` make sense to me. 

> For Kyuubi quorum peer, it seems raft is a better choice(I not sure).

Do you mean implements a Raft component like KRaft in Kafka 3.0? Personally, I think Paxos or ZAB or Raft or Gossip is not really mattered here, maybe an abstract service discover layer with adapters to K8s `api-server`, `Zookeeper`, `Etcd` make more sense to me.

**Comment by timothy65535** [comment]
Will remove the testing server first. 

> maybe an abstract service discover layer with adapters to K8s api-server, Zookeeper, Etcd make more sense to me.

Let's think about it, will let you know  if have any ideas.

**Comment by pan3793** [comment]
There is a fork of Kyuubi which implemented K8sSessionManager and K8sSessionImpl, maybe we can learn something from it.

https://zhuanlan.zhihu.com/p/345214051
https://github.com/yilong2001/kyuubi

**Comment by timothy65535** [comment]
> There is a fork of Kyuubi which implemented K8sSessionManager and K8sSessionImpl, maybe we can learn something from it.
> 
> https://zhuanlan.zhihu.com/p/345214051
> https://github.com/yilong2001/kyuubi

Nice !!!
