### ISSUE TITLE
Cannot load resource's kyuui-default.conf file when mvn package to a fat jar

### ISSUE THREAD

**Issue by iodone** [apache/incubator-kyuubi#900]
### 1. Describe the bug

Code: 
https://github.com/apache/incubator-kyuubi/blob/1a76d77b6fe37902161b770b31ffc5b0e5006fb4/kyuubi-common/src/main/scala/org/apache/kyuubi/Utils.scala#L47-L57

Call `getClass.getClassLoader.getResource(KYUUBI_CONF_FILE_NAME))` function in fat jar，the root path of the project execution is not available as expected. So the `kyuubi-default.conf` file under resource cannot be loaded when the program starts(Just the scene in fat jar). 

Solution: To be compatible with current single jars and fat jars, we can replace `getResource` with `getResourceAsStream` 

#### 2.1 Versions

- Kyuubi
  - [ x ] 1.2.0

**Comment by pan3793** [comment]
Please follow https://kyuubi.apache.org/docs/latest/tools/distribution.html to build your dist. Kyuubi has no plan to support fat-jar mode.

**Comment by iodone** [comment]
This is just to show that getResource may be empty in some scenarios where the classLoader loads the resource file and can be replaced by getResourceAsStream. Our scenario is based on the secondary development of kyuubi, so we encountered this problem

**Comment by pan3793** [comment]
You should handle those cases by yourself if you changed the package approach.
