### ISSUE TITLE
[Umbrella] Support long running SQL engine without principal and keytab provided

### ISSUE THREAD

**Issue by zhouyifan279** [apache/incubator-kyuubi#913]
# Describe the proposal

Due to Spark's limitation, a long running SQL engine must be submitted wtih principal and keytab in order to access secured Hadoop cluster. Turn to Kyuubi, this means before using principal and keytab in JDBC url, keytab files need to be deploy on each host where Kyuubi Servers are running.

This umbrellla issue propsed a new way to enable Kyuubi to launch long running SQL engine without principal and keytab provided:
1. Hadoop Cluster manager configures Kyuubi Server's principal to impersonate all Kyuubi users by adding [hadoop proxyuser conf](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/Superusers.html).
2.  Kyuubi Server will obtain DelegationTokens for each use and periodically renew and push DelegationTokens to SQL engine.
 
# Task list

- [x] #915 
  - [x] #1007
  - [x] #1008
  - [x] #1009
- [x] #916
- [x] #1090

**Comment by link3280** [comment]
My 2 cents: Is this feature scoped to YARN setups only? And what if the application needs to access services that do not support Hadoop delegation token (e.g. Kafka)?

**Comment by link3280** [comment]
@ulysses-you Thanks a lot for your input! Now I have a better sense of the PR.

**Comment by pan3793** [comment]
Moved to v1.4.0.

**Comment by turboFei** [comment]
Moved to v1.5.0.

**Comment by zhouyifan279** [comment]
This issue is in v1.4.0 and is finished. Milestone should not be v1.5.0.

**Comment by turboFei** [comment]
thanks @zhouyifan279  have corrected it.
