### ISSUE TITLE
The GetCatalogs API does not show all the Catalogs configured via SparkConf

### ISSUE THREAD

**Issue by iodone** [apache/incubator-kyuubi#929]
### 1. Describe the bug

The Kyuubi Engine is configured with multiple Spark Catalogs, and calls the Kyuubi Server's GetCatalogs Thrift API after startup, which can only show the default catalog configuration.
After checking the implementation of GetCatalogs, I finally traced it to this:

https://github.com/apache/incubator-kyuubi/blob/7e2d67ed618bff5ca58e35814c681a94e457e9f3/externals/kyuubi-spark-sql-engine/src/main/scala/org/apache/kyuubi/engine/spark/shim/CatalogShim_v3_0.scala#L29-L42

The called catalogs API are obtained from the CatalogManager and then traced to the Spark CatalogManager Catalogs registration at

```
 private val catalogs = mutable.HashMap.empty[String, CatalogPlugin]

  def catalog(name: String): CatalogPlugin = synchronized {
    if (name.equalsIgnoreCase(SESSION_CATALOG_NAME)) {
      v2SessionCatalog
    } else {
      catalogs.getOrElseUpdate(name, Catalogs.load(name, conf))
    }
  }

```

Catalog registration additions are dynamically loaded, that is, only when the Catalog is used will it be registered.
The problem is that when connecting to Kyuubi Server at the beginning, it is not possible to get all the catalog display information, which usually occurs only in multiple Catalog scenarios

#### 2.1 Versions

- Kyuubi
  - [x] 1.2.0

- Spark
  - [x] 3.1.x

#### 2.3 Spark Configurations
Multi-Catalog Support
```
spark.sql.catalog.catalog0=catalog0.implemant.class
spark.sql.catalog.catalog1=catalog1.implemant.class
spark.sql.catalog.catalog2=catalog2.implemant.class
```

**Comment by yaooqinn** [comment]
also, cc @pan3793

**Comment by pan3793** [comment]
Yes, spark uses lazy strategy to load catalogs, there is a workaround provided by #857 to load catalogs after the session is created. 
`kyuubi.engine.session.initialize.sql=show tables in catalog0.default;show tables in catalog1.default`

**Comment by pan3793** [comment]
Some related issues: https://github.com/apache/spark/pull/33175, https://github.com/apache/spark/pull/33692

**Comment by iodone** [comment]
> apache/spark#33175

I was just about to raise an issue about Show Catalogs support in Kyuubi Server, and spark itself is ready to support it, @pan3793 thanks for the reminder.

**Comment by yaooqinn** [comment]
maybe we can introduce a pre-load logic for meta API too

**Comment by iodone** [comment]
> maybe we can introduce a pre-load logic for meta API too

`Show Catalogs` is to get so Catalog name display, let the user know the current Catalog List, not necessarily to go to directly load the Catalog, the user really use when then loaded on demand. Is it possible to read all the catalog names directly from spark.sql.catalog.* in spark conf ?

**Comment by yaooqinn** [comment]
Do you mean the statement `Show Catalogs`? A meta API call has nothing to do with statements, for BI tools like Dbeaver, meta APIs are usually called ahead.

**Comment by iodone** [comment]
Currently spark does not support Show Catalogs statement, we have implemented based on GetCatalogs meta API. But in BI tools like DBeaver, it is not possible to get all the Catalogs in the initialization, right?

**Comment by yaooqinn** [comment]
why is it not possible?

**Comment by iodone** [comment]
As mentioned above, spark uses lazy strategy to load catalogs, if not Pre-load, GetCatalogs API does not get all the Catalog's name list. I wonder if it is possible to fetch the name of catalogs directly from the spark conf without pre-loading?

**Comment by pan3793** [comment]
> As mentioned above, spark uses lazy strategy to load catalogs, if not Pre-load, GetCatalogs API does not get all the Catalog's name list. I wonder if it is possible to fetch the name of catalogs directly from the spark conf without pre-loading?

I think it's a feasible approach, but may make the things inconsistent with `show catalogs`, since https://github.com/apache/spark/pull/33175 has not got merged yet, maybe we can discuss the implementations of `show catalogs` in upstream

**Comment by yaooqinn** [comment]
We can list all catalogs by configs. What happens next will be the Dbeaver client use the catalog names to get all databases, and then tables, etc. That's the pre-load, I actually mean,
