### ISSUE TITLE
Push Kyuubi docker image

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-kyuubi#937]
### 1. Describe the feature
Push Kyuubi docker image to dockerhub

Some test tailed due to the image is outdate, we need a official docker image repo.

https://hub.docker.com/repository/docker/apache/kyuubi/general

**Comment by yaooqinn** [comment]
LGTM

**Comment by ulysses-you** [comment]
created a ticket https://issues.apache.org/jira/browse/INFRA-22212

**Comment by ulysses-you** [comment]
Now the docker repo is ready, but we need [secrets](https://docs.github.com/en/actions/guides/publishing-docker-images) for github action.

Created a new ticket https://issues.apache.org/jira/browse/INFRA-22341
