### ISSUE TITLE
Support for adding internal attributes to ConfigBuilder

### ISSUE THREAD

**Issue by timothy65535** [apache/incubator-kyuubi#942]
### Description

`ConfigBuilder` currently only supports public configuration by default. In practice, there are also some configurations, which are internal configurations and do not need to be reserved for users.

refer to https://github.com/apache/incubator-kyuubi/pull/935#issuecomment-900117832

### Modification

- Add `internal` to ConfigBuilder
- Update `AllKyuubiConfiguration`

**Comment by yaooqinn** [comment]
👍
