### ISSUE TITLE
[Umbrella][KPIP-1] Support RESTful API for Kyuubi

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#950]
# Describe the proposal

See the proposal document: #917 

# Task list

- [x] #952 @yanghua 
- [x] #979 @yanghua 
- [x] #983 @yanghua 
- [x] #999 @yanghua 
- [x] #1011 @yanghua 
- [x] #1031 @yanghua 
- [x] #1052 @yanghua 
- [x] #1088 @yanghua 
- [x] #1092 @yanghua 
- [x] #1102 @yanghua  
- [x] #1106  @simon824  
- [x] #1135 @cfmcgrady 
- [x] #1258 @simon824  
- [x] #1275 @simon824 
- [x] #1294 @simon824  
- [x] #1351 @simon824 
- [ ] #1444 @simon824  
- [x] #1612
- [x] #1611
- [x] #1614
- [x] #1620 @simon824 
- [x] #1575 @simon824 
- [x] #1631
- [x] #1639
- [ ] #1672 @yaooqinn

**Comment by mahengyang** [comment]
这个功能好

**Comment by turboFei** [comment]
seems all of them are completed.

should we mark it as finished? @yanghua

**Comment by simon824** [comment]
> seems all of them are completed.
> 
> should we mark it as finished? @yanghua

It's not completed yet, still having many things to do.

**Comment by yaooqinn** [comment]
ping @yanghua @simon824, branch-1.5's been cut. Does anything more need to be fixed in this ticket? Otherwise, we shall mark this work as completed.

BTW, I notice that we have nothing in doc about this feature, right? It's not good for our users to use this feature.

**Comment by simon824** [comment]
> ping @yanghua @simon824, branch-1.5's been cut. Does anything more need to be fixed in this ticket? Otherwise, we shall mark this work as completed.
> 
> BTW, I notice that we have nothing in doc about this feature, right? It's not good for our users to use this feature.

Yes, it can be marked as completed, if there is any bug in the future, can ping me to fix , and I will add the document later.

**Comment by yaooqinn** [comment]
@simon824 thanks for the confirmation. actually, they're a lot of APIs through Rest, we can summarize and improve them in the future.
