### ISSUE TITLE
Refactor dockerfile

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#954]
### 1. Describe the feature

1. As the binary distributions contain all things that we want, we don't need a pre-build spark as a docker base image, use java as the base image instead.

2. Build kyuubi from source code.

**Comment by zwangsheng** [comment]
Thanks for your issue. My opinion is that if we don't use kyuubi externals spark, we need to set SPARK_HOME in kyuubi-env.sh. This requires us to package spark together in the image. It may better to use FROM Spark image.
