### ISSUE TITLE
Fail to get table list if there is "_" in schema's name

### ISSUE THREAD

**Issue by Baoqi** [apache/incubator-kyuubi#956]
### 1. Describe the bug

I used "kyuubi-tpcds" tool to generate test data.  And the result schema is: tpcds_sf1

Then, I use datagrip to connect to kyuubi. Datagrip will not find any tables under tpcds_sf1.

This is because a bug in src/main/scala/org/apache/kyuubi/engine/spark/operation/SparkOperation.scala , function toJavaRegex().

The input is:     tpcds\_sf1

and in function

```
 def toJavaRegex(input: String): String = {
    val res = if (StringUtils.isEmpty(input) || input == "*") {
      "%"
    } else {
      input
    }
    val in = res.toIterator
    val out = new StringBuilder()

    while (in.hasNext) {
      in.next match {
        case c if c == '\\' && in.hasNext => Pattern.quote(Character.toString(in.next()))
        case c if c == '\\' && !in.hasNext => Pattern.quote(Character.toString(c))
        case '_' => out ++= "."
        case '%' => out ++= ".*"
        case c => out ++= Character.toString(c)
      }
    }
    out.result()
  }
```

the " case c if c == '\\' && in.hasNext => Pattern.quote(Character.toString(in.next()))" line,    the Pattern.quote result is just ignored.   So, later, we are querying "tpcdssf1"  as the schema, which definitely don't have any tables (which don't exist)

#### 2.1 Versions

- Kyuubi
  - [x] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [x] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by yaooqinn** [comment]
@Baoqi Hi, can u send a PR for this bug?
