### ISSUE TITLE
Call closeOperation function in AbstractSession may cause inconsistencies in the operations held by Session and OpeartionManager

### ISSUE THREAD

**Issue by iodone** [apache/incubator-kyuubi#961]
### 1. Describe the bug

**Bug Analysis**
https://github.com/apache/incubator-kyuubi/blob/4aa93d3cbdb71ca6c8eb91bd426fdd5191d03f02/kyuubi-common/src/main/scala/org/apache/kyuubi/session/AbstractSession.scala#L180-L183

In the implementation of closeOperation, `sessionManager.operationManager.closeOperation(operationHandle)` will be called first.

https://github.com/apache/incubator-kyuubi/blob/4aa93d3cbdb71ca6c8eb91bd426fdd5191d03f02/kyuubi-common/src/main/scala/org/apache/kyuubi/operation/OperationManager.scala#L102-L106

In the implementation of `operationManager.closeOperation`, the operation in operationManager is removed first, and then closed, if an exception occurs in the `operation.close` phase, the `opHandleSet.remove(operationHandle)` in `Session.closeOperation.remove(operationHandle)` will not be executed, which will lead to inconsistency between the operation of OperationManager.handleToOperation and Session.opHandleSet

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
Would you like to send a PR to fix it?

**Comment by iodone** [comment]
> Would you like to send a PR to fix it?

OK
