### ISSUE TITLE
Whether the user default configuration need to support different sharelevels?

### ISSUE THREAD

**Issue by wForget** [apache/incubator-kyuubi#966]
### 1. Describe the feature

In the `KyuubiConf#getUserDefaults` method, whether the user default configuration need to support the default configuration of different sharelevels, because the same user may use different sharelevels for different tasks.

**Comment by yaooqinn** [comment]
is it a case that the user should put the share-level config in the connection string? you said that this is task-oriented.

I am thinking of a tag-based defaults configuration system to work with user-based together,

1. a tag can be a static value, such as `abc`, `efg`...

+++abc+++.spark.xyz=abc
+++efg+++.spark.xyz=123

2. a tag also can be a variable, that might point to some key like
+++conf:spark.yarn.queue+++.spark.xyz=abc

**Comment by yaooqinn** [comment]
Not yet:)
